### ISSUE TITLE
[🐞]: 

### ISSUE THREAD

**Issue by simoltedal** [MehVahdJukaar/Supplementaries#1035]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2-FORGE

### Supplementaries Version

2.4.20

### Moonlight Lib Version

2.3.6

### Issue Detail

Hey, i set up a modpack recently, a custom one i made on my own. I use it on a server i host myself. In this modpack i have installed Nyf's Spiders mod. These mods seem to be conflicting and have caused a couple crashes for me server wise. The minecraft client didn't crash, the server did. Here is the server log when starting the server. It seems they are in conflict with one another.
19.04 21:04:34 [Server] Server thread/ERROR [!!!!] Some mods (see below stack trace) have errors which will prevent Supplementaries from working correctly.Continuing anyways but you might experience random crashes. You have been warned
19.04 21:04:34 [Server] INFO java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getKey()" because "this.groundDirecton" is null
19.04 21:04:34 [Server] INFO at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.monster.Spider.getGroundSide(Spider.java:903)
19.04 21:04:34 [Server] INFO at TRANSFORMER/spiderstpo@2.0.4/tcb.spiderstpo.common.entity.movement.AdvancedWalkNodeProcessor.findSuitableStartingPosition(AdvancedWalkNodeProcessor.java:221)
19.04 21:04:34 [Server] INFO at TRANSFORMER/spiderstpo@2.0.4/tcb.spiderstpo.common.entity.movement.AdvancedWalkNodeProcessor.m_7171_(AdvancedWalkNodeProcessor.java:179)
19.04 21:04:34 [Server] INFO at TRANSFORMER/spiderstpo@2.0.4/tcb.spiderstpo.common.entity.movement.CustomPathFinder.m_77427_(CustomPathFinder.java:68)
19.04 21:04:34 [Server] INFO at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.navigation.PathNavigation.m_148222_(PathNavigation.java:144)
19.04 21:04:34 [Server] INFO at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.navigation.PathNavigation.m_26551_(PathNavigation.java:126)
19.04 21:04:34 [Server] INFO at TRANSFORMER/spiderstpo@2.0.4/tcb.spiderstpo.common.entity.movement.AdvancedGroundPathNavigator.m_26551_(AdvancedGroundPathNavigator.java:78)
19.04 21:04:34 [Server] INFO at TRANSFORMER/spiderstpo@2.0.4/tcb.spiderstpo.common.entity.movement.AdvancedClimberPathNavigator.m_7864_(AdvancedClimberPathNavigator.java:55)
19.04 21:04:34 [Server] INFO at TRANSFORMER/spiderstpo@2.0.4/tcb.spiderstpo.common.entity.movement.BetterSpiderPathNavigator.m_7864_(BetterSpiderPathNavigator.java:22)
19.04 21:04:34 [Server] INFO at TRANSFORMER/supplementaries@1.19.2-2.4.20/net.mehvahdjukaar.supplementaries.forge.VibeCheck.checkVibe(VibeCheck.java:28)
19.04 21:04:34 [Server] INFO at TRANSFORMER/supplementaries@1.19.2-2.4.20/net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge.onLevelTick(ServerEventsForge.java:209)
19.04 21:04:34 [Server] INFO at TRANSFORMER/supplementaries@1.19.2-2.4.20/net.mehvahdjukaar.supplementaries.common.events.forge.__ServerEventsForge_onLevelTick_LevelTickEvent.invoke(.dynamic)
19.04 21:04:34 [Server] INFO at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
19.04 21:04:34 [Server] INFO at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
19.04 21:04:34 [Server] INFO at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
19.04 21:04:34 [Server] INFO at TRANSFORMER/forge@43.3.5/net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:824)
19.04 21:04:34 [Server] INFO at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:863)
19.04 21:04:34 [Server] INFO at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292)
19.04 21:04:34 [Server] INFO at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
19.04 21:04:34 [Server] INFO at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
19.04 21:04:34 [Server] INFO at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
19.04 21:04:34 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:833)

Just wanted to let you know about it :)

**Comment by Xelbayria** [comment]
Please include the file, latest.log (just drag it in here).  a portion of the log is useless.

**Comment by JLUsr** [comment]
I am going to necro this with a full crash log.

Minecraft 1.21.1
NeoForge 21.1.216
MoonlightLib 2.27.1
Supplementaries 3.5.1
Nyf's Spiders 2.3.2

Creating a new single player world generally results in a CTD shortly after join. Here is a [gist of the crash log](https://gist.github.com/JLUsr/d3637bc75662adaf88a708589eff664f).

**Comment by MehVahdJukaar** [comment]
issue from their mod. missing null check very CLEARLYT from their code

**Comment by MehVahdJukaar** [comment]
closing as unrelated. also because your issue is new but still theri issue
