### ISSUE TITLE
[🐞]: Minecraft wont start whit supplementaries enabled 

### ISSUE THREAD

**Issue by timjae22** [MehVahdJukaar/Supplementaries#1104]
### Before Continuing:

- [ ] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2-FORGE

### Supplementaries Version

supplementaries-1.19.2-2.1.0

### Moonlight Lib Version

moonlight-1.19.2-2.3.6-forge

### Issue Detail

So everytime i try to get into the game after the launcher startet it it says that it failed to load and i cant seem to find the problem.
I changed the version to a older version because the newer one whants a newer create version that i cannot have.
heres the crash report: https://mclo.gs/YvwvTTi     and heres the log:https://mclo.gs/PEr0ahM 
Any help is very apreciatet because i cant play whitout it. (sorry for my bad englisch)

**Comment by Kogomre** [comment]
Similar problem on version 1.20.1 the server does not start

Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.2.20-universal.jar%23448!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.20.1-47.2.20-universal.jar%23448!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23443!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mods: NONE
Stacktrace:
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:152) ~[toml-3.6.4.jar%2359!/:?] {}
-- MOD supplementaries --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:49) ~[Supplementaries-1.20-2.8.17.jar%23420!/:?] {re:classloading}
		at net.mehvahdjukaar.supplementaries.forge.SupplementariesForge.<init>(SupplementariesForge.java:32) ~[Supplementaries-1.20-2.8.17.jar%23420!/:?] {re:classloading,re:mixin}
		at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.20.jar%23445!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.20.jar%23444!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

	Caused by 1: net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigSpecWrapper$ConfigLoadingException: Failed loading config file supplementaries-common.toml of type COMMON for modid supplementaries. Try deleting it
		at net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigSpecWrapper.loadFromFile(ConfigSpecWrapper.java:113) ~[Moonlight-1.20-2.12.8-forge.jar%23383!/:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.mehvahdjukaar.supplementaries.configs.CommonConfigs.<clinit>(CommonConfigs.java:63) ~[Supplementaries-1.20-2.8.17.jar%23420!/:?] {re:classloading}
		at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:49) ~[Supplementaries-1.20-2.8.17.jar%23420!/:?] {re:classloading}
		at net.mehvahdjukaar.supplementaries.forge.SupplementariesForge.<init>(SupplementariesForge.java:32) ~[Supplementaries-1.20-2.8.17.jar%23420!/:?] {re:classloading,re:mixin}
		at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.20.jar%23445!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.20.jar%23444!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

	Mod File: /E:/Games/Minecraft Servers/Forge Skylands 1.20.1/mods/Supplementaries-1.20-2.8.17.jar
	Failure message: Supplementaries (supplementaries) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 1.20-2.8.17
	Mod Issue URL: https://github.com/MehVahdJukaar/Supplementaries/issues
	Exception message: com.electronwill.nightconfig.core.io.ParsingException: Invalid character ']' after key [lore]
Stacktrace:
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:152) ~[toml-3.6.4.jar%2359!/:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.4.jar%2359!/:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:88) ~[toml-3.6.4.jar%2359!/:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.4.jar%2359!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.4.jar%2358!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.4.jar%2358!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.4.jar%2358!/:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.4.jar%2358!/:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.4.jar%2358!/:?] {}
	at net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigSpecWrapper.readConfig(ConfigSpecWrapper.java:132) ~[Moonlight-1.20-2.12.8-forge.jar%23383!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigSpecWrapper.loadFromFile(ConfigSpecWrapper.java:107) ~[Moonlight-1.20-2.12.8-forge.jar%23383!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.mehvahdjukaar.supplementaries.configs.CommonConfigs.<clinit>(CommonConfigs.java:63) ~[Supplementaries-1.20-2.8.17.jar%23420!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:49) ~[Supplementaries-1.20-2.8.17.jar%23420!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.forge.SupplementariesForge.<init>(SupplementariesForge.java:32) ~[Supplementaries-1.20-2.8.17.jar%23420!/:?] {re:classloading,re:mixin}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.20.jar%23445!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.20.jar%23444!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

**Comment by MehVahdJukaar** [comment]
Solution is on first line of that error you posted. Try deleting your config file, it's corrupted

**Comment by Kogomre** [comment]
@MehVahdJukaar yes i do it and this works, thx

**Comment by timjae22** [comment]
so i tryed everything and it still wont work for me is there any other way to fix it?

**Comment by MehVahdJukaar** [comment]
Yes,send latest.log

**Comment by timjae22** [comment]
thx for the help i now fixed it and i can finally play
