### ISSUE TITLE
[🐞]: Update Compat with Farmers Respite

### ISSUE THREAD

**Issue by mlus-asuka** [MehVahdJukaar/Supplementaries#1142]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

1.20-2.8.17

### Moonlight Lib Version

1.20-2.12.20

### Issue Detail

Crash because the kettle change the way it storage water to fluid capability instead of water level

Time: 2024-09-30 14:58:28
Description: Ticking block entity

java.lang.NoSuchFieldError: WATER_LEVEL
	at net.mehvahdjukaar.supplementaries.integration.forge.FarmersRespriteCompatImpl.getWaterLevel(FarmersRespriteCompatImpl.java:10) ~[supplementaries-1.20-2.8.17.jar%23494!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.integration.FarmersRespriteCompat.getWaterLevel(FarmersRespriteCompat.java) ~[supplementaries-1.20-2.8.17.jar%23494!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.block.faucet.KettleInteraction.fill(KettleInteraction.java:38) ~[supplementaries-1.20-2.8.17.jar%23494!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.block.faucet.KettleInteraction.fill(KettleInteraction.java:11) ~[supplementaries-1.20-2.8.17.jar%23494!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.block.tiles.FaucetBlockTile.tryFillingBlockBelow(FaucetBlockTile.java:178) ~[supplementaries-1.20-2.8.17.jar%23494!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.block.tiles.FaucetBlockTile.runInteractions(FaucetBlockTile.java:162) ~[supplementaries-1.20-2.8.17.jar%23494!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.block.tiles.FaucetBlockTile.tryExtract(FaucetBlockTile.java:145) ~[supplementaries-1.20-2.8.17.jar%23494!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.block.tiles.FaucetBlockTile.tick(FaucetBlockTile.java:93) ~[supplementaries-1.20-2.8.17.jar%23494!/:?] {re:classloading}

**Comment by mlus-asuka** [comment]
ok same as #1115

**Comment by MehVahdJukaar** [comment]
Weird I thought I removed that stuff
