### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by mcenderdragon** [MehVahdJukaar/Supplementaries#119]
[crash-2021-09-30_22.12.08-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/7262234/crash-2021-09-30_22.12.08-fml.txt
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/7262241/latest.log)
)
```

Caused by 0: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/jozufozu/flywheel/backend/material/MaterialManager
		at net.mehvahdjukaar.supplementaries.compat.flywheel.FlywheelPlugin.registerInstances(FlywheelPlugin.java:13) ~[supplementaries:1.16.5-0.17.2] {re:classloading}
		at net.mehvahdjukaar.supplementaries.compat.CompatHandlerClient.init(CompatHandlerClient.java:24) ~[supplementaries:1.16.5-0.17.2] {re:classloading}
		at net.mehvahdjukaar.supplementaries.setup.ClientSetup.init(ClientSetup.java:68) ~[supplementaries:1.16.5-0.17.2] 
```

**Comment by MehVahdJukaar** [comment]
Update flywheel

**Comment by mcenderdragon** [comment]
ahh ok, thanks.
