### ISSUE TITLE
[🐞]: Instant Crash on Joining [Fabric 1.21.1 Huge Modpack Test Enviroment to Fix Compat issues]

### ISSUE THREAD

**Issue by suerion** [MehVahdJukaar/Supplementaries#1196]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-FABRIC

### Supplementaries Version

Supplementaries 1.21-3.0.8-alpha (shows 3.0.6)

### Moonlight Lib Version

moonlight-1.21-2.15.13

### Issue Detail

Crashlog from Client:
https://mclo.gs/q5i3TH5

```
[20:27:48] [Render thread/WARN]: Strict error handling was triggered, but disconnection was prevented
[20:27:48] [Render thread/ERROR]: Failed to handle packet net.minecraft.class_8733@5540ac19
java.lang.NullPointerException: null
	at knot/com.google.common.collect.Iterators$6.transform(Iterators.java:829) ~[guava-32.1.2-jre.jar:?]
	at knot/com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52) ~[guava-32.1.2-jre.jar:?]
	at knot/net.mehvahdjukaar.supplementaries.common.block.dispenser.DispenserBehaviorsManager.registerBehaviors(DispenserBehaviorsManager.java:149) ~[supplementaries-1.21-3.0.8-alpha-fabric.jar:?]
	at knot/net.mehvahdjukaar.moonlight.api.util.DispenserHelper.lambda$reload$1(DispenserHelper.java:115) ~[moonlight-1.21-2.15.13-fabric.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at knot/net.mehvahdjukaar.moonlight.api.util.DispenserHelper.reload(DispenserHelper.java:115) ~[moonlight-1.21-2.15.13-fabric.jar:?]
	at knot/net.mehvahdjukaar.moonlight.core.Moonlight.afterDataReload(Moonlight.java:125) ~[moonlight-1.21-2.15.13-fabric.jar:?]
	at knot/net.fabricmc.fabric.api.event.lifecycle.v1.CommonLifecycleEvents.lambda$static$0(CommonLifecycleEvents.java:33) ~[fabric-lifecycle-events-v1-2.4.0+0f6c53cd19-c6aff05668ba7382.jar:?]
	at knot//MC/net.minecraft.client.network.ClientTagLoader.handler$edm000$fabric-lifecycle-events-v1$invokeTagsLoaded(ClientTagLoader.java:1033) ~[client-intermediary.jar:?]
	at knot//MC/net.minecraft.client.network.ClientTagLoader.load(ClientTagLoader.java:44) ~[client-intermediary.jar:?]
	at knot//MC/net.minecraft.client.network.ClientRegistries.createRegistryManager(ClientRegistries.java:70) ~[client-intermediary.jar:?]
	at knot//MC/net.minecraft.client.network.ClientConfigurationNetworkHandler.method_57043(ClientConfigurationNetworkHandler.java:117) ~[client-intermediary.jar:?]
	at knot//MC/net.minecraft.client.network.ClientConfigurationNetworkHandler.openClientDataPack(ClientConfigurationNetworkHandler.java:109) ~[client-intermediary.jar:?]
	at knot//MC/net.minecraft.client.network.ClientConfigurationNetworkHandler.onReady(ClientConfigurationNetworkHandler.java:117) ~[client-intermediary.jar:?]
	at knot//MC/net.minecraft.network.packet.s2c.config.ReadyS2CPacket.apply(ReadyS2CPacket.java:22) ~[client-intermediary.jar:?]
	at knot//MC/net.minecraft.network.packet.s2c.config.ReadyS2CPacket.apply(ReadyS2CPacket.java:8) ~[client-intermediary.jar:?]
	at knot//MC/net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:27) ~[client-intermediary.jar:?]
	at knot//MC/net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:162) [client-intermediary.jar:?]
	at knot//MC/net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [client-intermediary.jar:?]
	at knot//MC/net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:136) [client-intermediary.jar:?]
	at knot//MC/net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:121) [client-intermediary.jar:?]
	at knot//MC/net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1240) [client-intermediary.jar:?]
	at knot//MC/net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
[20:28:17] [Netty Client IO #2/ERROR]: Exception occurred in netty pipeline
io.netty.handler.timeout.ReadTimeoutException: null
[20:28:18] [Render thread/ERROR]: Negative index in crash report handler (0/8)
[20:28:18] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.util.crash.CrashException: Ticking screen
	at knot//MC/net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:436) ~[client-intermediary.jar:?]
	at knot//MC/net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1930) ~[client-intermediary.jar:?]
	at knot//MC/net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1246) ~[client-intermediary.jar:?]
	at knot//MC/net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.NullPointerException
```

Latest.log
https://mclo.gs/X2WMX8M

**Comment by suerion** [comment]
Without hopper, it does also not work, will look on min server enviroment

**Comment by suerion** [comment]
Hey, had tried to use an lower modpack, now i had this issue -> Crash instant on server joining ->

```
Registry remapping failed!
java.util.concurrent.CompletionException: java.lang.RuntimeException: Errors while remapping Int2ObjectMap ItemModels.modelIds found:
 - Map contained two equal IDs 2128 (arborealnature:quince_hanging_sign/2128 -> arborealnature:quince_hanging_sign/2128)!
 - Map contained two equal IDs 2120 (arborealnature:hornbeam_sign/2090 -> arborealnature:hornbeam_sign/2120)!
 - Map contained two equal IDs 2126 (arborealnature:hornbeam_hanging_sign/2102 -> arborealnature:hornbeam_hanging_sign/2126)!
 - Map contained two equal IDs 2123 (arborealnature:plum_sign/2093 -> arborealnature:plum_sign/2123)!
 - Map contained two equal IDs 2121 (arborealnature:hawthorn_sign/2121 -> arborealnature:hawthorn_sign/2121)!
 - Map contained two equal IDs 2127 (arborealnature:hawthorn_hanging_sign/2127 -> arborealnature:hawthorn_hanging_sign/2127)!
 - Map contained two equal IDs 2119 (arborealnature:hazelnut_sign/2089 -> arborealnature:hazelnut_sign/2119)!
 - Map contained two equal IDs 2130 (arborealnature:mango_hanging_sign/2106 -> arborealnature:mango_hanging_sign/2130)!
 - Map contained two equal IDs 2124 (arborealnature:mango_sign/2094 -> arborealnature:mango_sign/2124)!
 - Map contained two equal IDs 2125 (arborealnature:hazelnut_hanging_sign/2101 -> arborealnature:hazelnut_hanging_sign/2125)!
 - Map contained two equal IDs 2129 (arborealnature:plum_hanging_sign/2129 -> arborealnature:plum_hanging_sign/2129)!
 - Map contained two equal IDs 2122 (arborealnature:quince_sign/2122 -> arborealnature:quince_sign/2122)!
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) [?:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.RuntimeException: Errors while remapping Int2ObjectMap ItemModels.modelIds found:
 - Map contained two equal IDs 2128 (arborealnature:quince_hanging_sign/2128 -> arborealnature:quince_hanging_sign/2128)!
 - Map contained two equal IDs 2120 (arborealnature:hornbeam_sign/2090 -> arborealnature:hornbeam_sign/2120)!
 - Map contained two equal IDs 2126 (arborealnature:hornbeam_hanging_sign/2102 -> arborealnature:hornbeam_hanging_sign/2126)!
 - Map contained two equal IDs 2123 (arborealnature:plum_sign/2093 -> arborealnature:plum_sign/2123)!
 - Map contained two equal IDs 2121 (arborealnature:hawthorn_sign/2121 -> arborealnature:hawthorn_sign/2121)!
 - Map contained two equal IDs 2127 (arborealnature:hawthorn_hanging_sign/2127 -> arborealnature:hawthorn_hanging_sign/2127)!
 - Map contained two equal IDs 2119 (arborealnature:hazelnut_sign/2089 -> arborealnature:hazelnut_sign/2119)!
 - Map contained two equal IDs 2130 (arborealnature:mango_hanging_sign/2106 -> arborealnature:mango_hanging_sign/2130)!
 - Map contained two equal IDs 2124 (arborealnature:mango_sign/2094 -> arborealnature:mango_sign/2124)!
 - Map contained two equal IDs 2125 (arborealnature:hazelnut_hanging_sign/2101 -> arborealnature:hazelnut_hanging_sign/2125)!
 - Map contained two equal IDs 2129 (arborealnature:plum_hanging_sign/2129 -> arborealnature:plum_hanging_sign/2129)!
 - Map contained two equal IDs 2122 (arborealnature:quince_sign/2122 -> arborealnature:quince_sign/2122)!
	at knot/net.fabricmc.fabric.impl.registry.sync.trackers.Int2ObjectMapTracker.onRemap(Int2ObjectMapTracker.java:89) ~[fabric-registry-sync-v0-5.1.2+60c3209b6a-a2b2ad91afa06615.jar:?]
	at knot/net.minecraft.class_2370.mdc4ac6e$fabric-registry-sync-v0$lambda$init$2$1(class_2370.java:1140) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2370.remap(class_2370.java:1352) ~[client-intermediary.jar:?]
	at knot/net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:280) ~[fabric-registry-sync-v0-5.1.2+60c3209b6a-a2b2ad91afa06615.jar:?]
	at knot/net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:141) ~[fabric-registry-sync-v0-5.1.2+60c3209b6a-a2b2ad91afa06615.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 10 more
Reported exception thrown!
net.minecraft.class_148: Ticking screen
	at knot/net.minecraft.class_437.method_25412(class_437.java:436) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1574(class_310.java:1930) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1246) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.NullPointerException
	at knot/com.google.common.collect.Iterators$6.transform(Iterators.java:829) ~[guava-32.1.2-jre.jar:?]
	at knot/com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52) ~[guava-32.1.2-jre.jar:?]
	at knot/net.minecraft.class_2370.remap(class_2370.java:1247) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2370.unmap(class_2370.java:1378) ~[client-intermediary.jar:?]
	at knot/net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.unmap(RegistrySyncManager.java:367) ~[fabric-registry-sync-v0-5.1.2+60c3209b6a-a2b2ad91afa06615.jar:?]
	at knot/net.minecraft.class_310.handler$zcl000$fabric-registry-sync-v0$disconnectAfter(class_310.java:4191) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_18096(class_310.java:2269) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8673.method_10839(class_8673.java:319) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8674.method_10839(class_8674.java:148) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2535.method_10768(class_2535.java:673) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_412.method_25393(class_412.java:175) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1572(class_310.java:1930) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 7 more

```

Crashlog:
https://mclo.gs/gy7WMKM

Latest.log:
https://mclo.gs/hT2G6Sm

**Comment by suerion** [comment]
Sorry for the issue, found the issuer -> https://modrinth.com/mod/arboreal-nature

Will add there an issue
