### ISSUE TITLE
[🐞]: Can't start fabric server with 1.21.1 supplementaries

### ISSUE THREAD

**Issue by BigMouthFlower** [MehVahdJukaar/Supplementaries#1232]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-FABRIC

### Supplementaries Version

supplementaries-1.21-3.0.20-beta-fabric

### Moonlight Lib Version

moonlight-1.21-2.17.5-fabric

### Issue Detail

I use this version of supplementaries and moonlight  and they run properly on singleplayer. But when I put them on server, the server can't start.
latest.log:
```
[17:49:19] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.7
[17:49:20] [ForkJoinPool-1-worker-4/WARN]: Mod gca uses the version mc1.21-2.9.0+build.57 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'mc1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:49:20] [main/WARN]: Warnings were found!
 - 模组 'Forge Config API Port' (forgeconfigapiport) 21.1.0 建议安装 modmenu 的 任意版本，但没有安装它！
	 - 为了最佳体验，您应该安装 modmenu 的 任意版本。
[17:49:20] [main/INFO]: Loading 90 mods:
	- carpet 1.4.147+v240613
	- fabric-api 0.107.0+1.21.1
	   |-- fabric-api-base 0.4.42+6573ed8c19
	   |-- fabric-api-lookup-api-v1 1.6.69+b559734419
	   |-- fabric-biome-api-v1 13.0.30+be1ed2d719
	   |-- fabric-block-api-v1 1.0.22+0af3f5a719
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
	   |-- fabric-command-api-v1 1.2.49+f71b366f19
	   |-- fabric-command-api-v2 2.2.28+6ced4dd919
	   |-- fabric-commands-v0 0.2.66+df3654b319
	   |-- fabric-content-registries-v0 8.0.17+b559734419
	   |-- fabric-convention-tags-v1 2.1.1+7f945d5b19
	   |-- fabric-convention-tags-v2 2.9.1+7fd4837519
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
	   |-- fabric-data-attachment-api-v1 1.2.0+e49211d819
	   |-- fabric-data-generation-api-v1 20.2.22+16c4ae2519
	   |-- fabric-dimensions-v1 4.0.0+6fc22b9919
	   |-- fabric-entity-events-v1 1.7.0+2122d82819
	   |-- fabric-events-interaction-v0 0.7.13+ba9dae0619
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
	   |-- fabric-item-api-v1 11.1.1+d5debaed19
	   |-- fabric-item-group-api-v1 4.1.6+6823f7cd19
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a719
	   |-- fabric-keybindings-v0 0.2.45+df3654b319
	   |-- fabric-lifecycle-events-v1 2.4.0+0f6c53cd19
	   |-- fabric-loot-api-v2 3.0.15+3f89f5a519
	   |-- fabric-loot-api-v3 1.0.3+3f89f5a519
	   |-- fabric-message-api-v1 6.0.13+6573ed8c19
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
	   |-- fabric-networking-api-v1 4.3.0+c7469b2119
	   |-- fabric-object-builder-api-v1 15.2.1+40875a9319
	   |-- fabric-particles-v1 4.0.2+6573ed8c19
	   |-- fabric-recipe-api-v1 5.0.13+6508971219
	   |-- fabric-registry-sync-v0 5.1.3+60c3209b19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-renderer-indigo 1.7.0+c705a49c19
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b319
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   |-- fabric-rendering-v0 1.1.71+df3654b319
	   |-- fabric-rendering-v1 5.0.5+df16efd019
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
	   |-- fabric-resource-loader-v0 1.3.1+5b5275af19
	   |-- fabric-screen-api-v1 2.0.25+8b68f1c719
	   |-- fabric-screen-handler-api-v1 1.3.87+b559734419
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c19
	   |-- fabric-transfer-api-v1 5.4.1+95bead5f19
	   \-- fabric-transitive-access-wideners-v1 6.1.0+1daea21519
	- fabricloader 0.16.7
	   \-- mixinextras 0.4.1
	- farmersdelight 1.21-2.1.10+refabricated
	   |-- mm 2.3
	   |-- porting_lib_base 3.1.0-beta+fdrf.1+1.21
	   |    |-- com_electronwill_night-config_core 3.8.0
	   |    |-- com_electronwill_night-config_toml 3.8.0
	   |    |-- mm 2.3
	   |    |-- porting_lib_accessors 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_asm 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_attributes 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_blocks 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_common 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_entity 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_extensions 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_fluids 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_gui_utils 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_mixin_extensions 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_tags 3.0
	   |    \-- porting_lib_transfer 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_config 3.1.0-beta+fdrf.1+1.21
	   |    |-- com_electronwill_night-config_core 3.8.0
	   |    |-- com_electronwill_night-config_toml 3.8.0
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_item_abilities 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_blocks 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_level_events 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_lazy_registration 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_loot 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_conditions 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   \-- porting_lib_recipe_book_categories 3.1.0-beta+fdrf.1+1.21
	        |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	        \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	- gca mc1.21-2.9.0+build.57
	- java 22
	- jei 19.21.0.247
	- minecraft 1.21.1
	- moonlight 1.21-2.17.5
	- netmusic 1.0.0
	   |-- com_googlecode_soundlibs_jlayer 1.0.1.4
	   |-- com_googlecode_soundlibs_mp3spi 1.9.5.4
	   |-- com_googlecode_soundlibs_tritonus-share 0.3.7.4
	   \-- yet_another_config_lib_v3 3.5.0+1.21-fabric
	        |-- com_twelvemonkeys_common_common-image 3.10.0
	        |-- com_twelvemonkeys_common_common-io 3.10.0
	        |-- com_twelvemonkeys_common_common-lang 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	        |-- org_quiltmc_parsers_gson 0.2.1
	        \-- org_quiltmc_parsers_json 0.2.1
	- pineapple_delight 1.0.0
	- smallships 2.0.0-b1.5
	   \-- forgeconfigapiport 21.1.0
	        |-- com_electronwill_night-config_core 3.8.0
	        \-- com_electronwill_night-config_toml 3.8.0
	- storagedelight 24.9.11-1.21-fabric
	- supplementaries 1.21-3.0.20-beta
	   \-- mixinsquared 0.1.1
[17:49:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/home/minecraft/multicraft/servers/server14104/libraries/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[17:49:20] [main/INFO]: Compatibility level set to JAVA_17
[17:49:20] [main/INFO]: Compatibility level set to JAVA_21
[17:49:20] [main/WARN]: Reference map 'forgeconfigapiport.common.refmap.json' for forgeconfigapiport.common.mixins.json could not be read. If this is a development environment you can ignore this message
[17:49:21] [main/WARN]: Error loading class: net/minecraft/class_881 (java.lang.ClassNotFoundException: net/minecraft/class_881)
[17:49:21] [main/WARN]: @Mixin target net.minecraft.class_881 was not found porting_lib_base.mixins.json:client.BoatRendererMixin from mod porting_lib_base
[17:49:21] [main/WARN]: Error loading class: net/minecraft/class_525 (java.lang.ClassNotFoundException: net/minecraft/class_525)
[17:49:21] [main/WARN]: @Mixin target net.minecraft.class_525 was not found porting_lib_base.mixins.json:client.CreateWorldScreenMixin from mod porting_lib_base
[17:49:21] [main/WARN]: Error loading class: net/minecraft/class_906 (java.lang.ClassNotFoundException: net/minecraft/class_906)
[17:49:21] [main/WARN]: @Mixin target net.minecraft.class_906 was not found porting_lib_item_abilities.mixins.json:FishingHookRendererMixin from mod porting_lib_item_abilities
[17:49:21] [main/WARN]: Error loading class: net/minecraft/class_638 (java.lang.ClassNotFoundException: net/minecraft/class_638)
[17:49:21] [main/WARN]: @Mixin target net.minecraft.class_638 was not found porting_lib_level_events.mixins.json:client.ClientLevelMixin from mod porting_lib_level_events
[17:49:21] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/FluidRenderer (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/FluidRenderer)
[17:49:21] [main/WARN]: Error loading class: net/minecraft/class_314 (java.lang.ClassNotFoundException: net/minecraft/class_314)
[17:49:21] [main/WARN]: @Mixin target net.minecraft.class_314 was not found mixins.mm.json:net.minecraft.class_314 from mod mm
[17:49:21] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[17:49:25] [main/WARN]: Method overwrite conflict for getClimateSettings in supplementaries.mixins.json:BiomeAccessor from mod supplementaries, previously written by carpet.mixins.Biome_scarpetMixin. Skipping method.
[17:49:32] [main/ERROR]: No data fixer registered for rotten_tomato
[17:49:33] [main/INFO]: Definitely not up to no good
[17:49:33] [main/INFO]: Deserializing GeneralConfig from './config/netmusic/common.json5'
[17:49:33] [main/INFO]: Loaded config supplementaries-common.json
[17:49:33] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'supplementaries' at 'net.mehvahdjukaar.supplementaries.fabric.SupplementariesFabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.7.jar:?]
	at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [java22.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_638
	at knot/net.mehvahdjukaar.supplementaries.common.network.ModNetwork.registerMessages(ModNetwork.java:20) ~[supplementaries-1.21-3.0.20-beta-fabric.jar:?]
	at knot/net.mehvahdjukaar.moonlight.api.platform.network.fabric.NetworkHelperImpl.addNetworkRegistration(NetworkHelperImpl.java:27) ~[moonlight-1.21-2.17.5-fabric.jar:?]
	at knot/net.mehvahdjukaar.moonlight.api.platform.network.NetworkHelper.addNetworkRegistration(NetworkHelper.java) ~[moonlight-1.21-2.17.5-fabric.jar:?]
	at knot/net.mehvahdjukaar.supplementaries.common.network.ModNetwork.init(ModNetwork.java:8) ~[supplementaries-1.21-3.0.20-beta-fabric.jar:?]
	at knot/net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:63) ~[supplementaries-1.21-3.0.20-beta-fabric.jar:?]
	at knot/net.mehvahdjukaar.supplementaries.fabric.SupplementariesFabric.onInitialize(SupplementariesFabric.java:19) ~[supplementaries-1.21-3.0.20-beta-fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.7.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.7.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at knot/net.mehvahdjukaar.supplementaries.common.network.ModNetwork.registerMessages(ModNetwork.java:20) ~[supplementaries-1.21-3.0.20-beta-fabric.jar:?]
	at knot/net.mehvahdjukaar.moonlight.api.platform.network.fabric.NetworkHelperImpl.addNetworkRegistration(NetworkHelperImpl.java:27) ~[moonlight-1.21-2.17.5-fabric.jar:?]
	at knot/net.mehvahdjukaar.moonlight.api.platform.network.NetworkHelper.addNetworkRegistration(NetworkHelper.java) ~[moonlight-1.21-2.17.5-fabric.jar:?]
	at knot/net.mehvahdjukaar.supplementaries.common.network.ModNetwork.init(ModNetwork.java:8) ~[supplementaries-1.21-3.0.20-beta-fabric.jar:?]
	at knot/net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:63) ~[supplementaries-1.21-3.0.20-beta-fabric.jar:?]
	at knot/net.mehvahdjukaar.supplementaries.fabric.SupplementariesFabric.onInitialize(SupplementariesFabric.java:19) ~[supplementaries-1.21-3.0.20-beta-fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.7.jar:?]
	... 7 more

```

**Comment by MehVahdJukaar** [comment]
fixed
