### ISSUE TITLE
[🐞]: Repeating console entry freezes computer

### ISSUE THREAD

**Issue by GreenVoltage** [MehVahdJukaar/Supplementaries#1263]
### Before Continuing:

- [x] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-FABRIC

### Supplementaries Version

supplementaries-1.21-3.0.25-beta-fabric

### Moonlight Lib Version

moonlight-1.21-2.17.7-fabric

### Describe Issue

This started happening randomly mid-game on a modded server and now every time I try to join this server my entire computer starts freezing up.
And this set of lines keeps repeating multiple times per second in the console window:

<details>
<summary>Partially of latest.log</summary>

[01:55:05] [Render thread/WARN]: Failed to load shader: supplementaries:shaders/post/flare.json
net.minecraft.class_2973: Invalid shaders/post/flare.json (supplementaries) passes[0]: Cannot invoke "net.minecraft.class_2960.method_12836()" because "$$0" is null
at knot/net.minecraft.class_2973.method_12856(class_2973.java:48) ~[client-intermediary.jar:?]
at knot/net.minecraft.class_279.method_1256(class_279.java:89) ~[client-intermediary.jar:?]
at knot/net.minecraft.class_279.<init>(class_279.java:57) ~[client-intermediary.jar:?]
at knot/net.minecraft.class_757.method_3168(class_757.java:349) ~[client-intermediary.jar:?]
at knot/net.mehvahdjukaar.supplementaries.common.events.ClientEvents.applyMobHeadShaders(ClientEvents.java:166) ~[supplementaries-1.21-3.0.23-beta-fabric.jar:?]
at knot/net.mehvahdjukaar.supplementaries.common.events.ClientEvents.onClientTick(ClientEvents.java:124) ~[supplementaries-1.21-3.0.23-beta-fabric.jar:?]
at knot/net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.5.0+01d9a51c19-8ff401bae2cee6b0.jar:?]
at knot/net.minecraft.class_310.handler$bjd000$fabric-lifecycle-events-v1$onEndTick(class_310.java:9185) [client-intermediary.jar:?]
at knot/net.minecraft.class_310.method_1574(class_310.java:2012) [client-intermediary.jar:?]
at knot/net.minecraft.class_310.method_1523(class_310.java:1246) [client-intermediary.jar:?]
at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.method_12836()" because "$$0" is null
at knot/net.minecraft.class_6861.method_14486(class_6861.java:79) ~[client-intermediary.jar:?]
at knot/net.minecraft.class_3304.method_14486(class_3304.java:52) ~[client-intermediary.jar:?]
at knot/net.minecraft.class_5912.getResourceOrThrow(class_5912.java:23) ~[client-intermediary.jar:?]
at knot/net.minecraft.class_280.<init>(class_280.java:77) ~[client-intermediary.jar:?]
at knot/net.minecraft.class_283.<init>(class_283.java:32) ~[client-intermediary.jar:?]
at knot/net.minecraft.class_279.method_1262(class_279.java:284) ~[client-intermediary.jar:?]
at knot/net.minecraft.class_279.method_1257(class_279.java:138) ~[client-intermediary.jar:?]
at knot/net.minecraft.class_279.method_1256(class_279.java:87) ~[client-intermediary.jar:?]
... 16 more

</details>

It only does this in that specific server, and I don't know how to recreate this in singleplayer or sumthin to test this with the mod by itself,,
Here's every server-required mod just in-case:
<ul>
	<li>Amendments</li>
	<li>CICADA</li>
	<li>Cardinal Components API</li>
	<li>Cloth Config v15</li>
	<li>Fabric API</li>
	<li>Farmer's Delight</li>
	<li>Gauntlets</li>
	<li>Just Enough Items</li>
	<li>Moonlight Lib</li>
	<li>Pehkui</li>
	<li>Placeholder API</li>
	<li>Supplementaries</li>
	<li>Traveler's Backpack</li>
	<li>YetAnotherConfigLib</li>
	<li>oωo</li>
</ul>

**Comment by MehVahdJukaar** [comment]
try new versions

**Comment by GreenVoltage** [comment]
seems to be fixed!
