### ISSUE TITLE
[🐞]: Server crash when removing written book from lectern

### ISSUE THREAD

**Issue by FreyrDev** [MehVahdJukaar/Supplementaries#1269]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-FABRIC

### Supplementaries Version

supplementaries-1.21-3.0.25-beta-fabric

### Moonlight Lib Version

moonlight-1.21-2.17.10-fabric

### Describe Issue

Internal server crashes when taking a written book or book & quill from a lectern.

<details>
<summary>disconnect-2024-12-06_00.51.52-client.txt</summary>

```
---- Minecraft Network Protocol Error Report ----
// I'm sorry, I don't speak that language

Time: 2024-12-06 00:51:52
Description: Packet handling error

java.lang.NullPointerException: Cannot invoke "net.mehvahdjukaar.supplementaries.common.block.IAntiquable.supplementaries$setAntique(boolean)" because "original" is null
	at knot//net.minecraft.class_3872$class_3931.modifyReturnValue$bih000$supplementaries$supp$checkAntiqueInk(class_3872.java:522)
	at knot//net.minecraft.class_3872$class_3931.method_17562(class_3872.java:55)
	at knot//net.minecraft.class_3935.method_17574(class_3935.java:99)
	at knot//net.minecraft.class_3935$1.method_7635(class_3935.java:21)
	at knot//net.minecraft.class_1703.method_34246(class_1703.java:219)
	at knot//net.minecraft.class_1703.method_7623(class_1703.java:176)
	at knot//net.minecraft.class_1703.method_7609(class_1703.java:589)
	at knot//net.minecraft.class_3916$1.method_7668(class_3916.java:35)
	at knot//net.minecraft.class_1735.method_7673(class_1735.java:76)
	at knot//net.minecraft.class_1703.method_7619(class_1703.java:593)
	at knot//net.minecraft.class_634.method_11109(class_634.java:1261)
	at knot//net.minecraft.class_2653.method_11451(class_2653.java:49)
	at knot//net.minecraft.class_2653.method_11054(class_2653.java:10)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1240)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_3872$class_3931.modifyReturnValue$bih000$supplementaries$supp$checkAntiqueInk(class_3872.java:522)
	at knot//net.minecraft.class_3872$class_3931.method_17562(class_3872.java:55)
	at knot//net.minecraft.class_3935.method_17574(class_3935.java:99)
	at knot//net.minecraft.class_3935$1.method_7635(class_3935.java:21)
	at knot//net.minecraft.class_1703.method_34246(class_1703.java:219)
	at knot//net.minecraft.class_1703.method_7623(class_1703.java:176)
	at knot//net.minecraft.class_1703.method_7609(class_1703.java:589)
	at knot//net.minecraft.class_3916$1.method_7668(class_3916.java:35)
	at knot//net.minecraft.class_1735.method_7673(class_1735.java:76)
	at knot//net.minecraft.class_1703.method_7619(class_1703.java:593)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:container_set_slot
	Is Terminal: false
	Is Skippable: false
Stacktrace:
	at knot//net.minecraft.class_2600.method_59803(class_2600.java:56)
	at knot//net.minecraft.class_8673.method_60882(class_8673.java:136)
	at knot//net.minecraft.class_8673.method_59807(class_8673.java:113)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:32)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1240)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: <none>
	Server brand: fabric

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.9.3-76060903-generic
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 7868012832 bytes (7503 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600H with Radeon Graphics
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 4.28
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: GA106M [GeForce RTX 3060 Mobile / Max-Q]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MiB): 8224.00
	Graphics card #0 deviceId: 0x2560
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: Cezanne
	Graphics card #1 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #1 VRAM (MiB): 258.00
	Graphics card #1 deviceId: 0x1638
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MiB): 24835.97
	Virtual memory used (MiB): 14198.09
	Swap memory total (MiB): 17922.49
	Swap memory used (MiB): 3081.61
	Space in storage for jna.tmpdir (MiB): available: 792721.00, total: 928723.38
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 792721.00, total: 928723.38
	Space in storage for io.netty.native.workdir (MiB): available: 792721.00, total: 928723.38
	Space in storage for java.io.tmpdir (MiB): available: 792721.00, total: 928723.38
	Space in storage for workdir (MiB): available: 792721.00, total: 928723.38
	JVM Flags: 9 total; -Xss1M -Xms8G -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		emi: EMI 1.1.18+1.21.1+fabric
		fabric-api: Fabric API 0.107.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.69+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.17+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.1+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.1+7fd4837519
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.2.0+e49211d819
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.22+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.4.0+0f6c53cd19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.1+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.3
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		moonlight: Moonlight Lib 1.21-2.17.10
		sodium: Sodium 0.6.0+mc1.21.1
		supplementaries: Supplementaries 1.21-3.0.25-beta
			mixinsquared: MixinSquared 0.1.1
```
</details>

**Comment by MehVahdJukaar** [comment]
fixed
