### ISSUE TITLE
[🐞]: Game always crash when XP bottlering with a Jar

### ISSUE THREAD

**Issue by darceno** [MehVahdJukaar/Supplementaries#1284]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-3.1.10

### Moonlight Lib Version

moonlight-1.20-2.13.40-forge

### Describe Issue

Crash report: https://pastebin.com/tLNapkTF

Using a glass bottle works fine.

**Comment by BigJMoney** [comment]
I also get this crash, and can confirm it doesn't happen with a bottle.  Callstack looks similar to me:

`[18Jun2025 16:32:45.025] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.registryAccess()" because the return value of "net.minecraft.world.level.block.entity.BlockEntity.getLevel()" is null
	at TRANSFORMER/supplementaries@1.21-3.1.7/net.mehvahdjukaar.supplementaries.common.utils.BlockUtil.loadTileFromItem(BlockUtil.java:67) ~[supplementaries-1.21-3.1.7-neoforge.jar%23467!/:?]
	at TRANSFORMER/supplementaries@1.21-3.1.7/net.mehvahdjukaar.supplementaries.common.events.overrides.XPBottlingBehavior.tryPerformingAction(XPBottlingBehavior.java:57) ~[supplementaries-1.21-3.1.7-neoforge.jar%23467!/:?]
	at TRANSFORMER/supplementaries@1.21-3.1.7/net.mehvahdjukaar.supplementaries.common.events.overrides.InteractEventsHandler.onItemUsedOnBlock(InteractEventsHandler.java:163) ~[supplementaries-1.21-3.1.7-neoforge.jar%23467!/:?]
	at TRANSFORMER/supplementaries@1.21-3.1.7/net.mehvahdjukaar.supplementaries.common.events.ServerEvents.onRightClickBlock(ServerEvents.java:90) ~[supplementaries-1.21-3.1.7-neoforge.jar%23467!/:?]
	at TRANSFORMER/supplementaries@1.21-3.1.7/net.mehvahdjukaar.supplementaries.common.events.neoforge.ServerEventsForge.onUseBlock(ServerEventsForge.java:55) ~[supplementaries-1.21-3.1.7-neoforge.jar%23467!/:?]`

1.21.1 NeoForge, Suppl. v. 3.1.7

**Comment by MehVahdJukaar** [comment]
fixed
