### ISSUE TITLE
[🐞]: Some mod breaks the Sheets class and crashes game on world join (If "Supplementaries" AND "Sleep Tight" are installed)

### ISSUE THREAD

**Issue by User4716** [MehVahdJukaar/Supplementaries#1295]
```
📌 Soft-Fix for this issue has been found:
Deleting "Sleep Tight" or "Supplementaries" makes the Sheet class not crash the game.
```
___

### Checklist:

- [X] Modloader is up to date
- [X] Every mod in the modpack uses its latest version
- [X] A clean boot has been performed (Meaning a boot after deleting every file except the mods folder)

___

### Modpack information:

- 1.20.1 FABRIC v0.16.9
- supplementaries-1.20-3.1.10
- moonlight-1.20-2.13.42

___

### What happened:
- To reproduce this crash, you need to have **Supplementaries**, **Sleep Tight**, and a **third unknown mod** installed and join a world.

![image](https://github.com/user-attachments/assets/c32dec85-d780-43a9-acce-4b67dd905634)

**Logs:**
[**crash-server.txt**](https://github.com/user-attachments/files/18252535/crash-2024-12-26_13.48.45-server.txt)
[**latest.log**](https://github.com/user-attachments/files/18252533/latest.log)

```
Description: Exception in server tick loop

net.mehvahdjukaar.supplementaries.common.utils.VibeChecker$BadModError: Some OTHER mod loaded the Sheets class to early, causing modded banner patterns and sherds textures to not include modded ones.
Refusing to proceed further.
Missing entries: [ResourceKey[minecraft:banner_pattern / sleep_tight:moon]] (mods listed here are NOT the cause of this, merely the ones that got broken because of it)
Check previous forge log lines to find the offending mod.
	at knot//net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.clientStuff(VibeChecker.java:90)
	at knot//net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.checkVibe(VibeChecker.java:42)
	at knot//net.mehvahdjukaar.supplementaries.common.events.ServerEvents.onPlayerLoggedIn(ServerEvents.java:121)
	at knot//net.mehvahdjukaar.supplementaries.common.events.fabric.ServerEventsFabric.lambda$init$0(ServerEventsFabric.java:40)
	at knot//net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48)
	at knot//net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:66)
	at knot//MC//net.minecraft.server.PlayerManager.handler$fci001$fabric-networking-api-v1$handlePlayerConnection(PlayerManager.java:7518)
	at knot//MC//net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager.java:215)
	at knot//MC//net.minecraft.server.network.ServerLoginNetworkHandler.addToServer(ServerLoginNetworkHandler.java:131)
	at knot//MC//net.minecraft.server.network.ServerLoginNetworkHandler.md178e08$polymer-networking$lambda$polymerNet$prePlayHandshakeHackfest$0$0(ServerLoginNetworkHandler.java:549)
	at knot//eu.pb4.polymer.networking.impl.EarlyConnectionMagic.lambda$handle$0(EarlyConnectionMagic.java:32)
	at knot//eu.pb4.polymer.networking.api.EarlyPlayNetworkHandler.lambda$onKeepAlive$0(EarlyPlayNetworkHandler.java:108)
	at knot//MC//net.minecraft.server.ServerTask.run(ServerTask.java:18)
	at knot//MC//net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156)
	at knot//MC//net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23)
	at knot//net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:782)
	at knot//net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:164)
	at knot//MC//net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130)
	at knot//net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:21818)
	at knot//net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:758)
	at knot//MC//net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:139)
	at knot//net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:743)
	at knot//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:675)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
```

**Comment by Poopooracoocoo** [comment]
Did you ever identify what was causing the issue?

**Comment by MehVahdJukaar** [comment]
Btw this has nothing to do with sleep tight. It's just the mod being broken
. Without it there's nothing to break so it loads
