### ISSUE TITLE
some error being thrown when loading world [1.16.5 - atm6 1.8.10]

### ISSUE THREAD

**Issue by Xplodin** [MehVahdJukaar/Supplementaries#145]
[23:49:24][Server thread][ERROR]: Throwing
 java.lang.Exception: something went wrong: found a null biome in the biome provider
        at net.mehvahdjukaar.supplementaries.world.structures.StructureRegistry.addDimensionalSpacing(StructureRegistry.java:142) ~[supplementaries:1.16.5-0.17.10]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:430) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:351) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:730) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]

Im unsure but I think this is whats making my world not load
Its a 14 GB world and used to work.

**Comment by MehVahdJukaar** [comment]
So I can tell you for sure that is not on my end. Basically I had this issue where when I was registering my structure it happened once that at that phase of registration there was a null biome in a list that wasn't supposed to be null. this broke alot of things and I since then added that check and it throws that warning instead skipping registration. It's not my mod that it's failing now but somebody else that is doing the same that as I am is probably crashing when it encounters that null biome. Now the culprit here is the mod that put that null biome there in the first place. last time it was a buggy BYG update. Try removing some of your world gen mods and see which one it is

**Comment by Xplodin** [comment]
oh dang. My world became corrupted somehow during a download/backup process. Ive never seen the error but im unsure what to do to fix it.
Nothing was added/changed except for machine and cpu type.

**Comment by MehVahdJukaar** [comment]
Hmm odd. Usually that would point toward something more systematic that would happen with any new world too. Not exactly sure though cause I never had to fix that issue since it wasn't on my mod. Does it indeed happen on that world only? Maybe it's some mod you updated

**Comment by meeprdib** [comment]
Mod versions on 1.19.2 and below are not supported
