### ISSUE TITLE
[1.16.5 0.17.10] Failed to save chunk

### ISSUE THREAD

**Issue by dayd21git** [MehVahdJukaar/Supplementaries#151]
An error occurs on the server side during the game.
Forge: 36.2.19
```
[18:59:09] [Server thread/ERROR] [net.minecraft.world.server.ChunkManager/]: Failed to save chunk [3, 0]
java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.mehvahdjukaar.supplementaries.block.tiles.StructureTempBlockTile cannot be cast to class net.minecraft.entity.Entity (net.mehvahdjukaar.supplementaries.block.tiles.StructureTempBlockTile and net.minecraft.entity.Entity are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @4005e485)
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_223155_b(ChunkManager.java:416) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219204_a(ChunkManager.java:394) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:388) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:489) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1093) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1006) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassCastException: class net.mehvahdjukaar.supplementaries.block.tiles.StructureTempBlockTile cannot be cast to class net.minecraft.entity.Entity (net.mehvahdjukaar.supplementaries.block.tiles.StructureTempBlockTile and net.minecraft.entity.Entity are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @4005e485)
	at net.minecraft.world.server.ServerWorld.redirect$zkk000$onEntityRemoved(ServerWorld.java:3431) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217466_a(ServerWorld.java:1139) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219185_a(ChunkManager.java:437) ~[?:?]
	... 12 more
```

**Comment by MehVahdJukaar** [comment]
Any more info on this? Could be some sort of incompatibility since I haven't changed that code in ages. Can you send me the full log and crash report?

**Comment by dayd21git** [comment]
Sry, my bad.
Log file: https://day-d.ru/logs/issues-151/latest01.log
Is the **hastebin** broken?

**Comment by MehVahdJukaar** [comment]
not sure what's causing this. does it happen with only the mod installed? Have you tried using the latest version?

**Comment by dayd21git** [comment]
I checked the changelog of version 1.17.11 and 1.17.12b. Having not seen the necessary fix in these versions, I did not even try to install them.
I'll try to test the new versions, okay.

**Comment by dayd21git** [comment]
Unfortunately the new version has the same error. I will try to install only your mod and conduct tests, but I do not promise that this will happen quickly.

**Comment by MehVahdJukaar** [comment]
so when exactly is that happening?

**Comment by dayd21git** [comment]
I installed only your mod and did not see such an error.
For what reason can there be an error in the mods pack and how to catch the culprit?

**Comment by MehVahdJukaar** [comment]
I'm not sure. Does it happen in every new world you create? Are you using any worldgen mod in particular? I can see that the error description is very weird indeed

**Comment by dayd21git** [comment]
Any world. I don't use generators.

**Comment by MehVahdJukaar** [comment]
Superflat too?

**Comment by dayd21git** [comment]
I thought of something else, I'll check it later.

**Comment by dayd21git** [comment]
I checked. This error also exists in the flat world. I only got to the first village and got the same error.

**Comment by dayd21git** [comment]
That's just this time many other mods took part in the mistakes.
https://pastebin.com/ShgseULd

Is this probably a server core problem?

**Comment by MehVahdJukaar** [comment]
So I can only say that this is a very weird problem. That class that it was referencing is used by a very simple block I have and it's literally used in only one place, when generating way signs and nowhere else. The fact that it happened in a superflat world where those dont spawn states that its not my block problem. Moreover the error itself is weird in itself cause it seems that there is someplace in code where it's trying to cast tile entities to the entity class, which are two completelly different thing so I have no idea how anybody could even write something like that cause the ide would warn about it. It's definitely a buggy mod  seeing that it can happen with other tile entities like the bed one in your latest report. Unfortunatelly I can't tell anything more since the report doesn't include any information that points to any mod, infact if I didn't know any better I would think this could be a vanilla minecraft problem. The only thing that I think could cause this is coremodding stuff like mixins, althought those are usually mentioned there too so I'm not sure. 
I would advise you to brute force this to find the culprit, to do so just disable half the mods you have and boot it up. If the error persists keep repeating the previous steps until it works

**Comment by dayd21git** [comment]
This approach will take a lot of time and will not guarantee that a bad mod will be found. However, thank you for your time!

**Comment by meeprdib** [comment]
Mod versions on 1.19.2 and below are not supported
