### ISSUE TITLE
Unknown items and skipped recipes

### ISSUE THREAD

**Issue by spiritedfang** [MehVahdJukaar/Supplementaries#164]
Hi there,

I saw these info messages and errors when running a 1.18.1 forge server (running 39.0.7 of forge). Are these expected? 

```
[20:40:24] [Worker-Main-4/INFO]: Skipping loading recipe supplementaries:inspirations/blackboard_clear as it's serializer returned null
[20:40:24] [Worker-Main-4/INFO]: Skipping loading recipe supplementaries:blackstone_tile_vertical_slab as it's serializer returned null
[20:40:24] [Worker-Main-4/INFO]: Skipping loading recipe supplementaries:inspirations/flag_dye as it's serializer returned null
[20:40:24] [Worker-Main-4/INFO]: Skipping loading recipe supplementaries:ash_bricks_vertical_slab as it's serializer returned null
[20:40:24] [Worker-Main-4/INFO]: Skipping loading recipe supplementaries:planter_rich_soul as it's serializer returned null
[20:40:24] [Worker-Main-4/INFO]: Skipping loading recipe supplementaries:checker_vertical_slab as it's serializer returned null
[20:40:24] [Worker-Main-4/INFO]: Skipping loading recipe supplementaries:gold_gate as it's serializer returned null
[20:40:24] [Worker-Main-4/INFO]: Skipping loading recipe supplementaries:inspirations/flag_clear as it's serializer returned null
[20:40:24] [Worker-Main-4/ERROR]: Parsing error loading recipe supplementaries:planter_rich
com.google.gson.JsonSyntaxException: Unknown item 'supplementaries:planter_rich'
        at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:170) ~[forge-1.18.1-39.0.7-universal.jar%2371!:?]
        at net.minecraft.world.item.crafting.ShapedRecipe.m_151274_(ShapedRecipe.java:270) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at net.minecraft.world.item.crafting.ShapedRecipe$Serializer.m_6729_(ShapedRecipe.java:294) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at net.minecraft.world.item.crafting.ShapedRecipe$Serializer.m_6729_(ShapedRecipe.java:285) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at net.minecraft.world.item.crafting.RecipeManager.m_44045_(RecipeManager.java:144) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at net.minecraftforge.common.crafting.ConditionalRecipe$Serializer.m_6729_(ConditionalRecipe.java:93) ~[forge-1.18.1-39.0.7-universal.jar%2371!:?]
        at net.minecraft.world.item.crafting.RecipeManager.m_44045_(RecipeManager.java:144) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:60) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:35) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:70) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:70) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:70) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance$1.m_10855_(SimpleReloadInstance.java:53) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance$1.m_6769_(SimpleReloadInstance.java:50) ~[server-1.18.1-20211210.034407-srg.jar%2367!:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[20:40:24] [Worker-Main-4/INFO]: Skipping loading recipe supplementaries:stone_tile_vertical_slab as it's serializer returned null
```

Thanks,
Spirited

**Comment by MehVahdJukaar** [comment]
yeah they are some of those remaining forge recipes that I haven't converted over yet. Yeah that's expected and they are supposed to return null since they are disabled but for some reason forge recipes spam the log while vanilla do not. it's annoying really but I'll switch all of them over so they dont spam

**Comment by MehVahdJukaar** [comment]
actually I stand corrected, those are compat recipes for modded stuff that can't be made with vanilla ones (otherwise they will spam like that last of those , which indeed has an error which I'll fix). those lines will have to stay, no clue why forge is even allowing logging for conditonal recipes being disablen when their whole porpouse is being disableable lol

**Comment by MehVahdJukaar** [comment]
so this should have been fixed

**Comment by spiritedfang** [comment]
Awesome, thanks!
