### ISSUE TITLE
DoubleSkullBlockTile cant be broken

### ISSUE THREAD

**Issue by UdoMorgenstern** [MehVahdJukaar/Supplementaries#177]
mc 1.18.1 
forge 39.0.10
supplementaries-1.18.1-1.1.5.jar

Steps to reproduce:
- place 2 sculls on top of each other
- break skulls

Outcome
- from the perspective of the player breaking the skull they seem to be gone
- placing a block in that place will show 2 skeleton skulls stack on top of each other
- restart of server / world will recover the original player heads

Expected:
- skulls / heads shall be breakable
- original player heads / skulls shall be recoverable

Server console log after breaking double skull/player head:
java.lang.ClassCastException: class net.mehvahdjukaar.supplementaries.common.block.tiles.DoubleSkullBlockTile cannot be cast to class net.minecraft.world.level.block.entity.SkullBlockEntity (net.mehvahdjukaar.supplementaries.common.block.tiles.DoubleSkullBlockTile is in module supplementaries@1.1.4 of loader 'TRANSFORMER' @1c067c0d; net.minecraft.world.level.block.entity.SkullBlockEntity is in module minecraft@1.18.1 of loader 'TRANSFORMER' @1c067c0d)
at com.natamus.justmobheads.events.HeadDropEvent.onPlayerHeadBreak(HeadDropEvent.java:151) ~[justmobheads_1.18.1-5.3.jar%2366!:1.0]
at net.minecraftforge.eventbus.ASMEventHandler_360_HeadDropEvent_onPlayerHeadBreak_BreakEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:532) ~[forge-1.18.1-39.0.9-universal.jar%23102!:?]
at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:227) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.server.level.ServerPlayerGameMode.m_9286_(ServerPlayerGameMode.java:217) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.server.level.ServerPlayerGameMode.m_7391_(ServerPlayerGameMode.java:187) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:945) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:34) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2398!:?]
at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by MehVahdJukaar** [comment]
might be an incompatibility with "justMobHeads" mod. I'll try to see if I can figure it out

**Comment by MehVahdJukaar** [comment]
actually this is totally his issue here, not mine. It's making unsafe cast right here 
https://github.com/ricksouth/serilum-mc-mods/blob/fe546505a92b7aabc566c4d3db3dee9c0008e46b/sources/Just%20Mob%20Heads/src/main/java/com/natamus/justmobheads/events/HeadDropEvent.java
at this line SkullBlockEntity sbe = (SkullBlockEntity)world.getBlockEntity(pos);
