### ISSUE TITLE
Compatibility with Jade

### ISSUE THREAD

**Issue by Dr-WeiAL** [MehVahdJukaar/Supplementaries#215]
Using Jade to view four layers of enchanted books placed by Supplementaries crashes the game
![image](https://user-images.githubusercontent.com/47446553/158827202-3b4882d7-60f3-4569-99d0-58b389206668.png)

```
Time: 2022/3/16 下午12:54
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?] {}
	at net.minecraft.core.NonNullList.get(NonNullList.java:47) ~[client-1.18.1-20211210.034407-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:radium.mixins.json:block.hopper.DefaultedListAccessor,pl:mixin:A}
	at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.m_8020_(RandomizableContainerBlockEntity.java:100) ~[client-1.18.1-20211210.034407-srg.jar%23209!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.mehvahdjukaar.supplementaries.common.block.blocks.BookPileBlock.getCloneItemStack(BookPileBlock.java:126) ~[supplementaries-1.18.1-1.2.3.jar%23197!/:1.18.1-1.2.2] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.getCloneItemStack(IForgeBlockState.java:218) ~[forge-1.18.1-39.1.2-universal.jar%23213!/:?] {re:computing_frames,re:mixin,re:classloading}
	at mcp.mobius.waila.impl.BlockAccessorImpl.getPickedResult(BlockAccessorImpl.java:75) ~[Jade-1.18.1-4.4.1.jar%23160!/:4.4.1] {re:classloading}
	at mcp.mobius.waila.impl.BlockAccessorImpl._getIcon(BlockAccessorImpl.java:87) ~[Jade-1.18.1-4.4.1.jar%23160!/:4.4.1] {re:classloading}
	at mcp.mobius.waila.overlay.RayTracing.getIcon(RayTracing.java:162) ~[Jade-1.18.1-4.4.1.jar%23160!/:4.4.1] {re:classloading}
	at mcp.mobius.waila.overlay.TooltipRenderer.<init>(TooltipRenderer.java:33) ~[Jade-1.18.1-4.4.1.jar%23160!/:4.4.1] {re:classloading}
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:127) ~[Jade-1.18.1-4.4.1.jar%23160!/:4.4.1] {re:classloading}
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:123) ~[Jade-1.18.1-4.4.1.jar%23160!/:4.4.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_549_WailaClient_onClientTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:868) ~[forge-1.18.1-39.1.2-universal.jar%23213!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1734) ~[client-1.18.1-20211210.034407-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:inventorio.mixins.json:client.accessor.MinecraftClientAccessor,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:inventorio.mixins.json:client.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1016) ~[client-1.18.1-20211210.034407-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:inventorio.mixins.json:client.accessor.MinecraftClientAccessor,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:inventorio.mixins.json:client.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.18.1-20211210.034407-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:inventorio.mixins.json:client.accessor.MinecraftClientAccessor,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:inventorio.mixins.json:client.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23209!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.2.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?] {}
	at net.minecraft.core.NonNullList.get(NonNullList.java:47) ~[client-1.18.1-20211210.034407-srg.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:radium.mixins.json:block.hopper.DefaultedListAccessor,pl:mixin:A}
	at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.m_8020_(RandomizableContainerBlockEntity.java:100) ~[client-1.18.1-20211210.034407-srg.jar%23209!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.mehvahdjukaar.supplementaries.common.block.blocks.BookPileBlock.getCloneItemStack(BookPileBlock.java:126) ~[supplementaries-1.18.1-1.2.3.jar%23197!/:1.18.1-1.2.2] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.getCloneItemStack(IForgeBlockState.java:218) ~[forge-1.18.1-39.1.2-universal.jar%23213!/:?] {re:computing_frames,re:mixin,re:classloading}
	at mcp.mobius.waila.impl.BlockAccessorImpl.getPickedResult(BlockAccessorImpl.java:75) ~[Jade-1.18.1-4.4.1.jar%23160!/:4.4.1] {re:classloading}
	at mcp.mobius.waila.impl.BlockAccessorImpl._getIcon(BlockAccessorImpl.java:87) ~[Jade-1.18.1-4.4.1.jar%23160!/:4.4.1] {re:classloading}
	at mcp.mobius.waila.overlay.RayTracing.getIcon(RayTracing.java:162) ~[Jade-1.18.1-4.4.1.jar%23160!/:4.4.1] {re:classloading}
	at mcp.mobius.waila.overlay.TooltipRenderer.<init>(TooltipRenderer.java:33) ~[Jade-1.18.1-4.4.1.jar%23160!/:4.4.1] {re:classloading}
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:127) ~[Jade-1.18.1-4.4.1.jar%23160!/:4.4.1] {re:classloading}
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:123) ~[Jade-1.18.1-4.4.1.jar%23160!/:4.4.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_549_WailaClient_onClientTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:868) ~[forge-1.18.1-39.1.2-universal.jar%23213!/:?] {re:mixin,re:classloading}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['WeiAL'/1, l='ClientLevel', x=2.50, y=-60.00, z=-0.50]]
	Chunk stats: 5041, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 299 game time, 299 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:517) ~[client-1.18.1-20211210.034407-srg.jar%23209!/:?] {re:mixin,xf:OptiFine:default,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,re:classloading,xf:OptiFine:default,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:krypton.mixins.json:client.fastchunkentityaccess.ClientWorldMixin,pl:mixin:APP:radium.mixins.json:chunk.entity_class_groups.ClientWorldMixin,pl:mixin:APP:terrablender.mixins.json:client.MixinClientLevel,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2249) ~[client-1.18.1-20211210.034407-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:inventorio.mixins.json:client.accessor.MinecraftClientAccessor,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:inventorio.mixins.json:client.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:683) ~[client-1.18.1-20211210.034407-srg.jar%23209!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:inventorio.mixins.json:client.accessor.MinecraftClientAccessor,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:inventorio.mixins.json:client.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23209!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.2.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
```

**Comment by danflech** [comment]
I got a similar issue, but I also had mods that add custom enchants and I wasn't entirely certain if those were part of the crash as well. Were all of the books you looked at vanilla enchants?

**Comment by Dr-WeiAL** [comment]
It's not a matter of enchantment properties, vanilla enchantments can also cause crashes

**Comment by danflech** [comment]
Also - tried turning off placeable books in the config for my world and server to prevent it from happening by accident, but I was still able to place the books! Hopefully this gets patched soon.

**Comment by JDLENL** [comment]
i placed three books and had no problem, but as soon as i placed a fourth book, my game crashed. i had to disable jade to break the stack.
