### ISSUE TITLE
1.19 ResourcePack Incompat Crash

### ISSUE THREAD

**Issue by Speiger** [MehVahdJukaar/Supplementaries#260]
o/ Found that supplementaries ships a invalid ResourcePack that causes it to crash.

```
Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: supplementaries:textures/blocks/end_lamps/end_stone_lamp_ඞ.png
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:classloading,re:mixin}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:classloading,re:mixin}
	at net.minecraftforge.resource.PathResourcePack.lambda$getResources$1(PathResourcePack.java:116) ~[forge-1.19-41.0.62-universal.jar%23159!/:?] {re:classloading}
```

The piece of code that causes the crash:
```java
for(Map.Entry<ResourceLocation, Resource> entry : manager.listResources("textures", T -> T.getPath().endsWith("texture_package.json")).entrySet())
{
}
```

How to fix:
- 1: Delete the problem file.
- 2: Rename the file to a ResourcePack Friendly name

Thank you for reading.
Speiger

**Comment by MehVahdJukaar** [comment]
that's weird. I had that thing there for ages. It's unused and never gave problems. This doesnt happen to me of course so I wonder what mod is loading that texture

**Comment by Speiger** [comment]
@MehVahdJukaar Mojang Very Recently switched its listResources from Strings to resourcelocations. Also mods that scim through folders (like textures) are very rare but they do exist.

**Comment by MehVahdJukaar** [comment]
Oh I see. Well this means no more random unused crap in the pack folder
