### ISSUE TITLE
crashed setup event

### ISSUE THREAD

**Issue by holyaurora21** [MehVahdJukaar/Supplementaries#287]
encountered an error during the sided_setup event phase

supplementaries-1.18.1-1.2.5.jar

1.18.1

forge: 39.1.0

---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/31/22, 2:01 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.1-39.1.0-universal.jar%23119!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:169) ~[forge-1.18.1-39.1.0-universal.jar%23119!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:554) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:409) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:548) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:875) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1041) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.0.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
-- MOD supplementaries --
Details:
	Mod File: supplementaries-1.18.1-1.2.5.jar
	Failure message: Supplementaries (supplementaries) encountered an error during the sided_setup event phase
		java.util.ConcurrentModificationException: null
	Mod Version: 1.2.5
	Mod Issue URL: https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues
	Exception message: java.util.ConcurrentModificationException
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
	at net.minecraft.client.renderer.item.ItemProperties.register(ItemProperties.java:60) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.mehvahdjukaar.supplementaries.setup.ClientSetup.init(ClientSetup.java:155) ~[supplementaries-1.18.1-1.2.5.jar%23112!/:1.18.1-1.2.5] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_333_ClientSetup_init_FMLClientSetupEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.1.0.jar%23117!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.1.0.jar%23116!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3984586752 bytes (3799 MiB) / 7893680128 bytes (7528 MiB) up to 11408506880 bytes (10880 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1640
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 31599.24
	Virtual memory used (MB): 20308.16
	Swap memory total (MB): 15360.00
	Swap memory used (MB): 493.11
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10880m -Xms256m
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.6.0
	Mod List: 
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |ENQUEUE_IM|Manifest: NOSIGNATURE
		clienttweaks-forge-1.18.1-7.1.0.jar               |Client Tweaks                 |clienttweaks                  |7.1.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.6-forge-mc1.18.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6               |ENQUEUE_IM|Manifest: NOSIGNATURE
		rechiseled-1.0.10a-mc1.18.jar                     |rechiseled                    |rechiseled                    |1.0.10a             |ENQUEUE_IM|Manifest: NOSIGNATURE
		Connectible Chains-forge-1.18.1-2.0.1.jar         |Connectible Chains            |connectiblechains             |2.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		jei-1.18.1-9.4.1.172.jar                          |Just Enough Items             |jei                           |9.4.1.172           |ENQUEUE_IM|Manifest: NOSIGNATURE
		Architects-Palette-1.18.1-1.2.0.jar               |Architect's Palette           |architects_palette            |1.1.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-windows-2.0.3-mc1.18.1.jar                    |Macaw's Windows               |mcwwindows                    |2.0.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		kleeslabs-forge-1.18.1-11.1.0.jar                 |KleeSlabs                     |kleeslabs                     |11.1.0              |ENQUEUE_IM|Manifest: NOSIGNATURE
		BuildersDelight-Forge.1.18.1.jar                  |Builder's Delight             |buildersdelight               |0.9                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-paintings-1.0.3-mc1.18.1.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Clumps-forge-1.18.1-8.0.0+5.jar                   |Clumps                        |clumps                        |8.0.0+5             |ENQUEUE_IM|Manifest: NOSIGNATURE
		CTM-1.18-1.1.3+1.jar                              |ConnectedTexturesMod          |ctm                           |1.18-1.1.3+1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.18.1-11.1.0.jar      |CookingForBlockheads          |cookingforblockheads          |11.1.0              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Controlling-forge-1.18.1-9.0+15.jar               |Controlling                   |controlling                   |9.0+15              |ENQUEUE_IM|Manifest: NOSIGNATURE
		1.18.1-additionalbars-2.3.0.jar                   |Additional Bars               |additionalbars                |2.3.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		configured-1.5.3-1.18.1.jar                       |Configured                    |configured                    |1.5.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		alcocraft-1.0.0.jar                               |Alcocraft: Beer & Stuff       |alcocraft                     |1.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Decorative Blocks-forge-1.18.1-2.0.4.jar          |Decorative Blocks             |decorative_blocks             |2.0.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		macawsbridgesbop-1.18.1-1.0.jar                   |Macaw's Bridges - Biomes O' Pl|macawsbridgesbop              |1.18.1-1.0          |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-doors-1.0.6-mc1.18.1.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.6               |ENQUEUE_IM|Manifest: NOSIGNATURE
		balm-2.4.3+0.jar                                  |Balm                          |balm                          |2.4.3+0             |ENQUEUE_IM|Manifest: NOSIGNATURE
		JEITweaker-1.18.1-3.0.0.5.jar                     |JEI Tweaker                   |jeitweaker                    |3.0.0.5             |ENQUEUE_IM|Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.1-9.0.81.jar              |CraftTweaker                  |crafttweaker                  |9.0.81              |ENQUEUE_IM|Manifest: NOSIGNATURE
		macawsroofsbop-1.18.1-1.1.jar                     |Macaw's Roofs - Biomes O' Plen|macawsroofsbop                |1.18.1-1.1          |ENQUEUE_IM|Manifest: NOSIGNATURE
		cloth-config-6.2.62-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.2.62              |ENQUEUE_IM|Manifest: NOSIGNATURE
		ilikewoodxbiomesoplenty-1.18.1-7.4.0.jar          |I Like Wood - Biomes o' Plenty|ilikewoodxbiomesoplenty       |1.18.1-7.4.0        |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-paths-1.0.0-mc1.18.1.jar                      |Macaw's Paths and Pavings     |mcwpaths                      |1.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		selene-1.18-1.13.2.jar                            |Selene                        |selene                        |1.18-1.13.2         |ENQUEUE_IM|Manifest: NOSIGNATURE
		supplementaries-1.18.1-1.2.5.jar                  |Supplementaries               |supplementaries               |1.2.5               |ERROR     |Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.3-mc1.18.1.jar                    |Macaw's Bridges               |mcwbridges                    |2.0.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		FarmersDelight-1.18.1-1.0.4.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.4        |ENQUEUE_IM|Manifest: NOSIGNATURE
		DustrialDecor-1.3.2-1.18.jar                      |'Dustrial Decor               |dustrial_decor                |1.3.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.1-1.1.0.77.jar            |TerraBlender                  |terrablender                  |1.18.1-1.1.0.77     |ENQUEUE_IM|Manifest: NOSIGNATURE
		Decorative Blocks Compat-forge-1.18.1-2.0.0.jar   |Decorative Compat             |decorative_compat             |2.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |ENQUEUE_IM|Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.1-15.0.0.104-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.1-15.0.0.104   |ENQUEUE_IM|Manifest: NOSIGNATURE
		Jade-1.18.1-4.4.1.jar                             |Jade                          |jade                          |4.4.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.18.1-39.1.0-universal.jar                 |Forge                         |forge                         |39.1.0              |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		CreativeCore_v2.5.0_mc1.18.1.jar                  |CreativeCore                  |creativecore                  |2.5.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.6-mc1.18.1.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.6               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-fences-1.0.5-mc1.18.1.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.5               |ENQUEUE_IM|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19-forge-mc1.18.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |ENQUEUE_IM|Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Quark-3.1-340.jar                                 |Quark                         |quark                         |3.1-340             |ENQUEUE_IM|Manifest: NOSIGNATURE
		FramedBlocks-4.4.0.jar                            |FramedBlocks                  |framedblocks                  |4.4.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		entityculling-forge-mc1.18-1.5.1.jar              |EntityCulling                 |entityculling                 |1.5.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.18-1.6.0.jar            |Better Third Person           |betterthirdperson             |1.6.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		buildersaddition-1.18.1-20220123a.jar             |Builders Crafts & Addition    |buildersaddition              |1.18.1-20220123a    |ENQUEUE_IM|Manifest: NOSIGNATURE
		just_enough_keg-1.18.1-3.0.1.jar                  |Just Enough Keg               |just_enough_keg               |3.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Blocks + 1.18.1 - 1.4.jar                         |Blocks +                      |blocksplus                    |1.4                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		worldedit-mod-7.2.9.jar                           |WorldEdit                     |worldedit                     |7.2.9+e20e013       |ENQUEUE_IM|Manifest: NOSIGNATURE
		constructionwand-1.18.1-2.7.jar                   |Construction Wand             |constructionwand              |1.18.1-2.7          |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-roofs-2.1.2-mc1.18.1.jar                      |Macaw's Roofs                 |mcwroofs                      |2.1.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		architectury-3.9.66.jar                           |Architectury                  |architectury                  |3.9.66              |ENQUEUE_IM|Manifest: NOSIGNATURE
		connectedglass-1.1.4-forge-mc1.18.jar             |Connected Glass               |connectedglass                |1.1.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-furniture-3.0.1-mc1.18.1.jar                  |Macaw's Furniture             |mcwfurnitures                 |3.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Adorn-3.3.1+1.18.1-forge.jar                      |Adorn                         |adorn                         |3.3.1+1.18.1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		ilikewood-1.18.1-7.4.4.0.jar                      |I Like Wood                   |ilikewood                     |1.18.1-7.4.4.0      |ENQUEUE_IM|Manifest: NOSIGNATURE
		JadeAddons-1.18.1-1.0.1.jar                       |Jade Addons                   |jadeaddons                    |1.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		ChiselsBits-forge-1.18.1-1.2.82-universal.jar     |Chisels & bits                |chiselsandbits                |1.2.82              |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-lights-1.0.3-mc1.18.1.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		drinkbeer-v2.3.5 for 1.18.1.jar                   |Drink Beer                    |drinkbeer                     |2.3.5               |ENQUEUE_IM|Manifest: NOSIGNATURE
	Crash Report UUID: 94dbafdc-86d9-4d8e-bedb-d70abffc450d
	FML: 39.1
	Forge: net.minecraftforge:39.1.0
	FramedBlocks BlockEntity Warning: Not applicable

**Comment by meeprdib** [comment]
Mod versions on 1.19.2 and below are not supported
