### ISSUE TITLE
Crashes before reaching title menu

### ISSUE THREAD

**Issue by ajaelle12** [MehVahdJukaar/Supplementaries#294]
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/mehvahdjukaar/moonlight/api/block/IBlockHolder
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/mehvahdjukaar/moonlight/api/block/IBlockHolder
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.block.Blocks.<clinit>(Blocks:236)
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig:9)
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig:20)
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig:16)
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver:32)
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers:21)
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries:66)
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98)
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104)
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326)
	at net.minecraft.Bootstrap.initialize(Bootstrap:50)
	at net.minecraft.client.main.Main.main(Main:154)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: java.lang.ClassNotFoundException: net.mehvahdjukaar.moonlight.api.block.IBlockHolder
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 26 more

**Comment by MehVahdJukaar** [comment]
You dont have Moonlight lib installed
