### ISSUE TITLE
Fix mixin and other related issues

### ISSUE THREAD

**Issue by FrannDzs** [MehVahdJukaar/Supplementaries#3]
When i install supplementaries i get several errors. You can see more information about the errors thanks to Blame.

**To Reproduce**
1. Install Minecraft 1.16.4	
2. Install Forge 35.1.36
3. Install Supplementaries

**Expected behavior**
Fix mixin problems and other related issues

** Mod version **
Forge 35.1.36

** Logs **
Latest/Crash log
[10ene2021 17:34:05.941] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, FrannDzs, --version, HMCL 3.3.179, --gameDir, C:\Users\Franco\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Franco\AppData\Roaming\.minecraft\assets, --assetIndex, 1.16, --uuid, 72a6a693156b4d46861862888ce18584, --accessToken, ????????, --userType, mojang, --versionType, HMCL 3.3.179, --width, 854, --height, 480, --launchTarget, fmlclient, --fml.forgeVersion, 35.1.36, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201102.104115]
[10ene2021 17:34:06.051] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.6+85+master.325de55 starting: java version 1.8.0_272 by GraalVM Community
[10ene2021 17:34:09.748] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[10ene2021 17:34:10.221] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Franco/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[10ene2021 17:34:23.513] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, HMCL 3.3.179, --gameDir, C:\Users\Franco\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Franco\AppData\Roaming\.minecraft\assets, --uuid, 72a6a693156b4d46861862888ce18584, --username, FrannDzs, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, HMCL 3.3.179, --width, 854, --height, 480]
[10ene2021 17:34:46.410] [pool-3-thread-1/WARN] [mixin/]: @Final field field_76203_h:Ljava/util/Map; in supplementaries.mixins.json:MapMixin should be final
[10ene2021 17:34:55.532] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://littleskin.cn/api/yggdrasil/authserver', accountsHost='http://127.0.0.1:13117/https/api.mojang.com', sessionHost='http://127.0.0.1:13117/https/sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10ene2021 17:34:57.259] [Render thread/ERROR] [net.minecraft.client.Minecraft/]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationException: Unauthorized
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:119) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:94) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at net.minecraft.client.Minecraft.func_244735_a(Minecraft.java:551) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:383) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.36.jar:35.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
[10ene2021 17:34:57.344] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: FrannDzs
[10ene2021 17:34:58.890] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[10ene2021 17:35:02.193] [modloading-worker-1/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 35.1.36, for MC 1.16.4 with MCP 20201102.104115
[10ene2021 17:35:02.195] [modloading-worker-1/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v35.1.36 Initialized
[10ene2021 17:35:02.292] [modloading-worker-0/ERROR] [com.telepathicgrunt.blame.Blame/]: Blame 1.8.1 initialized
[10ene2021 17:35:03.166] [modloading-worker-0/ERROR] [net.minecraft.util.Util/]: No data fixer registered for firefly
[10ene2021 17:35:06.123] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:<init>:52]: Log Path: C:\Users\Franco\AppData\Roaming\.minecraft\CustomSkinLoader\CustomSkinLoader.log
[10ene2021 17:35:06.128] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] CustomSkinLoader 14.13-SNAPSHOT-199
[10ene2021 17:35:06.146] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] DataDir: C:\Users\Franco\AppData\Roaming\.minecraft\CustomSkinLoader
[10ene2021 17:35:06.147] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Operating System: Windows 10 (amd64) version 10.0
[10ene2021 17:35:06.150] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Java Version: 1.8.0_272, GraalVM Community
[10ene2021 17:35:06.170] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Java VM Version: OpenJDK 64-Bit Server VM GraalVM CE 21.1.0-dev (mixed mode), GraalVM Community
[10ene2021 17:35:06.237] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Minecraft: 1.16.4(1.16.4)
[10ene2021 17:35:06.337] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Config File: C:\Users\Franco\AppData\Roaming\.minecraft\CustomSkinLoader\CustomSkinLoader.json
[10ene2021 17:35:06.340] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Try to load config.
[10ene2021 17:35:06.395] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] Successfully load config.
[10ene2021 17:35:06.650] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] version : 14.13
[10ene2021 17:35:06.651] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] enableDynamicSkull : true
[10ene2021 17:35:06.652] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] enableTransparentSkin : true
[10ene2021 17:35:06.654] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] forceIgnoreHttpsCertificate : false
[10ene2021 17:35:06.654] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] forceLoadAllTextures : false
[10ene2021 17:35:06.658] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] enableCape : true
[10ene2021 17:35:06.660] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] threadPoolSize : 3
[10ene2021 17:35:06.662] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] retryTime : 1
[10ene2021 17:35:06.663] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] cacheExpiry : 30
[10ene2021 17:35:06.674] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] forceUpdateSkull : false
[10ene2021 17:35:06.675] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] enableLocalProfileCache : false
[10ene2021 17:35:06.838] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] enableCacheAutoClean : false
[10ene2021 17:35:06.841] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] forceDisableCache : false
[10ene2021 17:35:06.882] [Render thread/INFO] [STDOUT/]: [customskinloader.Logger:log:72]: [Render thread INFO] loadList : 7
[10ene2021 17:35:10.347] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[10ene2021 17:35:10.669] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources
[10ene2021 17:35:11.276] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[10ene2021 17:35:11.399] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:mushroom_stew
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.DefaultDispenseItemBehavior
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.426] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:water_bucket
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.IDispenseItemBehavior$16
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.426] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:lava_bucket
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.IDispenseItemBehavior$16
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.427] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:milk_bucket
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.DefaultDispenseItemBehavior
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.427] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:pufferfish_bucket
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.IDispenseItemBehavior$16
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.428] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:salmon_bucket
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.IDispenseItemBehavior$16
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.428] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:cod_bucket
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.IDispenseItemBehavior$16
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.583] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:tropical_fish_bucket
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.IDispenseItemBehavior$16
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.586] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:cookie
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.DefaultDispenseItemBehavior
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.589] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:potion
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.DefaultDispenseItemBehavior
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.592] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:experience_bottle
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.IDispenseItemBehavior$6
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.600] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:rabbit_stew
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.DefaultDispenseItemBehavior
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.601] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:beetroot_soup
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.DefaultDispenseItemBehavior
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.604] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:dragon_breath
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.DefaultDispenseItemBehavior
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.643] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:splash_potion
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.IDispenseItemBehavior$7
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.654] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:lingering_potion
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.IDispenseItemBehavior$8
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.657] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:suspicious_stew
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.DefaultDispenseItemBehavior
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.660] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:honey_bottle
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$FillJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.DefaultDispenseItemBehavior
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:53)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.666] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:bucket
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$BucketJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.IDispenseItemBehavior$17
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:56)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.672] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:bowl
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$BowlJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.DefaultDispenseItemBehavior
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:57)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:11.676] [Worker-Main-2/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Extra Info Report 1.8.1 ******************
   Ignore this unless item behavior aren't working with Dispensers. If Dispenser behavior
   is broken, check out "Potentially Dangerous alternative prefix `minecraft`" lines for
   the item too as registry replacements might break dispenser behaviors as well.
  Dispenser Behavior overridden for minecraft:glass_bottle
  New behavior: net.mehvahdjukaar.supplementaries.setup.Dispenser$BottleJarDispenserBehavior
  Old behavior: net.minecraft.dispenser.IDispenseItemBehavior$24
  Registration done at: 
    net.mehvahdjukaar.supplementaries.setup.Dispenser.registerBehaviors(Dispenser.java:58)
    net.mehvahdjukaar.supplementaries.setup.ModSetup.init(ModSetup.java:24)
    net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)

[10ene2021 17:35:13.257] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: AHEAD Current: 35.1.36 Target: null
[10ene2021 17:35:40.117] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[10ene2021 17:35:40.123] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[10ene2021 17:35:41.520] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[10ene2021 17:35:41.687] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[10ene2021 17:35:41.703] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[10ene2021 17:35:41.747] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[10ene2021 17:35:41.753] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[10ene2021 17:35:41.760] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[10ene2021 17:35:41.766] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[10ene2021 17:35:46.164] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[10ene2021 17:35:46.232] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[10ene2021 17:35:46.237] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[10ene2021 17:35:47.298] [Realms Notification Availability checker #1/INFO] [com.mojang.realmsclient.client.RealmsClient/]: Could not authorize you against Realms server: Invalid session id
[10ene2021 17:36:46.894] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!

**Comment by MehVahdJukaar** [comment]
I'll reply here too just in case some other people have the same questions.
In short they are just warning and none of those are of any concert. It's basically complaining that overriding dispensers behaviors like that could break some modded ones but I haven't seen other mods do it in a different way and it's already implemented in a pretty compatible way. Other one is just a warning that for some reason I can't get rid but it's nothing to be worried about.
