### ISSUE TITLE
Crash with Flax Seeds

### ISSUE THREAD

**Issue by SwollNoodle** [MehVahdJukaar/Supplementaries#300]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 8/10/22, 9:42 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property class_2754{name=half, clazz=class net.minecraft.class_2756, values=[upper, lower]} as it does not exist in Block{minecraft:grass}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.mehvahdjukaar.supplementaries.common.block.blocks.FlaxBlock.method_9558(FlaxBlock.java:87)
	at net.minecraft.class_1542.handler$hge00d$tick(class_1542.java:3589)
	at net.minecraft.class_1542.method_5773(class_1542.java:105)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1813)
	at net.minecraft.class_310.method_1523(class_310.java:1101)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.mehvahdjukaar.supplementaries.common.block.blocks.FlaxBlock.method_9558(FlaxBlock.java:87)
	at net.minecraft.class_1542.handler$hge00d$tick(class_1542.java:3589)
	at net.minecraft.class_1542.method_5773(class_1542.java:105)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)

-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 2244
	Entity Name: Flax Seeds
	Entity's Exact location: 7.79, 66.00, 12.23
	Entity's Block location: World: (7,66,12), Section: (at 7,2,12 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.04, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1813)
	at net.minecraft.class_310.method_1523(class_310.java:1101)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['x'/211, l='ClientLevel', x=2.72, y=67.00, z=9.70]]
	Chunk stats: 4096, 901
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,63,0), Section: (at 0,15,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1112 game time, 1112 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, EclecticTrove-1.19-1.1.0.zip, Supplementaries Generated Pack

**Comment by MehVahdJukaar** [comment]
Can you give me more details? When did that happen?

**Comment by SwollNoodle** [comment]
It occurs when tossing flax from an inventory onto the ground, works fine if the mod is by itself but when with others (I still have to pinpoint which mod, no time yet) breaks. Think it might be due to a performance mod? I'll attach the full crash log below
[crash-2022-08-11_17.51.12-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9312533/crash-2022-08-11_17.51.12-server.txt)
:

**Comment by Nieeeb** [comment]
I also gets this issue. Sometimes server crashes, sometimes my client crashes.

Happens if a flax seed item is dropped on the ground

Tried disabling and enabling a bunch of different mods. It consistently seems to fail at the "Cannot get property class_2754{name=half, clazz=class net.minecraft.class_2756, values=[upper, lower]}" part. Sometimes what it checks in (in this case "Block{minecraft:air"}) differs.

[crash-2023-04-06_15.50.15-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11171256/crash-2023-04-06_15.50.15-client.txt)

**Comment by MehVahdJukaar** [comment]
Do you have vanilla tweaks? If so it's their issue

**Comment by meeprdib** [comment]
Mod versions on 1.19.2 and below are not supported
