### ISSUE TITLE
1.19 fabric launch crash

### ISSUE THREAD

**Issue by WANGCHIENCHIH** [MehVahdJukaar/Supplementaries#304]
crash report said 
Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Moonlight (moonlight), Supplementaries (supplementaries), Not Enough Crashes (notenoughcrashes)

but  after i ban Supplementaries  mod ,minecraft can work and load into  world
=================

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 8/11/22, 6:42 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'moonlight'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$eck000$catchFabricInit(class_310.java:20871)
	at net.minecraft.class_310.<init>(class_310.java:443)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.UnsupportedOperationException
	at net.mehvahdjukaar.supplementaries.integration.fabric.CCCompatImpl.makeSpeaker(CCCompatImpl.java:18)
	at net.mehvahdjukaar.supplementaries.integration.CCCompat.makeSpeaker(CCCompat.java)
	at net.mehvahdjukaar.supplementaries.reg.ModRegistry.lambda$static$118(ModRegistry.java:753)
	at net.mehvahdjukaar.moonlight.api.platform.fabric.RegistryQueue$EntryWrapper.initialize(RegistryQueue.java:67)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.mehvahdjukaar.moonlight.api.platform.fabric.RegistryQueue.initializeEntries(RegistryQueue.java:34)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
	at net.mehvahdjukaar.moonlight.api.platform.fabric.RegHelperImpl.registerEntries(RegHelperImpl.java:54)
	at net.mehvahdjukaar.moonlight.fabric.MoonlightFabric.commonSetup(MoonlightFabric.java:35)
	at net.mehvahdjukaar.moonlight.fabric.MoonlightFabricClient.onInitializeClient(MoonlightFabricClient.java:12)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 9 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)

-- Initialization --
Details:
Stacktrace:
	at fudge.notenoughcrashes.mixinhandlers.EntryPointCatcher.handleEntryPointError(EntryPointCatcher.java:28)
	at net.minecraft.class_310.redirect$eck000$catchFabricInit(class_310.java:20873)
	at net.minecraft.class_310.<init>(class_310.java:443)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.4, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 238185984 bytes (227 MiB) / 1010827264 bytes (964 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: unknown
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c8d
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Graphics card #1 name: Intel(R) HD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x591b
	Graphics card #1 versionInfo: DriverVersion=30.0.101.1994
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 35595.60
	Virtual memory used (MB): 12850.21
	Swap memory total (MB): 19328.00
	Swap memory used (MB): 172.07
	JVM Flags: 14 total; -Xmn512m -Xmx5120m -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+UseNUMA -XX:MaxGCPauseMillis=50 -XX:-UseGCOverheadLimit -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:UseSSE=3 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		additionalstructures: Additional Structures 4.0.0
		advdebug: Advancements Debug 2.3.0
		alternate-current: Alternate Current 1.4.0
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19
		architects_palette: Architect's Palette Fabric 2.1.1
		architectury: Architectury 5.11.40
		attributefix: AttributeFix 15.1.3
		awesomedungeon: Awesome Dungeon 2.0.11
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.3
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.8
		axolotlitemfix: Axolotl Item Fix 1.1.3
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 4.5.2+0
		bclib: BCLib 2.0.20
		betterend: Better End 2.0.11
		betterf3: BetterF3 1.3.2
		betternether: Better Nether 7.0.9
		bookshelf: Bookshelf 14.2.10
		byg: Oh The Biomes You'll Go 2.0.0.7
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.3.0
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		cave_enhancements: Cave Enhancements 1.19-FABRIC-1.3.3
		charmofundying: Charm of Undying 6.0.0+1.19.2
		citresewn: CIT Resewn 1.1.1+1.19
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.19
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.0.75
		clumps: Clumps 9.0.0+7
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		computercraft: CC: Restitched 1.101.0
			io_netty_netty-codec-http: netty-codec-http 4.1.77.Final
			org_squiddev_cobalt: Cobalt 0.5.5
		continuity: Continuity 2.0.1+1.19
		controlling: Controlling For Fabric 10.0+3
		craftingtweaks: Crafting Tweaks 15.1.0
		cullleaves: Cull Leaves 2.3.4
		darkpaintings: DarkPaintings 11.1.3
		dawn: Dawn API 3.5.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		dungeons_arise: When Dungeons Arise 2.1.51
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		ecologics: Ecologics 2.1.7
		edenring: EdenRing 0.6.3
		enchdesc: EnchantmentDescriptions 11.1.9
		enhancedcelestials: Enhanced Celestials 2.1.0.0
		entity_texture_features: Entity Texture Features 4.0.1
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		environmentz: EnvironmentZ 1.2.3
		expandeddelight: Expanded Delight 0.2.1
		experiencebugfix: Experience Bug Fix 18
		fabric: Fabric API 0.58.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.9
		farmersdelight: Farmer's Delight 1.19-0.3.0
		farmersknives: Farmer's Knives 2.0
		fastchest: FastChest 1.3+1.19
		ferritecore: FerriteCore 4.2.1
		friendsandfoes: Friends&Foes 1.5.5
			mm: Manningham Mills 2.3
		fwaystones: Fabric Waystones 3.0.2+mc1.19
		geckolib3: Geckolib 3.1.6
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		guardvillagers: Guard Villagers Fabric 1.19-1.0.16
		huskdropsand: Husks Drop Sand 1.19-5
		incendium: Incendium 5.1.2
		indium: Indium 1.0.7+mc1.19
		inventoryprofilesnext: Inventory Profiles Next 1.6.3
		iris: Iris 1.2.6
			org_anarres_jcpp: jcpp 1.4.14
		ironchests: Iron Chests 1.7.5
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		kubejs: KubeJS 1900.5.5-build.27
		kubejs_ui: KubeJS UI 1900.1.8-build.20
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazy-language-loader: lazy-language-loader 0.3.1
		lazydfu: LazyDFU 0.1.3
		lcsl: Lightly Colored Sea Lanterns 1.1.0
		libraryferret: Library Ferret 2.0.0
		lightoverlay: Light Overlay 7.0.0
		litematica: Litematica 0.12.0
		lithium: Lithium 0.8.1
		macawsbridgesbyg: Macaw's Bridges - BYG 1.19-1.0
		malilib: MaLiLib 0.13.0
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.6
		mcwlights: Macaw's Lights and Lamps 1.0.4
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwroofs: Macaw's Roofs 2.1.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.7
		mcwwindows: Macaw's Windows 2.0.3
		megane: megane 8.2.0
			megane-api: megane-api 8.2.0
			megane-fabric-transfer: megane-fabric-transfer 8.2.0
			megane-runtime: megane-runtime 8.2.0
			megane-vanilla: megane-vanilla 8.2.0
		memoryleakfix: memory Leak Fix 1.19-0.7.0
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		minieffects: Mini Effects 5.0.0
		mining_dims: Mining Dimensions 1.4.20
			customportalapi: Custom Portal Api 0.0.1-beta51-1.19
			pugh_lib: Pugh Lib 1.4.11
		modmenu: Mod Menu 4.0.4
		moonlight: Moonlight 1.19-2.0.15
		moreculling: More Culling 1.19.1-0.9.1
			conditional-mixin: conditional mixin 0.3.0
		moretags: More Tags 3.0.7
		morevillagers: More Villagers 4.0.2
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		neat: Neat 1.19-32-FABRIC
		nochatreports: No Chat Reports 1.19-v1.2.3
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		openloader: OpenLoader 13.1.2
		patchouli: Patchouli 1.19-74-FABRIC
		polymorph: Polymorph 0.45.0+1.19.1
		probejs: ProbeJS 3.0.5
		promenade: Promenade 2.7.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 4.0.0
		reeses-sodium-options: Reese's Sodium Options 1.4.5+mc1.19.2-build.51
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		respawningshulkers-fabric: Respawning Shulkers (Fabric) 1.8
		rhino: Rhino 1802.1.14-build.209
		riverredux: River Redux 0.3.0
		roughlyenoughitems: Roughly Enough Items 9.1.526
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		rpmtw_platform_mod: RPMTW Platform Mod 1.4.3
		satin: Satin 1.9.0
		smoke_suppression: Smoke Suppression 1.0.13
			crowdin-translate: CrowdinTranslate 1.4+1.19
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.6+mc1.19-build.47
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		spidersproducewebs-fabric: Spiders Produce Webs (Fabric) 1.7
		starlight: Starlight 1.1.1+fabric.ae22326
		stoneholm: Stoneholm 1.4.4
		supplementaries: Supplementaries 1.19-2.0.13
		t_and_t: Towns and Towers - Structure Add-on 1.8
		terrablender: TerraBlender 2.0.0.120
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		terralith: Terralith 2.3
		the_bumblezone: The Bumblezone - Fabric 6.1.4+1.19
			com_github_llamalad7_mixinextras: MixinExtras 0.0.11
			fake-player-api: Fake Player API 0.4.0
		tiefix: TieFix 1.11.0
		tooltipfix: ToolTip Fix 1.0.5-1.19
		totw_additions: Towers of the Wild: Additions 1.2.3
		trinkets: Trinkets 3.4.0
		wmitaf: WMITAF 3.1.0
		wthit: wthit 5.10.0
		xaerominimap: Xaero's Minimap 22.12.0
		xaeroworldmap: Xaero's World Map 1.26.1
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Moonlight (moonlight), Supplementaries (supplementaries), Not Enough Crashes (notenoughcrashes)

**Comment by meeprdib** [comment]
Mod versions on 1.19.2 and below are not supported
