### ISSUE TITLE
1.19.2forge The game crashes when placing blackboard!!!!

### ISSUE THREAD

**Issue by Busyfox123** [MehVahdJukaar/Supplementaries#432]
supplementaries-1.19.2-2.2.16 Minecraft 1.19.2
 The game crashes when placing blackboard

[items]

**Comment by Busyfox123** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2022-11-10 23:49:06
Description: Tesselating block model

java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'
	at net.minecraftforge.client.model.pipeline.QuadBakingVertexConsumer.m_5752_(QuadBakingVertexConsumer.java:131) ~[forge-1.19.2-43.1.25-universal.jar%23235!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.client.model.forge.BakedQuadBuilderImpl.endVertex(BakedQuadBuilderImpl.java:92) ~[moonlight-1.19.2-2.1.4-forge.jar%23165!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.client.block_models.BlackboardBakedModel.putVertex(BlackboardBakedModel.java:185) ~[supplementaries-1.19.2-2.2.16.jar%23172!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.client.block_models.BlackboardBakedModel.createPixelQuad(BlackboardBakedModel.java:161) ~[supplementaries-1.19.2-2.2.16.jar%23172!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.client.block_models.BlackboardBakedModel.generateQuads(BlackboardBakedModel.java:123) ~[supplementaries-1.19.2-2.2.16.jar%23172!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.client.block_models.BlackboardBakedModel.lambda$getBlockQuads$0(BlackboardBakedModel.java:91) ~[supplementaries-1.19.2-2.2.16.jar%23172!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.client.BlackboardManager$Blackboard.lambda$getOrCreateModel$0(BlackboardManager.java:170) ~[supplementaries-1.19.2-2.2.16.jar%23172!/:?] {re:classloading}
	at java.util.Map.computeIfAbsent(Map.java:1054) ~[?:?] {re:mixin}
	at net.mehvahdjukaar.supplementaries.client.BlackboardManager$Blackboard.getOrCreateModel(BlackboardManager.java:170) ~[supplementaries-1.19.2-2.2.16.jar%23172!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.client.block_models.BlackboardBakedModel.getBlockQuads(BlackboardBakedModel.java:90) ~[supplementaries-1.19.2-2.2.16.jar%23172!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.client.model.CustomBakedModel.getQuads(CustomBakedModel.java:526) ~[moonlight-1.19.2-2.1.4-forge.jar%23165!/:?] {re:mixin,re:classloading,pl:mixin:APP:moonlight.mixins.json:SelfCustomBakedModel,pl:mixin:A}
	at net.minecraft.client.renderer.block.ModelBlockRenderer.renderModelSmooth(ModelBlockRenderer.java:177) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:109) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:farmersdelight.mixins.json:HideBlockBreakProgressMixin,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_234467_(ChunkRenderDispatcher.java:1065) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:908) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$0(ChunkRenderDispatcher.java:195) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.client.model.pipeline.QuadBakingVertexConsumer.m_5752_(QuadBakingVertexConsumer.java:131) ~[forge-1.19.2-43.1.25-universal.jar%23235!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.client.model.forge.BakedQuadBuilderImpl.endVertex(BakedQuadBuilderImpl.java:92) ~[moonlight-1.19.2-2.1.4-forge.jar%23165!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.client.block_models.BlackboardBakedModel.putVertex(BlackboardBakedModel.java:185) ~[supplementaries-1.19.2-2.2.16.jar%23172!/:?] {re:classloading}
-- Block model being tesselated --
Details:
	Block: Block{supplementaries:blackboard}[facing=west,glowing=false,waterlogged=false]
	Block location: World: (134,72,-125), Section: (at 6,8,3 in 8,4,-8; chunk contains blocks 128,-64,-128 to 143,319,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:109) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:farmersdelight.mixins.json:HideBlockBreakProgressMixin,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_234467_(ChunkRenderDispatcher.java:1065) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:908) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$0(ChunkRenderDispatcher.java:195) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- Block being tesselated --
Details:
	Block: Block{supplementaries:blackboard}[facing=west,glowing=false,waterlogged=false]
	Block location: World: (134,72,-125), Section: (at 6,8,3 in 8,4,-8; chunk contains blocks 128,-64,-128 to 143,319,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Stacktrace:
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:farmersdelight.mixins.json:HideBlockBreakProgressMixin,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_234467_(ChunkRenderDispatcher.java:1065) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:908) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$0(ChunkRenderDispatcher.java:195) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Busyfox'/186, l='ClientLevel', x=132.64, y=72.00, z=-123.78]]
	Chunk stats: 361, 210
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,71,-48), Section: (at 0,7,0 in 7,4,-3; chunk contains blocks 112,-64,-48 to 127,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 341 game time, 341 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:580) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:mixin,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,re:classloading,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2278) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_231462_(Minecraft.java:800) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:690) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23230!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.25.jar%23148!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23134!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23134!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23134!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23134!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23134!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23134!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23134!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?] {}

**Comment by Busyfox123** [comment]
blackboard

**Comment by MehVahdJukaar** [comment]
optifine

**Comment by MehVahdJukaar** [comment]
breaks forge. use an optifine older version or switch to mods that dont break the mod loader

**Comment by MehVahdJukaar** [comment]
I'll close since I've got no further info and I assume it was indeed how I said
