### ISSUE TITLE
[Fabric/Quilt] Errors in log during start on 1.19.2

### ISSUE THREAD

**Issue by TobiPeterG** [MehVahdJukaar/Supplementaries#485]
Hey there,
when starting Minecraft (Quilt loader), I get the following errors in the log:
[18:29:18] [Worker-Main-5/ERROR]: Unknown model loader: forge:obj
[18:29:18] [Worker-Main-5/ERROR]: Unknown model loader: forge:obj
[18:29:18] [Worker-Main-5/ERROR]: Unknown model loader: forge:obj
[18:29:18] [Worker-Main-5/ERROR]: Unknown model loader: forge:obj
[18:29:18] [Worker-Main-5/ERROR]: Unknown model loader: forge:obj
[18:29:18] [Worker-Main-5/ERROR]: Unknown model loader: forge:obj
[18:29:18] [Worker-Main-5/ERROR]: Unknown model loader: forge:obj
[18:29:18] [Worker-Main-5/ERROR]: Unknown model loader: forge:obj
[18:29:18] [Worker-Main-5/ERROR]: Unknown model loader: forge:obj
[18:29:18] [Worker-Main-5/ERROR]: Unknown model loader: forge:obj
[18:29:18] [Worker-Main-5/ERROR]: Unknown model loader: forge:obj
[18:29:18] [Worker-Main-5/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_gold' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_gold: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_gold.json
[18:29:18] [Worker-Main-5/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_oxidized' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_oxidized: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_oxidized.json
[18:29:18] [Worker-Main-5/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_glowstone' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_glowstone: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_glowstone.json
[18:29:18] [Worker-Main-5/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_cryptic' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_cryptic: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_cryptic.json
[18:29:18] [Worker-Main-5/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_copper' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_copper: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_copper.json
[18:29:18] [Worker-Main-5/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_brass' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_brass: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_brass.json
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.Objects.checkIndex(Objects.java:359)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$SubList.get(ArrayList.java:1149)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:306)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:282)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:439)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:266)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:308)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:283)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseSymbolsMolang(MolangParser.java:228)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseOneLine(MolangParser.java:216)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseExpression(MolangParser.java:174)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseJson(MolangParser.java:154)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:179)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:58)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToRotationKeyFrames(JsonKeyFrameUtils.java:173)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:278)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:32)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:73)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:91)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.Objects.checkIndex(Objects.java:359)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$SubList.get(ArrayList.java:1149)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:306)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:282)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:439)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:266)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:308)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:283)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseSymbolsMolang(MolangParser.java:228)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseOneLine(MolangParser.java:216)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseExpression(MolangParser.java:174)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseJson(MolangParser.java:154)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:179)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:58)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToRotationKeyFrames(JsonKeyFrameUtils.java:173)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:278)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:32)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:73)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:91)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[18:29:18] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

Should any additional information be required, I'd be happy to help

**Comment by MehVahdJukaar** [comment]
do wall lanterns work?

**Comment by mrukas** [comment]
`[22:35:13] [Worker-Main-22/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_brass' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_brass: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_brass.json
[22:35:13] [Worker-Main-22/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_gold' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_gold: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_gold.json
[22:35:13] [Worker-Main-22/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_copper' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_copper: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_copper.json
[22:35:16] [Worker-Main-17/ERROR]: Using missing texture, file supplementaries:textures/blocks/sconce_fire_nether_brass.png not found
[22:35:16] [Worker-Main-25/ERROR]: Using missing texture, file supplementaries:textures/blocks/sconce_nether_brass.png not found
[22:35:16] [Worker-Main-30/ERROR]: Using missing texture, file buzzier_bees:textures/block/soul_candle_lit.png not found
[22:35:16] [Worker-Main-29/ERROR]: Using missing texture, file supplementaries:textures/items/sconce_nether_brass.png not found
[22:35:16] [Worker-Main-30/ERROR]: Using missing texture, file buzzier_bees:textures/block/soul_candle.png not found
[22:35:16] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[22:35:16] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[22:35:16] [Render thread/WARN]: Missing sound for event: supplementaries:item.wrench.hit`

I also get such errors using fabric. Lanterns do work, but only the standard lantern, the soul lantern, the copper lantern and the crimson lantern exist. There is no brass or gold lantern. It appears something is missing.
Also the wrench.hit sound appears to be missing, regarding the logs. But when i hit an entity with it the sound plays.

**Comment by MehVahdJukaar** [comment]
I think all those are harmless. I'll try to clean them anyway

**Comment by davispuh** [comment]
I'm seeing same error message, but I'm not using this mod, it looks like it comes from https://www.curseforge.com/minecraft/mc-mods/geckolib

**Comment by Krimatoria** [comment]
I have these warnings in orange.
supplementaries-1.19.2-2.4.19.jar

[00:55:00] [Worker-ResourceReload-6/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_lead' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_lead: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_lead.json
[00:55:00] [Worker-ResourceReload-6/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_copper' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_copper: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_copper.json
[00:55:00] [Forge Version Check/INFO]: [moonlight] Found status: UP_TO_DATE Current: 1.19.2-2.3.6 Target: null
[00:55:00] [Forge Version Check/INFO]: [iceberg] Starting version check at https://mc-update-check.anthonyhilyard.com/520110
[00:55:00] [Worker-ResourceReload-6/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_silver' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_silver: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_silver.json
[00:55:00] [Worker-ResourceReload-6/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_brass' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_brass: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_brass.json
[00:55:00] [Worker-ResourceReload-6/WARN]: Unable to load model: 'supplementaries:blocks/wall_lanterns/wall_lantern_gold' referenced from: supplementaries:blocks/wall_lanterns/wall_lantern_gold: java.io.FileNotFoundException: supplementaries:models/blocks/wall_lanterns/wall_lantern_gold.json

**Comment by MehVahdJukaar** [comment]
none of those is important. closing as 1.19 isnt even supported anymore and none of those errors has any negative effect

**Comment by Krimatoria** [comment]
> ничто из этого не важно. закрытие, поскольку версия 1.19 больше не поддерживается, и ни одна из этих ошибок не имеет никакого негативного эффекта.

I forgot to say that this is Forge
