### ISSUE TITLE
1.16.5 Error message Forge server

### ISSUE THREAD

**Issue by Senyum** [MehVahdJukaar/Supplementaries#50]
Hi, when i use mod on server, he all time on server loading tell me this about some items from mod
forge-1.16.5-36.1.0.jar
Supplementaries-1.16.5-0.11.0b.jar
[11:50:45] [Worker-Main-13/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe supplementaries:candle_holder
com.google.gson.JsonSyntaxException: Unknown item tag 'supplementaries:candle/base'
        at net.minecraft.item.crafting.Ingredient.func_199803_a(Ingredient.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:41) ~[forge:?] {re:classloading}
        at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:155) ~[forge:?] {re:classloading}
        at net.minecraft.item.crafting.Ingredient.func_199802_a(Ingredient.java:189) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.item.crafting.ShapedRecipe.func_192408_a(ShapedRecipe.java:252) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.ShapedRecipe.access$000(ShapedRecipe.java:24) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:276) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:272) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:141) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraftforge.common.crafting.ConditionalRecipe$Serializer.func_199425_a_(ConditionalRecipe.java:93) ~[forge:?] {re:classloading}
        at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:141) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:61) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:38) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_281] {}
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
        at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_281] {}

**Comment by MehVahdJukaar** [comment]
fix coming next update. for now that's nothing to worry about it's just complaining for a typo in a recipe that caused it not to load
