### ISSUE TITLE
Crash when placing jar 

### ISSUE THREAD

**Issue by aria1th** [MehVahdJukaar/Supplementaries#500]
Fabric instance, 1.19.2
Moonlightlib 2.2.3
Supplementaries 2.2.44
Fabric loader 0.14.13

```
Description: Unexpected error

java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / moonlight:moonlight/soft_fluids]
	at net.minecraft.class_5455.method_30534(class_5455.java:66)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.minecraft.class_5455.method_30530(class_5455.java:66)
	at net.mehvahdjukaar.moonlight.api.misc.DataObjectReference.get(DataObjectReference.java:37)
	at net.mehvahdjukaar.moonlight.api.fluids.SoftFluidTank.<init>(SoftFluidTank.java:43)
	at net.mehvahdjukaar.moonlight.api.fluids.fabric.SoftFluidTankImpl.<init>(SoftFluidTankImpl.java:26)
	at net.mehvahdjukaar.moonlight.api.fluids.fabric.SoftFluidTankImpl.create(SoftFluidTankImpl.java:22)
	at net.mehvahdjukaar.moonlight.api.fluids.SoftFluidTank.create(SoftFluidTank.java)
	at net.mehvahdjukaar.supplementaries.common.block.tiles.JarBlockTile.<init>(JarBlockTile.java:45)
	at net.mehvahdjukaar.supplementaries.common.block.blocks.JarBlock.method_10123(JarBlock.java:171)
	at net.minecraft.class_2818.method_12010(class_2818.java:268)
	at net.minecraft.class_1937.method_30092(class_1937.java:221)
	at net.minecraft.class_638.method_30092(class_638.java:156)
	at net.minecraft.class_1937.method_8652(class_1937.java:206)
	at net.minecraft.class_1747.method_7708(class_1747.java:159)
	at net.minecraft.class_1747.method_7712(class_1747.java:76)
	at net.mehvahdjukaar.supplementaries.common.items.AbstractMobContainerItem.method_7712(AbstractMobContainerItem.java:347)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.mehvahdjukaar.supplementaries.common.items.AbstractMobContainerItem.method_7884(AbstractMobContainerItem.java:237)
	at net.mehvahdjukaar.supplementaries.common.items.JarItem.method_7884(JarItem.java:262)
	at net.minecraft.class_1799.method_7981(class_1799.java:264)
	at net.minecraft.class_636.method_41934(class_636.java:363)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1748)
	at net.minecraft.class_310.method_1508(class_310.java:2002)
	at net.minecraft.class_310.method_1574(class_310.java:1829)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

```

How to reproduce:

Shift-right click block with jar in right hand.

https://github.com/MehVahdJukaar/Moonlight/blob/multi-loader/common/src/main/java/net/mehvahdjukaar/moonlight/api/fluids/SoftFluidTank.java#L43

where creating 
https://github.com/MehVahdJukaar/Moonlight/blob/multi-loader/common/src/main/java/net/mehvahdjukaar/moonlight/api/fluids/VanillaSoftFluids.java#L27

https://github.com/MehVahdJukaar/Moonlight/blob/multi-loader/common/src/main/java/net/mehvahdjukaar/moonlight/api/fluids/SoftFluidRegistry.java#L37

- If applicable, add screenshots to help explain your problem.

**Comment by MehVahdJukaar** [comment]
it says that the entire registry is missing. that should never happen and its an indication of some mods somehow managing to yeet it. I know velocity had such a problem but was since then fixed

**Comment by aria1th** [comment]
You might be correct, we're using velocity in server, that might be the problem. I'll check if I can do something

**Comment by MehVahdJukaar** [comment]
did they not fix that? it took a bit for them to correct it but after a while they broke it again. I didnt realized that got broken for the third time lol

**Comment by aria1th** [comment]
It was velocity issue, thanks for the help!
