### ISSUE TITLE
Game crashes while using the jukebox in LAN world

### ISSUE THREAD

**Issue by SystemlessDev** [MehVahdJukaar/Supplementaries#509]
This issue is reported here simply due to me not knowing who is at fault. I have checked the bug tracker for Moonlight, Supplementaries and CPM, and found no existing report. It works fine with Moonlight and CPM, but that still doesn't mean that it's Supplementaries' fault. 

In this case the crash occurs on every client that can hear the jukebox. 

I have not tested with a dedicated server.

**Recreated on version and modloader:**
- Minecraft 1.19.2
- Fabric loader 0.14.14

**Mods used:**
- [Fabric API 0.73.2](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4373739)
- [Moonlight 2.2.6](https://www.curseforge.com/minecraft/mc-mods/selene/files/4391194)
- [Supplementaries 2.2.46](https://www.curseforge.com/minecraft/mc-mods/supplementaries/files/4375772)
- [Customizable Player Models 0.6.5a](https://www.curseforge.com/minecraft/mc-mods/custom-player-models-fabric/files/4378451)

**Recreation steps:**
- Start LAN world with the above mods present
- Join with a 2nd client (same mods)
- Start playing a disc in a jukebox
- See the game crash with the exception below

**Exception thrown:**
```
[00:10:18] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.class_761.method_22979(class_761.java:1558) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1321) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:816) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.14.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]

```

**Comment by MehVahdJukaar** [comment]
Need a crash log

**Comment by SystemlessDev** [comment]
The full log provides no info that you don't already have. 

Regardless here you go:
[host.log](https://github.com/MehVahdJukaar/Supplementaries/files/10716110/host.log)
[client.log](https://github.com/MehVahdJukaar/Supplementaries/files/10716111/client.log)

**Comment by MehVahdJukaar** [comment]
same issue as this https://github.com/tom5454/CustomPlayerModels/issues/337

**Comment by MehVahdJukaar** [comment]
added a workaround that accounts for their non empty pose stack returned there
