### ISSUE TITLE
[Bug] Using slingshot will cause server crash (Entity error)

### ISSUE THREAD

**Issue by xiaofan7520** [MehVahdJukaar/Supplementaries#515]
```
---- Minecraft Crash Report ----
// My bad.

Time: 2023-02-18 14:12:02
Description: Ticking entity

java.lang.IllegalArgumentException: Level must be either ServerLevel or ClientLevel
	at net.mehvahdjukaar.moonlight.api.util.fake_player.FakePlayerManager.get(FakePlayerManager.java:34)
	at net.mehvahdjukaar.moonlight.api.util.fake_player.FakePlayerManager.get(FakePlayerManager.java:41)
	at net.mehvahdjukaar.moonlight.api.util.fake_player.FakePlayerManager.getDefault(FakePlayerManager.java:56)
	at net.mehvahdjukaar.supplementaries.common.entities.SlingshotProjectileEntity.method_24920(SlingshotProjectileEntity.java:165)
	at net.minecraft.class_1676.method_7488(class_1676.java:153)
	at net.mehvahdjukaar.moonlight.api.entity.ImprovedProjectileEntity.method_5773(ImprovedProjectileEntity.java:219)
	at net.mehvahdjukaar.supplementaries.common.entities.SlingshotProjectileEntity.method_5773(SlingshotProjectileEntity.java:195)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because the return value of "net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel()" is null
	at net.minecraft.class_3244.handler$zga000$adventure$initTracking(class_3244.java:3044)
	at net.minecraft.class_3244.<init>(class_3244.java:242)
	at net.mehvahdjukaar.moonlight.api.util.fake_player.FakeServerPlayer$FakePlayerNetHandler.<init>(FakeServerPlayer.java:134)
	at net.mehvahdjukaar.moonlight.api.util.fake_player.FakeServerPlayer.<init>(FakeServerPlayer.java:63)
	at net.mehvahdjukaar.moonlight.api.util.fake_player.FakeServerPlayer.lambda$get$1(FakeServerPlayer.java:50)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at net.mehvahdjukaar.moonlight.api.util.fake_player.FakeServerPlayer.get(FakeServerPlayer.java:50)
	at net.mehvahdjukaar.moonlight.api.util.fake_player.FakePlayerManager.get(FakePlayerManager.java:28)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.mehvahdjukaar.moonlight.api.util.fake_player.FakePlayerManager.get(FakePlayerManager.java:34)
	at net.mehvahdjukaar.moonlight.api.util.fake_player.FakePlayerManager.get(FakePlayerManager.java:41)
	at net.mehvahdjukaar.moonlight.api.util.fake_player.FakePlayerManager.getDefault(FakePlayerManager.java:56)
	at net.mehvahdjukaar.supplementaries.common.entities.SlingshotProjectileEntity.method_24920(SlingshotProjectileEntity.java:165)
	at net.minecraft.class_1676.method_7488(class_1676.java:153)
	at net.mehvahdjukaar.moonlight.api.entity.ImprovedProjectileEntity.method_5773(ImprovedProjectileEntity.java:219)
	at net.mehvahdjukaar.supplementaries.common.entities.SlingshotProjectileEntity.method_5773(SlingshotProjectileEntity.java:195)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
Mixins in Stacktrace: None found

-- Entity being ticked --
Details:
	Entity Type: supplementaries:slingshot_projectile (net.mehvahdjukaar.supplementaries.common.entities.SlingshotProjectileEntity)
	Entity ID: 2055
	Entity Name: Slingshot Projectile
	Entity's Exact location: 9.06, 64.00, -6.32
	Entity's Block location: World: (9,64,-7), Section: (at 9,0,9 in 0,4,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.02, -0.77, -0.86
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Mixins in Stacktrace: None found

-- Affected level --
Details:
	All players: 3 total; [class_3222['CHN_96_STUDIO'/673, l='ServerLevel[mod_server_map123123]', x=-32.68, y=96.00, z=-3385.40], class_3222['LarryFoulke2914'/995, l='ServerLevel[mod_server_map123123]', x=8.91, y=66.54, z=-1.10], class_3222['U__U'/1028, l='ServerLevel[mod_server_map123123]', x=356.24, y=64.00, z=540.19]]
	Chunk stats: 8942
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,68,0), Section: (at 0,4,0 in -2,4,0; chunk contains blocks -32,-64,0 to -17,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 37590536 game time, 23318015 day time
	Level name: mod_server_map123123
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 18099 (now: false), thunder time: 84627 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Mixins in Stacktrace: None found

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.15.0-58-generic
	Java Version: 17.0.5, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 9959524352 bytes (9498 MiB) / 11811160064 bytes (11264 MiB) up to 11811160064 bytes (11264 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Genuine Intel(R) CPU 0000 @ 2.10GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 12
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Juniper XT [Radeon HD 5770]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x68b8
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): -0.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): -0.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 10035.87
	Virtual memory used (MB): 15485.16
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1068.00
	JVM Flags: 21 total; -Xms11G -Xmx11G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		alternate-current: Alternate Current 1.4.0
		architectury: Architectury 6.4.62
		backportgamerules: Backport Gamerules 1.0.1+1.19.2
		badpackets: Bad Packets 0.2.1
		balm-fabric: Balm 4.5.2+0
		beefix: Bee Fix 1.0-SNAPSHOT+1.19.2
		betterimpaling: Better Impaling 2.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		cmdspy: Command Spy 1.3.1
		collective: Collective 6.43
		connectivity: Connectivity Mod 1.19.2-3.8
		create: Create 0.5.0.g+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.687+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.687+1.19.2
					com_github_llamalad7_mixinextras: MixinExtras 0.1.1
					mm: Manningham Mills 2.3
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.1.687+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.687+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.687+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.687+1.19.2
				porting_lib_models: Porting Lib Models 2.1.687+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.687+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.687+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.687+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.687+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.687+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.1.687+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.1.687+1.19.2
							porting_lib_constants: Porting Lib Constants 2.1.687+1.19.2
						porting_lib_common: Porting Lib Common 2.1.687+1.19.2
			registrate-fabric: Registrate for Fabric 1.1.47-MC1.19.2
		create_crystal_clear: Create: Crystal Clear 1.0+1.19.2
		createdeco: Create Deco 1.2.12-1.19.2
		damagetilt: Damage Tilt 1.19-fabric-0.1.2
		deathbackup: Death Backup 3.0
		delightchef: Chef's Delight 1.0.1-1.19.2
			structurized-reborn: Structurized Reborn 1.19-01
		dismountentity: Dismount Entity 3.0
		dragonfight: Dragonfight Mod 1.19.2-2.6
		essential_commands: Essential Commands 0.30.0-mc1.19.2
			ec-core: Essential Commands Core 1.3.0-mc1.19.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			org_yaml_snakeyaml: snakeyaml 1.33
			playerabilitylib: Pal 1.6.0
		fabric-api: Fabric API 0.73.2+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.7+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.35+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.5+dce4603e90
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.38+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.12+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.15+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.23+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.1+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricenchantments: Fabric Enchantments 0.9.0
		fabricloader: Fabric Loader 0.14.11
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		ferritecore: FerriteCore 5.1.0
		forgeconfigapiport: Forge Config API Port 4.2.6
		htm: Hey That's Mine 1.1.6
			common-protection-api: Common Protection API 1.0.0
			server_translations_api: Server Translations API 1.4.18+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		image2map: Image2Map 0.3.0
			map-canvas-api: Map Canvas API 0.2.0+1.19.1
			sgui: sgui 1.1.5+1.19.1
		invview: InvView 1.4.9-1.19+
		jade: Jade 8.7.3
		java: OpenJDK 64-Bit Server VM 17
		jline4mcdsrv: JLine for Minecraft Dedicated Server 0.4.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			org_fusesource_jansi_jansi: jansi 2.4.0
			org_jline_jline: jline 3.22.0
			org_jline_jline-terminal-jansi: jline-terminal-jansi 3.22.0
		leaf-decay: Leaf Decay 1.5.0-1.19.2
		ledger: Ledger 1.2.5
		ledger-databases: Ledger Databases 1.1.1
			com_h2database_h2: h2 1.4.200
			mysql_mysql-connector-java: mysql-connector-java 8.0.19
			org_postgresql_postgresql: postgresql 42.3.0
		lithium: Lithium 0.10.4
		luckperms: LuckPerms 5.4.52
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		minecraft: Minecraft 1.19.2
		minecraft-command-permissions: Minecraft Command Permissions 1.6.1
		mixintrace: MixinTrace 1.1.1+1.17
		moonlight: Moonlight 1.19.2-2.2.7
		nbtcrafting: NBT Crafting 2.2.3+mc1.19
		nextspring: NextSpring 1.0.0
		nochatreports: No Chat Reports 1.19.2-v1.13.11
		overweight_farming: Overweight Farming 1.19.2-2.0.2-fabric
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			midnightlib: MidnightLib 1.0.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		prettybeaches: Pretty Beaches 8.0.0
		roughlyenoughitems: Roughly Enough Items 9.1.585
			error_notifier: Error Notifier 1.0.9
		servercore: ServerCore 1.3.3-1.19.2
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			me_lucko_spark-api: spark-api 0.1-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		snowballkb: Snowball and Egg Knockback 1.2-1.19
		spark: spark 1.10.17
		starlight: Starlight 1.1.1+fabric.ae22326
		supplementaries: Supplementaries 1.19.2-2.2.50
		syncmatica: Syncmatica 0.3.5
		tabtps-fabric: TabTPS 1.3.15
			adventure-platform-fabric: adventure-platform-fabric 5.4.0-SNAPSHOT
				net_kyori_adventure-api: adventure-api 4.11.0
				net_kyori_adventure-key: adventure-key 4.11.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.1.1
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.11.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.11.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.11.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.11.0
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
			cloud: Cloud 1.8.0-SNAPSHOT
				cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.8.0-SNAPSHOT
				cloud_commandframework_cloud-core_: cloud-core 1.8.0-SNAPSHOT
				cloud_commandframework_cloud-services_: cloud-services 1.8.0-SNAPSHOT
				io_leangen_geantyref_geantyref: geantyref 1.3.13
			cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.8.0-SNAPSHOT
			com_typesafe_config: config 1.4.2
			net_kyori_adventure-serializer-configurate4: adventure-serializer-configurate4 4.11.0
			net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
			net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.11.0
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		torchhit: Torch hit! 5.0.0.0
		vanish: vanish 1.4.3
		voicechat: Simple Voice Chat 1.19.2-2.3.28
		wandering_collector: Wandering Collector 1.2.0+mc1.19
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.7.1+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
		way_much_faster_oxidize: Way Much Faster Oxidize 1.1.1
		worldedit: WorldEdit 7.2.11-beta-02+315c5d0
		wthit: wthit 5.13.4
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
	Server Running: true
	Player Count: 3 / 20; [class_3222['CHN_96_STUDIO'/673, l='ServerLevel[mod_server_map123123]', x=-32.68, y=96.00, z=-3385.40], class_3222['LarryFoulke2914'/995, l='ServerLevel[mod_server_map123123]', x=8.91, y=66.54, z=-1.10], class_3222['U__U'/1028, l='ServerLevel[mod_server_map123123]', x=356.24, y=64.00, z=540.19]]
	Data Packs: vanilla, Fabric Mods, file/AdditionalStructures_for_luatea_server 1.19remake.zip, file/Structory-1.19-1.3.zip, file/Terralith_1.19.x_v2.3.5.zip, file/Venturecraft Beta 0.4 1.19remake.zip, file/amplified-nether-1-19.zip, file/better-stonecutter-v1-1.zip, file/cuutterPlus_lunatea (incompatible), file/gm4_beehive_inspector_1_19.zip, file/gm4_desire_lines_1_19.zip, file/lunatea, file/nullscape-v1-2a.zip, file/quote, file/vanillaChair_1.19.zip, file/wanderingcities.zip, file/skyvillages (incompatible), file/Armor Stand Arms.zip (incompatible), file/Hats.zip (incompatible), file/Throwable Swords.zip (incompatible), file/command_block_rod (incompatible), file/nutrition-1-0-6-for-mc-1-19-2.zip, file/farmersdelight_pr116, file/forge_tags_fix, file/create_extension (incompatible), Supplementaries Generated Pack, file/item_ban
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

- Mod version, MC version and Loader you are using
supplementaries: 1.19.2-2.2.50-fabric
Moonlight Lib: 1.19.2-2.2.7-fabric
Minecraft version: 1.19.2 fabric

- A description of your issue and how to reproduce
Use it in server

**Comment by MehVahdJukaar** [comment]
Cant replicate. I see an error from this mod "net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel()

**Comment by xiaofan7520** [comment]
> 无法复制。我看到这个mod的错误“net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel（）

I think it's a mod compatibility problem. Testing. (＃°Д°)

**Comment by xiaofan7520** [comment]
> 无法复制。我看到这个mod的错误“net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel（）

Oh s*t, This is the problem of MOD:[TabTps](https://github.com/jpenilla/TabTPS/issues/39)
(￣_￣|||)

**Comment by xiaofan7520** [comment]
> 无法复制。我看到这个mod的错误“net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel（）

Oh s*t, This is the problem of MOD:[TabTps](https://github.com/jpenilla/TabTPS/issues/39)
(￣_￣|||)
