### ISSUE TITLE
game not loading due to mod

### ISSUE THREAD

**Issue by BloodRoseDiamond** [MehVahdJukaar/Supplementaries#605]
some reason minecraft wont load with supplementaries

![Screenshot (11)](https://github.com/MehVahdJukaar/Supplementaries/assets/133222566/fa2a8f80-2241-4738-8e1f-62814993bf97)

i am using the latest version of the mod moonlight and as I'm using curseforge mod pack etc using upto date forge version.

crash report 

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-05-11 12:19:45
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:58) ~[forge-1.19.4-45.0.58-universal.jar%23233!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:165) ~[forge-1.19.4-45.0.58-universal.jar%23233!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:591) ~[client-1.19.4-20230314.122934-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:420) ~[client-1.19.4-20230314.122934-srg.jar%23228!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:585) ~[client-1.19.4-20230314.122934-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_86412_(LoadingOverlay.java:135) ~[client-1.19.4-20230314.122934-srg.jar%23228!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:940) ~[client-1.19.4-20230314.122934-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1162) ~[client-1.19.4-20230314.122934-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:733) ~[client-1.19.4-20230314.122934-srg.jar%23228!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[forge-45.0.58.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.0.58.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.6.jar:?] {}
-- MOD supplementaries --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.4-45.0.58.jar%23230!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.4-45.0.58.jar%23229!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.NoClassDefFoundError: net/mehvahdjukaar/moonlight/api/platform/RegHelper$CommandRegistration
		at net.mehvahdjukaar.supplementaries.reg.ModCommands.init(ModCommands.java:14) ~[supplementaries-1.19.4-2.3.10.jar%23220!/:?] {re:classloading}
		at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:83) ~[supplementaries-1.19.4-2.3.10.jar%23220!/:?] {re:classloading,re:mixin}
		at net.mehvahdjukaar.supplementaries.forge.SupplementariesForge.<init>(SupplementariesForge.java:40) ~[supplementaries-1.19.4-2.3.10.jar%23220!/:?] {re:classloading,re:mixin}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.4-45.0.58.jar%23230!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.4-45.0.58.jar%23229!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/wolfm/curseforge/minecraft/Instances/arigolia/mods/supplementaries-1.19.4-2.3.10.jar
	Failure message: Supplementaries (supplementaries) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.19.4-2.3.10
	Mod Issue URL: https://github.com/MehVahdJukaar/Supplementaries/issues
	Exception message: java.lang.ClassNotFoundException: net.mehvahdjukaar.moonlight.api.platform.RegHelper$CommandRegistration
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.6.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at net.mehvahdjukaar.supplementaries.reg.ModCommands.init(ModCommands.java:14) ~[supplementaries-1.19.4-2.3.10.jar%23220!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:83) ~[supplementaries-1.19.4-2.3.10.jar%23220!/:?] {re:classloading,re:mixin}
	at net.mehvahdjukaar.supplementaries.forge.SupplementariesForge.<init>(SupplementariesForge.java:40) ~[supplementaries-1.19.4-2.3.10.jar%23220!/:?] {re:classloading,re:mixin}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.4-45.0.58.jar%23230!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.4-45.0.58.jar%23229!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 837262336 bytes (798 MiB) / 1468006400 bytes (1400 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD A8-9600 RADEON R7, 10 COMPUTE CORES 4C+6G  
	Identifier: AuthenticAMD Family 21 Model 101 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.09
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GT 1030
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1d01
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Graphics card #1 name: AMD Radeon R7 Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x9874
	Graphics card #1 versionInfo: DriverVersion=27.20.1020.1
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 20153.86
	Virtual memory used (MB): 11909.51
	Swap memory total (MB): 4352.00
	Swap memory used (MB): 308.27
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.0.58.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.58.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.0.58.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.0.58.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.58.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		handcrafted-forge-1.19.4-2.2.0.jar                |Handcrafted                   |handcrafted                   |2.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.4-2.2.0.154.jar           |TerraBlender                  |terrablender                  |2.2.0.154           |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.19.4-2.3.8-forge.jar                  |Moonlight Library             |moonlight                     |1.19.4-2.3.8        |COMMON_SET|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.19.4-2.24.jar               |Mouse Tweaks                  |mousetweaks                   |2.24                |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.19.4-4.1.3.jar                   |GeckoLib 4                    |geckolib                      |4.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.4-forge-13.1.0.9.jar                     |Just Enough Items             |jei                           |13.1.0.9            |COMMON_SET|Manifest: NOSIGNATURE
		simplefarming-1.19.4-2.0.3.jar                    |Simple Farming                |simplefarming                 |1.19.4-2.0.3        |COMMON_SET|Manifest: NOSIGNATURE
		recrafted_creatures-1.1.0-1.19.4.jar              |Recrafted Creatures           |recrafted_creatures           |1.1.0-1.19.4        |COMMON_SET|Manifest: NOSIGNATURE
		duclib-1.19.4-1.0.jar                             |DucLib                        |duclib                        |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		valhelsia_furniture-forge-1.19.4-1.1.0.jar        |Valhelsia Furniture           |valhelsia_furniture           |1.19.4-1.1.0        |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.19.4-5.1.5.3.jar                   |Curios API                    |curios                        |1.19.4-5.1.5.3      |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.19.4-13.1.0.jar                 |Waystones                     |waystones                     |13.1.0              |COMMON_SET|Manifest: NOSIGNATURE
		Structory_1.19.4_v1.3.1a.jar                      |Structory                     |structory                     |1.3.1a              |COMMON_SET|Manifest: NOSIGNATURE
		VarietyAquatic-1.0.4-SNAPSHOT.jar                 |varietyaquaticforge           |varietyaquaticforge           |1.0.4-SNAPSHOT      |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.3.3-1.19.4.jar                          |Citadel                       |citadel                       |2.3.3               |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.22.2.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.2              |COMMON_SET|Manifest: NOSIGNATURE
		artifacts-1.19.4-6.1.0.jar                        |Artifacts                     |artifacts                     |1.19.4-6.1.0        |COMMON_SET|Manifest: NOSIGNATURE
		MobVote22-1.19.4-1.3.0.jar                        |Mob Vote '22                  |mob_vote_22                   |1.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.4-18.0.2.jar                 |Bookshelf                     |bookshelf                     |18.0.2              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		resourcefullib-forge-1.19.4-1.3.1.jar             |Resourceful Lib               |resourcefullib                |1.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		guardvillagers-1.19.4-1.5.6.jar                   |Guard Villagers               |guardvillagers                |1.19.4-1.5.6        |COMMON_SET|Manifest: NOSIGNATURE
		architectury-8.1.80-forge.jar                     |Architectury                  |architectury                  |8.1.80              |COMMON_SET|Manifest: NOSIGNATURE
		biomemakeover-FORGE-1.19.4-1.8.3.jar              |Biome Makeover                |biomemakeover                 |1.19.4-1.8.3        |COMMON_SET|Manifest: NOSIGNATURE
		minecraft-comes-alive-7.4.8+1.19.4-universal.jar  |Minecraft Comes Alive         |mca                           |7.4.8+1.19.4        |COMMON_SET|Manifest: NOSIGNATURE
		taniwha-forge-1.19.4-4.0.0.jar                    |Taniwha                       |taniwha                       |1.19.4-4.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		vinery-1.2.6-forge.jar                            |Vinery                        |vinery                        |1.2.6               |COMMON_SET|Manifest: NOSIGNATURE
		moremobvariants-forge-1.1.0.jar                   |More Mob Variants             |moremobvariants               |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.19.4-6.0.2.jar                       |Balm                          |balm                          |6.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		mysticsbiomes-1.19.4-4.1.0.jar                    |Mystic's Biomes               |mysticsbiomes                 |1.19.4-4-1.0        |COMMON_SET|Manifest: NOSIGNATURE
		FallingTree-1.19.4-3.12.2.jar                     |FallingTree                   |fallingtree                   |3.12.2              |COMMON_SET|Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		cloth-config-10.0.96-forge.jar                    |Cloth Config v10 API          |cloth_config                  |10.0.96             |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.4-45.0.58-universal.jar                |Forge                         |forge                         |45.0.58             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		expandability-forge-8.0.0.jar                     |ExpandAbility                 |expandability                 |8.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		valhelsia_core-forge-1.19.4-0.5.0.jar             |Valhelsia Core                |valhelsia_core                |1.19.4-0.5.0        |COMMON_SET|Manifest: NOSIGNATURE
		valhelsia_structures-forge-1.19.4-1.1.0.jar       |Valhelsia Structures          |valhelsia_structures          |1.19.4-1.1.0        |COMMON_SET|Manifest: NOSIGNATURE
		supplementaries-1.19.4-2.3.10.jar                 |Supplementaries               |supplementaries               |1.19.4-2.3.10       |ERROR     |Manifest: NOSIGNATURE
		geophilic-1.19.4-2.0.0.jar                        |Geophilic                     |geophilic                     |1.19.4-2.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		friendsandfoes-forge-mc1.19.4-1.8.1.jar           |Friends&Foes                  |friendsandfoes                |1.8.1               |COMMON_SET|Manifest: NOSIGNATURE
		DarkPaintings-Forge-1.19.4-15.0.1.jar             |DarkPaintings                 |darkpaintings                 |15.0.1              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		caupona-1.19.4-0.3.2.jar                          |Caupona                       |caupona                       |1.19.4-0.3.2        |COMMON_SET|Manifest: NOSIGNATURE
		drinkbeer-refill-1.19.4-1.0.2.jar                 |Drink Beer Refill             |drinkbeer                     |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 0241065a-a575-4fb2-9d5f-b2ba3c2db80b
	FML: 45.0
	Forge: net.minecraftforge:45.0.58

**Comment by MehVahdJukaar** [comment]
so that version you have is not on curseforge. I dont know where you got it but i only shared in on a channel on my discord and it has to be used with a new moonlight version i posted there too
