### ISSUE TITLE
Crash with newest dependencies

### ISSUE THREAD

**Issue by mrukas** [MehVahdJukaar/Supplementaries#628]
Supplementaries crashes when using the newest versions (as listed in dependencies) of Fabric API and Moolight Lib.

If you use the following (newest) dependencies:
- Fabric 0.14.21
- Fabric API 0.83.0+1.19.4 (Beta)
- Moonlight Lib 1.19.4-2.4.13
- Supplementaries 1.19.4-2.4.15

I get the following error on start and minecraft crashes:

> [31/05/2023 23:08:38 PM] #
[31/05/2023 23:08:38 PM] # A fatal error has been detected by the Java Runtime Environment:
[31/05/2023 23:08:38 PM] #
[31/05/2023 23:08:38 PM] #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffcb85ac6cd, pid=17980, tid=9632
[31/05/2023 23:08:38 PM] #
[31/05/2023 23:08:38 PM] # JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
[31/05/2023 23:08:38 PM] # Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
[31/05/2023 23:08:38 PM] # Problematic frame:
[31/05/2023 23:08:38 PM] # C  [lwjgl_opengl.dll+0xc6cd]
[31/05/2023 23:08:38 PM] #
[31/05/2023 23:08:38 PM] # No core dump will be written. Minidumps are not enabled by default on client versions of Windows
[31/05/2023 23:08:38 PM] #
[31/05/2023 23:08:38 PM] # An error report file with more information is saved as:
[31/05/2023 23:08:38 PM] # **USERSDIR**\instances\ModpackTestbertino\hs_err_pid17980.log
[31/05/2023 23:08:38 PM] #
[31/05/2023 23:08:38 PM] # If you would like to submit a bug report, please visit:
[31/05/2023 23:08:38 PM] #   https://github.com/microsoft/openjdk/issues
[31/05/2023 23:08:38 PM] # The crash happened outside the Java Virtual Machine in native code.
[31/05/2023 23:08:38 PM] # See problematic frame for where to report the bug.
[31/05/2023 23:08:38 PM] #
[31/05/2023 23:08:38 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.

**If i remove Supplemenataries and only have the newest Fabric API and Moonlight Lib active, minecraft starts normally.**

**I kept the newest versions of Fabric API and Moonlight Lib and tried to downgrade Supplementaries.
If i use Supplementaries 1.19.4-2.4.11 if get the following error:**

> [31/05/2023 23:16:34 PM] java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'moonlight'!
[31/05/2023 23:16:34 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
[31/05/2023 23:16:34 PM] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
[31/05/2023 23:16:34 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
[31/05/2023 23:16:34 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[31/05/2023 23:16:34 PM] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
[31/05/2023 23:16:34 PM] 	at net.minecraft.class_310.<init>(class_310.java:468)
[31/05/2023 23:16:34 PM] 	at net.minecraft.client.main.Main.main(Main.java:198)
[31/05/2023 23:16:34 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
[31/05/2023 23:16:34 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[31/05/2023 23:16:34 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[31/05/2023 23:16:34 PM] Caused by: java.lang.NoClassDefFoundError: net/mehvahdjukaar/moonlight/api/map/client/MapDecorationClientHandler
[31/05/2023 23:16:34 PM] 	at net.mehvahdjukaar.supplementaries.common.misc.map_markers.client.ModMapMarkersClient.init(ModMapMarkersClient.java:9)
[31/05/2023 23:16:34 PM] 	at net.mehvahdjukaar.supplementaries.reg.ClientRegistry.setup(ClientRegistry.java:138)
[31/05/2023 23:16:34 PM] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[31/05/2023 23:16:34 PM] 	at net.mehvahdjukaar.moonlight.fabric.MoonlightFabricClient.onInitializeClient(MoonlightFabricClient.java:10)
[31/05/2023 23:16:34 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[31/05/2023 23:16:34 PM] 	... 7 more
[31/05/2023 23:16:34 PM] Caused by: java.lang.ClassNotFoundException: net.mehvahdjukaar.moonlight.api.map.client.MapDecorationClientHandler
[31/05/2023 23:16:34 PM] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[31/05/2023 23:16:34 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[31/05/2023 23:16:34 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
[31/05/2023 23:16:34 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
[31/05/2023 23:16:34 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[31/05/2023 23:16:34 PM] 	... 12 more

The last combination that did work for me was the following:
- Fabric 0.14.21
- Fabric API 0.83.0+1.19.4 (Beta)
- Moonlight Lib 1.19.4-2.4.8
- Supplementaries 1.19.4-2.4.11

**Comment by MehVahdJukaar** [comment]
not sure. whatever this is seems like a fabric issue. i tried with an older version and i did get that. then i update to fabric loader and api same as yours and it didnt happen anymore

**Comment by mrukas** [comment]
Wow thanks for your great work! Your update fixed it!
