### ISSUE TITLE
Bug error

### ISSUE THREAD

**Issue by MrGabe05** [MehVahdJukaar/Supplementaries#651]
I'm running the mod on minecraft version 1.19.2, and I'm constantly getting this error:

[15:41:52 ERROR]: Failed to save chunk [109, 21]
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Method net/mehvahdjukaar/supplementaries/common/block/tiles/SackBlockTile.getViewers()Ljava/util/List; is abstract
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraft.server.level.ChunkMap.m_140353_(ChunkMap.java:471) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:A}
        at net.minecraft.server.level.ChunkMap.m_140280_(ChunkMap.java:442) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:323) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:APP:mixins.cobblemon-common.json:ServerChunkManagerMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:313) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:mixins.cobblemon-common.json:MinecraftDedicatedServerMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1005) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:327) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:944) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:791) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:278) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.AbstractMethodError: Method net/mehvahdjukaar/supplementaries/common/block/tiles/SackBlockTile.getViewers()Ljava/util/List; is abstract
        at net.mehvahdjukaar.supplementaries.common.block.tiles.SackBlockTile.getViewers(SackBlockTile.java) ~[supplementaries-1.19.2-2.3.17.jar%23241!/:?] {re:classloading}
        at net.minecraft.server.level.ServerLevel.m_8712_(ServerLevel.java:904) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:mixins.cobblemon-common.json:MinecraftDedicatedServerMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
        at net.minecraft.server.level.ChunkMap.m_202998_(ChunkMap.java:501) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
        ... 11 more

**Comment by MehVahdJukaar** [comment]
What a weird error. So not me nor vanilla add that getViewers method. If I did mod wouldn't have compiled with an abstract method like that. It must be some mod doing something weird, likely some coremodding with ASM or maybe mixins. Thing is there's no way to tell which. Try any optimization mod or stuff that alters block entity. This is an issue on their side
