### ISSUE TITLE
Crash on start-up, 1.19.2, Forge

### ISSUE THREAD

**Issue by Someaussie** [MehVahdJukaar/Supplementaries#693]
G'day hope all is well, Just installed supplementaries today and was met with a crash on startup.
Heres my log:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2023-07-06 10:45:34
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.1-universal.jar%23218!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.2.1-universal.jar%23218!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:604) ~[client-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1290) ~[client-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23213!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.1.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.mehvahdjukaar.supplementaries.forge.SupplementariesForgeClient.crashIfOptifineHasNukedForge(SupplementariesForgeClient.java:80) ~[supplementaries-1.19.2-2.3.20.jar%23205!/:?] {re:classloading}
-- MOD supplementaries --
Details:
	Mod File: /C:/Users/Sam/AppData/Roaming/.minecraft/mods/supplementaries-1.19.2-2.3.20.jar
	Failure message: Supplementaries (supplementaries) encountered an error during the sided_setup event phase
		java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'
	Mod Version: 1.19.2-2.3.20
	Mod Issue URL: https://github.com/MehVahdJukaar/Supplementaries/issues
	Exception message: java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'
Stacktrace:
	at net.mehvahdjukaar.supplementaries.forge.SupplementariesForgeClient.crashIfOptifineHasNukedForge(SupplementariesForgeClient.java:80) ~[supplementaries-1.19.2-2.3.20.jar%23205!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.forge.SupplementariesForgeClient.init(SupplementariesForgeClient.java:30) ~[supplementaries-1.19.2-2.3.20.jar%23205!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.forge.__SupplementariesForgeClient_init_FMLClientSetupEvent.invoke(.dynamic) ~[supplementaries-1.19.2-2.3.20.jar%23205!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.2.1.jar%23215!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.2-43.2.1.jar%23214!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 644149432 bytes (614 MiB) / 1308622848 bytes (1248 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1740
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30662.15
	Virtual memory used (MB): 14458.59
	Swap memory total (MB): 14336.00
	Swap memory used (MB): 125.20
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.19.2_HD_U_H9
	OptiFine Build: 20220820-230904
	Render Distance Chunks: 18
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 517.40
	OpenGlRenderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.1.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.1.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.1.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.1.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.1.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Grappling-Hook-Mod-Forge-1.19.2.jar               |Grappling Hook Mod            |grapplemod                    |1.19.2-v13          |ENQUEUE_IM|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.2-2.0.1.128.jar           |TerraBlender                  |terrablender                  |2.0.1.128           |ENQUEUE_IM|Manifest: NOSIGNATURE
		moonlight-1.19.2-2.2.43-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.2.43       |ENQUEUE_IM|Manifest: NOSIGNATURE
		Cucumber-1.19.2-6.0.3.jar                         |Cucumber Library              |cucumber                      |6.0.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Mutant-Monsters-Mod-Forge-1.19.2.jar              |Mutant Monsters               |mutantmonsters                |4.0.1               |ENQUEUE_IM|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		cgm-1.3.1-1.19.2.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.3.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		BiomesOPlenty-1.19.2-17.1.1.162.jar               |Biomes O' Plenty              |biomesoplenty                 |17.1.1.162          |ENQUEUE_IM|Manifest: NOSIGNATURE
		Villagers-Drop-Emeralds-on-Death-Mod-Forge-1.19.2.|Villagers Drop Emeralds on Dea|villagerdrops                 |1.2.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		torojimaBuildHelper-3.6.0.0.jar                   |Torojima's Buildhelper        |buildhelper                   |3.6.0.0             |ENQUEUE_IM|Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.4.0.288.jar                   |Just Enough Items             |jei                           |11.4.0.288          |ENQUEUE_IM|Manifest: NOSIGNATURE
		OldCombatMod_1.19.2.jar                           |Old Combat Mod                |old_combat_mod                |1.1                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		IronJetpacks-1.19.2-6.0.3.jar                     |Iron Jetpacks                 |ironjetpacks                  |6.0.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Waystones-Mod-Forge-1.19.2.jar                    |Waystones                     |waystones                     |11.1.0              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Age-of-Weapons-Mod-Forge-1.19.2.jar               |Age of Weapons - Reforged     |ageofweapons                  |0.7.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Golems-Are-Friends-Not-Fodder-Mod-1.19.2.jar      |Golems Are Friends Not Fodder |golemsarefriends              |1.19.2-0.1.0.1      |ENQUEUE_IM|Manifest: NOSIGNATURE
		Double-Slabs-Mod-Forge-1.19.2.jar                 |Double Slabs                  |doubleslabs                   |6.1.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		worldedit-mod-7.2.12.jar                          |WorldEdit                     |worldedit                     |7.2.12+6240-87f4ae1 |ENQUEUE_IM|Manifest: NOSIGNATURE
		cfm-7.0.0-pre34-1.19.jar                          |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre34         |ENQUEUE_IM|Manifest: NOSIGNATURE
		architectury-6.4.62-forge.jar                     |Architectury                  |architectury                  |6.4.62              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Helpful-Wizards-Mod-Forge-1.19.2.jar              |Helpful Wizards               |helpfulwizards                |1.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Mahou-Tsukai-Mod-Forge-1.19.2.jar                 |Mahou Tsukai                  |mahoutsukai                   |1.19.1-v1.34.32     |ENQUEUE_IM|Manifest: NOSIGNATURE
		balm-4.5.3.jar                                    |Balm                          |balm                          |4.5.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		PuzzlesLib-v4.4.3-1.19.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |4.4.3               |ENQUEUE_IM|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		framework-0.4.2-1.19.2.jar                        |Framework                     |framework                     |0.4.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.19.2-43.2.1-universal.jar                 |Forge                         |forge                         |43.2.1              |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		VanillaTweaks-forge-1.19.2-1.5.65.jar             |VanillaTweaks                 |vanillatweaks                 |1.5.65              |ENQUEUE_IM|Manifest: NOSIGNATURE
		dragonmounts-1.19.2-1.1.4a.jar                    |Dragon Mounts: Legacy         |dragonmounts                  |1.1.4a              |ENQUEUE_IM|Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.3.20.jar                 |Supplementaries               |supplementaries               |1.19.2-2.3.20       |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: c98a948b-9bfb-4480-9355-47af23bd8be5
	FML: 43.2
	Forge: net.minecraftforge:43.2.1

**Comment by MehVahdJukaar** [comment]
if you got optifine tou should know that it breaks forge
