### ISSUE TITLE
Game crashes when rendering a player holding a filled cage: "Pose stack not empty"

### ISSUE THREAD

**Issue by schmoozingwithjohnny** [MehVahdJukaar/Supplementaries#704]
Supplementaries Version: 1.19.2-2.3.17 
Forge Version: 43.2.14
MC Version: 1.19.2

The game crashes with 
```
java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.client.renderer.LevelRenderer.m_109588_(LevelRenderer.java:1430)
```
when a player is rendering another player holding a **cage** that is filled with an entity (in this case: a chicken).

Crash File:
[crash-2023-07-15_14.22.21-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12061423/crash-2023-07-15_14.22.21-client.txt)

**Comment by MehVahdJukaar** [comment]
this has never been reported before so its likely not a cage issue. some mod must be doing something unsafe in the render code not popping a pose stack. what was in that cage?

**Comment by schmoozingwithjohnny** [comment]
Just a plain old Minecraft Chicken.

I'm playing the FTB Direwolf20 1.19 Modpack

**Comment by MehVahdJukaar** [comment]
Is your mod version latest?

**Comment by Xelbayria** [comment]
Is this issue resolved with the latest mod version?  Please close this if this is unrelated to supplementaries or resolved.

**Comment by rocketboy351** [comment]
I'm unsure if this is the same issue, mite be. But me and a friend have been trying to play a modpack that I modified and where having fun until suddenly, no matter what we did, if he looked in my direct and rendered my character (I'm the one hosting) his game would crash and boot him immediately. I've spent the last several hours removing mods to attempt to fix it. But they all follow the same pattern as the error log shown here. I've got 6 different crash logs from his end. Here is the most recent from the last attempt to figure out what mod was causing the crash. I can send the other 5 and potentially more if needed.
[crash-2024-01-08_18.34.03-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13868339/crash-2024-01-08_18.34.03-client.txt)

**Comment by DefinedAscent** [comment]
> I'm unsure if this is the same issue, mite be. But me and a friend have been trying to play a modpack that I modified and where having fun until suddenly, no matter what we did, if he looked in my direction and rendered my character (I'm the one hosting) his game would crash and boot him immediately. I've spent the last several hours removing mods to attempt to fix it. But they all follow the same pattern as the error log shown here. I've got 6 different crash logs from his end. Here is the most recent from the last attempt to figure out what mod was causing the crash. I can send the other 5 and potentially more if needed. [crash-2024-01-08_18.34.03-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13868339/crash-2024-01-08_18.34.03-client.txt)
> 
> (Edit) Sorry this is my first time actually writing one of these, required header information:
> 
> Supplementaries Version: 1.19.2-2.4.13 Forge Version: 43.3.5 MC Version: 1.19.2
> 
> java.lang.IllegalStateException: Pose stack not empty at net.minecraft.client.renderer.LevelRenderer.m_109588_(LevelRenderer.java:1430)
> 
> Crashes when loading another player. Holding item does not seem to be a requirement, rendering the player alone seems to be enough to cause the crash. I specifically went to the effort of removing all items from my character to the point of using /kill to completely wipe my character of all items or effects, with no effect and my friend still crashing the moment my character was rendered on their end.

Experiencing the exact same issue. Did you ever figure it out?

**Comment by MehVahdJukaar** [comment]
That must be because some other mod is doing unsafe stuff in mob render code, more specifically pushing to posestack without popping later in a position where it's safe to do so. No way to see what could cause that from the log

**Comment by meeprdib** [comment]
Mod versions on 1.19.2 and below are not supported
