### ISSUE TITLE
Failed to generate hanging sign extension texture for ___

### ISSUE THREAD

**Issue by Jamalam360** [MehVahdJukaar/Supplementaries#705]
Big log: https://mclo.gs/PLQBoaH

Lots of instances of this:

```
[17:36:43] [Render thread/WARN]: Failed to generate hanging sign extension texture for ad_astra:glacian,
--
2864 | java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4730.method_24147()" because the return value of "net.minecraft.class_4722.method_45781(net.minecraft.class_4719)" is null
2865 | at net.mehvahdjukaar.supplementaries.dynamicpack.ClientDynamicResourcesGenerator.regenerateDynamicAssets(ClientDynamicResourcesGenerator.java:238) ~[transformed-mod-supplementaries.i0:0/:?]
2866 | at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.reloadResources(DynResourceGenerator.java:117) ~[transformed-mod-moonlight.i0:0/:?]
2867 | at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.onEarlyReload(DynResourceGenerator.java:85) ~[transformed-mod-moonlight.i0:0/:?]
2868 | at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.lambda$postEvent$1(MoonlightEventsHelperImpl.java:27) ~[transformed-mod-moonlight.i0:0/:?]
2869 | at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
2870 | at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:27) ~[transformed-mod-moonlight.i0:0/:?]
2871 | at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[transformed-mod-moonlight.i0:0/:?]
2872 | at net.minecraft.class_6861.handler$boh000$moonlight$dynamicPackEarlyReload(class_6861.java:2034) ~[transformed-mod-minecraft.i0:0/:?]
2873 | at net.minecraft.class_6861.<init>(class_6861.java:60) ~[transformed-mod-minecraft.i0:0/:?]
2874 | at net.minecraft.class_3304.method_18232(class_3304.java:46) ~[transformed-mod-minecraft.i0:0/:?]
2875 | at net.minecraft.class_310.<init>(class_310.java:652) ~[transformed-mod-minecraft.i0:0/:?]
2876 | at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
```

Hopefully just a null check can solve this log spam.

**Comment by Jamalam360** [comment]
In the same log there's also

```
[17:41:59] [Worker-ResourceReload-16/ERROR]: Couldn't parse element loot_tables:supplementaries:blocks/candle_holder_spectacle
--
3090 | java.lang.IllegalArgumentException: Can't find block supplementaries:candle_holder_spectacle
```

**Comment by MehVahdJukaar** [comment]
loot table is normal and harmless. the one above is because some mod didnt register their wood type properly
