### ISSUE TITLE
Quilt Crash

### ISSUE THREAD

**Issue by lostopkk** [MehVahdJukaar/Supplementaries#716]
Minecraft 1.20.1 / Supplementaries 2.5.21 / Quilt-loader / Crash when Initialize
https://mclo.gs/eIIo3Em

Another crash recent: https://mclo.gs/LobdZ1C

**Comment by EduardoJauch** [comment]
Confirm the crash. From my crash report, the relevant bits:

`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'supplementaries'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
**Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/model/loading/v1/ModelLoadingPlugin
	at net.mehvahdjukaar.moonlight.api.platform.fabric.ClientHelperImpl.addSpecialModelRegistration(ClientHelperImpl.java:173)**
	at net.mehvahdjukaar.moonlight.api.platform.ClientHelper.addSpecialModelRegistration(ClientHelper.java)
	at net.mehvahdjukaar.supplementaries.reg.ClientRegistry.init(ClientRegistry.java:115)
	at net.mehvahdjukaar.supplementaries.fabric.SupplementariesFabricClient.init(SupplementariesFabricClient.java:20)
	at net.mehvahdjukaar.supplementaries.fabric.SupplementariesFabric.onInitialize(SupplementariesFabric.java:25)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 15 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.model.loading.v1.ModelLoadingPlugin
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:178)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 23 more`

**Comment by EduardoJauch** [comment]
On my case, i don't use Fabric API (nor will use it). Quild API should be compatible, so I will check with the team if there is a new Fabric API the QUilt API is not yet compatible (but will be), or if they diverge in a way that it is not possible to use this mod anymore (what is a shame, but I will not use Fabric).  Thanks for the answer.
