### ISSUE TITLE
[1.16.X] Crash when using Configured 1.1.0 and above

### ISSUE THREAD

**Issue by MrCrayfish** [MehVahdJukaar/Supplementaries#73]
I've recently published a new update to Configured (1.1.0), which has reportedly broken this mod.
https://github.com/MrCrayfish/Configured/issues/13

Crash report that I generated:
```java
java.lang.NoSuchMethodError: com.mrcrayfish.configured.client.screen.ConfigScreen.<init>(Lnet/minecraft/client/gui/screen/Screen;Ljava/lang/String;Lnet/minecraftforge/common/ForgeConfigSpec;Lnet/minecraftforge/common/ForgeConfigSpec;Lnet/minecraft/util/ResourceLocation;)V
	at net.mehvahdjukaar.supplementaries.compat.configured.ConfiguredCustomScreen.<init>(ConfiguredCustomScreen.java:110) ~[?:1.16.5-0.13.0] {re:classloading}
	at net.mehvahdjukaar.supplementaries.compat.configured.ConfiguredCustomScreen.lambda$null$0(ConfiguredCustomScreen.java:103) ~[?:1.16.5-0.13.0] {re:classloading}
	at net.mehvahdjukaar.supplementaries.compat.configured.ConfiguredCustomScreen$$Lambda$4968/326187802.apply(Unknown Source) ~[?:?] {}
	at com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.lambda$null$4(CatalogueModListScreen.java:122) ~[?:1.2.1-1.16.5] {re:classloading}
	at com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen$$Lambda$5461/744838086.apply(Unknown Source) ~[?:?] {}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
	at com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.lambda$init$6(CatalogueModListScreen.java:122) ~
        ...
```

**Comment by MrCrayfish** [comment]
I should point out that background support is built into the mod now.

**Comment by MehVahdJukaar** [comment]
Yeah I forgot to update the mod after you updated it. I'll push an update straight away. I've made my custom code a bit more robust and this time it should accept older and newer version (by just failing and using your default generated screen)
I have to say that the new support for multiple config specs is really cool!
Thanks again for the amazing mod!
