### ISSUE TITLE
Crashes on Mods loading (MC 1.19.2 || FML 43.2.0 || Supplementaries 2.3.24)

### ISSUE THREAD

**Issue by tylermav** [MehVahdJukaar/Supplementaries#752]
### Crashes during Mod Loading

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/23145429/98811b16-4356-4b01-9358-6e865a1f4dce)

### Error at fault  

> Exception message: java.lang.ClassNotFoundException: vazkii.quark.content.tools.item.PathfindersQuillItem

### LOGS
```

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD supplementaries --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {re:mixin}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23597!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23596!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.NoClassDefFoundError: vazkii/quark/content/tools/item/PathfindersQuillItem
		at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
		at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
		at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
		at net.mehvahdjukaar.supplementaries.integration.forge.QuarkCompatImpl.<clinit>(QuarkCompatImpl.java:94) ~[supplementaries-1.19.2-2.3.24.jar%23564!/:?] {re:classloading}
		at net.mehvahdjukaar.supplementaries.integration.QuarkCompat.init(QuarkCompat.java) ~[supplementaries-1.19.2-2.3.24.jar%23564!/:?] {re:mixin,re:classloading}
		at net.mehvahdjukaar.supplementaries.integration.CompatHandler.initOptionalRegistries(CompatHandler.java:83) ~[supplementaries-1.19.2-2.3.24.jar%23564!/:?] {re:mixin,re:classloading}
		at net.mehvahdjukaar.supplementaries.reg.ModRegistry.init(ModRegistry.java:48) ~[supplementaries-1.19.2-2.3.24.jar%23564!/:?] {re:mixin,re:classloading}
		at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:77) ~[supplementaries-1.19.2-2.3.24.jar%23564!/:?] {re:mixin,re:classloading}
		at net.mehvahdjukaar.supplementaries.forge.SupplementariesForge.<init>(SupplementariesForge.java:40) ~[supplementaries-1.19.2-2.3.24.jar%23564!/:?] {re:classloading,re:mixin}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {re:mixin}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23597!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23596!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/board/AppData/Roaming/.minecraft/mods/supplementaries-1.19.2-2.3.24.jar
	Failure message: Supplementaries (supplementaries) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.19.2-2.3.24
	Mod Issue URL: https://github.com/MehVahdJukaar/Supplementaries/issues
	Exception message: java.lang.ClassNotFoundException: vazkii.quark.content.tools.item.PathfindersQuillItem
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at net.mehvahdjukaar.supplementaries.integration.forge.QuarkCompatImpl.<clinit>(QuarkCompatImpl.java:94) ~[supplementaries-1.19.2-2.3.24.jar%23564!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.integration.QuarkCompat.init(QuarkCompat.java) ~[supplementaries-1.19.2-2.3.24.jar%23564!/:?] {re:mixin,re:classloading}
	at net.mehvahdjukaar.supplementaries.integration.CompatHandler.initOptionalRegistries(CompatHandler.java:83) ~[supplementaries-1.19.2-2.3.24.jar%23564!/:?] {re:mixin,re:classloading}
	at net.mehvahdjukaar.supplementaries.reg.ModRegistry.init(ModRegistry.java:48) ~[supplementaries-1.19.2-2.3.24.jar%23564!/:?] {re:mixin,re:classloading}
	at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:77) ~[supplementaries-1.19.2-2.3.24.jar%23564!/:?] {re:mixin,re:classloading}
	at net.mehvahdjukaar.supplementaries.forge.SupplementariesForge.<init>(SupplementariesForge.java:40) ~[supplementaries-1.19.2-2.3.24.jar%23564!/:?] {re:classloading,re:mixin}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {re:mixin}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23597!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23596!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

```

**Comment by tylermav** [comment]
Nvm resolved it.

Had to update my quark to the most recent version
