### ISSUE TITLE
Using a Faucet crashes the game on Fabric 1.20.1

### ISSUE THREAD

**Issue by GuardianWorld** [MehVahdJukaar/Supplementaries#758]
Crash Report: Ticking Block Entity

[11:51:06] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 27 out of bounds for length 27
	at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?]
	at net.minecraft.class_2371.get(class_2371.java:47) ~[server-intermediary.jar:?]
	at net.minecraft.class_2621.method_5438(class_2621.java:100) ~[server-intermediary.jar:?]
	at net.mehvahdjukaar.supplementaries.common.utils.fabric.ItemsUtilImpl.tryExtractingItem(ItemsUtilImpl.java:73) ~[supplementaries-1.20-2.5.21-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.utils.ItemsUtil.tryExtractingItem(ItemsUtil.java) ~[supplementaries-1.20-2.5.21-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.block.faucet.ContainerItemInteraction.tryExtractItem(ContainerItemInteraction.java:16) ~[supplementaries-1.20-2.5.21-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.block.tiles.FaucetBlockTile.tryExtract(FaucetBlockTile.java:161) ~[supplementaries-1.20-2.5.21-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.block.tiles.FaucetBlockTile.tick(FaucetBlockTile.java:93) ~[supplementaries-1.20-2.5.21-fabric.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:470) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:390) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
	... 5 more

Fabric 1.20.1 - 2.5.21

How to replicate: Placing a faucet and trying to open it crashes the game

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/12487327/latest.log)

**Comment by GuardianWorld** [comment]
I don't know if it helps, but the Faucet was connected to a Vanilla Barrel

**Comment by MehVahdJukaar** [comment]
Are you using latest version?

**Comment by MehVahdJukaar** [comment]
Ah hmm thought I fixed this

**Comment by GuardianWorld** [comment]
This is fixed on latest version... i'm sorry for opening the thread and forgetting to update...
