### ISSUE TITLE
[1.20.1 Quilt] Game crashes when using Supplementaries + Every Compat + QSL

### ISSUE THREAD

**Issue by Aninuscsalas** [MehVahdJukaar/Supplementaries#759]
Game crashes when using Supplementaries + Every Compat + QSL.
When using Fabric API this doesn't happen.

**Crash with QSL**
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'supplementaries'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.IllegalStateException: Tried to register resource reloader moonlight:mods_dynamic_assets twice!
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.registerReloader(ResourceLoaderImpl.java:160)
	at net.fabricmc.fabric.impl.resource.loader.ResourceManagerHelperImpl.registerReloadListener(ResourceManagerHelperImpl.java:50)
	at net.mehvahdjukaar.moonlight.api.platform.fabric.ClientHelperImpl.addClientReloadListener(ClientHelperImpl.java:133)
	at net.mehvahdjukaar.moonlight.api.platform.ClientHelper.addClientReloadListener(ClientHelper.java)
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynClientResourcesGenerator.register(DynClientResourcesGenerator.java:35)
	at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:96)
	at net.mehvahdjukaar.supplementaries.fabric.SupplementariesFabric.onInitialize(SupplementariesFabric.java:17)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 15 more

```

**Full Logs**
- QSL: https://mclo.gs/ucme2Tq
- Fabric API: https://mclo.gs/CgduRVv

**Mod versions**
- Moonlight 1.20-2.8.13-fabric
- Supplementaries 1.20-2.5.28
- everycomp 1.20-2.6.3
- QSL 7.1.2+0.87.0-1.20.1
- fabric-api 0.87.0 1.20.1

**Comment by MehVahdJukaar** [comment]
Try using new moonlight verison

**Comment by Aninuscsalas** [comment]
thx now its fixed
