### ISSUE TITLE
Minecraft game crash 1.20.1 FORGE

### ISSUE THREAD

**Issue by cherryomfg** [MehVahdJukaar/Supplementaries#786]
---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-09-29 22:32:17
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.1.44-universal.jar%23225!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:143) ~[forge-1.20.1-47.1.44-universal.jar%23225!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:583) ~[client-1.20.1-20230612.114412-srg.jar%23220!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.1.44-universal.jar%23225!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1380) ~[client-1.20.1-20230612.114412-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:ad_astra-common.mixins.json:client.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[Forge%201.20.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.4.jar%2393!/:?] {}
-- MOD supplementaries --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.44.jar%23222!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.44.jar%23221!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.ExceptionInInitializerError
		at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:51) ~[supplementaries-1.20-2.6.3.jar%23215!/:?] {re:classloading}
		at net.mehvahdjukaar.supplementaries.forge.SupplementariesForge.<init>(SupplementariesForge.java:34) ~[supplementaries-1.20-2.6.3.jar%23215!/:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.44.jar%23222!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.44.jar%23221!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 2: net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigSpecWrapper$ConfigLoadingException: Failed loading config file supplementaries-common.toml of type COMMON for modid supplementaries. Try deleting it
		at net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigSpecWrapper.loadFromFile(ConfigSpecWrapper.java:113) ~[moonlight-1.20-2.8.31-forge.jar%23207!/:?] {re:classloading}
		at net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigSpecWrapper.<init>(ConfigSpecWrapper.java:80) ~[moonlight-1.20-2.8.31-forge.jar%23207!/:?] {re:classloading}
		at net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigBuilderImpl.build(ConfigBuilderImpl.java:51) ~[moonlight-1.20-2.8.31-forge.jar%23207!/:?] {re:classloading}
		at net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigBuilderImpl.build(ConfigBuilderImpl.java:23) ~[moonlight-1.20-2.8.31-forge.jar%23207!/:?] {re:classloading}
		at net.mehvahdjukaar.moonlight.api.platform.configs.ConfigBuilder.buildAndRegister(ConfigBuilder.java:53) ~[moonlight-1.20-2.8.31-forge.jar%23207!/:?] {re:classloading}
		at net.mehvahdjukaar.supplementaries.configs.CommonConfigs.<clinit>(CommonConfigs.java:55) ~[supplementaries-1.20-2.6.3.jar%23215!/:?] {re:classloading}
		at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:51) ~[supplementaries-1.20-2.6.3.jar%23215!/:?] {re:classloading}
		at net.mehvahdjukaar.supplementaries.forge.SupplementariesForge.<init>(SupplementariesForge.java:34) ~[supplementaries-1.20-2.6.3.jar%23215!/:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.44.jar%23222!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.44.jar%23221!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/admin/AppData/Roaming/.tlauncher/legacy/Minecraft/game/mods/supplementaries-1.20-2.6.3.jar
	Failure message: Supplementaries (supplementaries) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.20-2.6.3
	Mod Issue URL: https://github.com/MehVahdJukaar/Supplementaries/issues
	Exception message: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
Stacktrace:
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.4.jar%2393!/:?] {}
	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36) ~[core-3.6.4.jar%2393!/:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49) ~[core-3.6.4.jar%2393!/:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123) ~[core-3.6.4.jar%2393!/:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166) ~[toml-3.6.4.jar%2394!/:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) ~[toml-3.6.4.jar%2394!/:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.4.jar%2394!/:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.4.jar%2394!/:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.4.jar%2394!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.4.jar%2393!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.4.jar%2393!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.4.jar%2393!/:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.4.jar%2393!/:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.4.jar%2393!/:?] {}
	at net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigSpecWrapper.readConfig(ConfigSpecWrapper.java:132) ~[moonlight-1.20-2.8.31-forge.jar%23207!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigSpecWrapper.loadFromFile(ConfigSpecWrapper.java:107) ~[moonlight-1.20-2.8.31-forge.jar%23207!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigSpecWrapper.<init>(ConfigSpecWrapper.java:80) ~[moonlight-1.20-2.8.31-forge.jar%23207!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigBuilderImpl.build(ConfigBuilderImpl.java:51) ~[moonlight-1.20-2.8.31-forge.jar%23207!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.platform.configs.forge.ConfigBuilderImpl.build(ConfigBuilderImpl.java:23) ~[moonlight-1.20-2.8.31-forge.jar%23207!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.platform.configs.ConfigBuilder.buildAndRegister(ConfigBuilder.java:53) ~[moonlight-1.20-2.8.31-forge.jar%23207!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.configs.CommonConfigs.<clinit>(CommonConfigs.java:55) ~[supplementaries-1.20-2.6.3.jar%23215!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:51) ~[supplementaries-1.20-2.6.3.jar%23215!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.forge.SupplementariesForge.<init>(SupplementariesForge.java:34) ~[supplementaries-1.20-2.6.3.jar%23215!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.44.jar%23222!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.44.jar%23221!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1651180800 bytes (1574 MiB) / 2147483648 bytes (2048 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1660
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2184
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 16335.05
	Virtual memory used (MB): 9021.17
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 121.80
	JVM Flags: 13 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Xms2048M -Xmx6144M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss2M
	OptiFine Version: OptiFine_1.20.1_HD_U_I6_pre6
	OptiFine Build: 20230727-130058
	Render Distance Chunks: 64
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryUnbound_r5.0.1.zip
	OpenGlVersion: 4.6.0 NVIDIA 531.79
	OpenGlRenderer: NVIDIA GeForce GTX 1660/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.1.1-mc1.20.1forge.jar               |Macaw's Bridges               |mcwbridges                    |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		BorderlessWindow-1.20-1.6.0 (1).jar               |Borderless Window             |borderlesswindow              |1.20-1.6.0          |COMMON_SET|Manifest: NOSIGNATURE
		TreeChop-1.20.1-forge-0.18.3.jar                  |HT's TreeChop                 |treechop                      |0.18.3              |COMMON_SET|Manifest: NOSIGNATURE
		Tropicraft-9.6.2.jar                              |Tropicraft                    |tropicraft                    |9.6.2               |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.0.169.jar           |TerraBlender                  |terrablender                  |3.0.0.169           |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.20-2.8.31-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.8.31         |COMMON_SET|Manifest: NOSIGNATURE
		spider (2).jar                                    |Spider-Man Mod                |spiderman_mod                 |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.2.2.jar                   |GeckoLib 4                    |geckolib                      |4.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.10.34_mc1.20.1 (1).jar      |CreativeCore                  |creativecore                  |2.10.34             |COMMON_SET|Manifest: NOSIGNATURE
		botarium-forge-1.20.1-2.2.0 (1).jar               |Botarium                      |botarium                      |2.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |COMMON_SET|Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.20.1-2.1.0 (1).jar      |Resourcefulconfig             |resourcefulconfig             |2.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		caelus-forge-3.1.0+1.20 (1).jar                   |Caelus API                    |caelus                        |3.1.0+1.20          |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-5.2.0-beta.3+1.20.1 (1).jar          |Curios API                    |curios                        |5.2.0-beta.3+1.20.1 |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.20.1-81-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-81-FORGE     |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.4.2-1.20.1.jar                          |Citadel                       |citadel                       |2.4.2               |COMMON_SET|Manifest: NOSIGNATURE
		NaturesCompass-1.20.1-1.11.2-forge.jar            |Nature's Compass              |naturescompass                |1.20.1-1.11.2-forge |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.8.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.8        |COMMON_SET|Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.10.jar            |Resourceful Lib               |resourcefullib                |2.1.10              |COMMON_SET|Manifest: NOSIGNATURE
		Butchersdelightbeta1.20.12.0.3.jar                |ButchersDelight               |butchersdelight               |1.20.12.0.3         |COMMON_SET|Manifest: NOSIGNATURE
		simpleplanes-1.20.1-5.2.3 (1).jar                 |Simple Planes                 |simpleplanes                  |1.20.1-5.2.3        |COMMON_SET|Manifest: NOSIGNATURE
		cfm-forge-1.20.1-7.0.0-pre36 (1).jar              |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre36         |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		ItemPhysic_FORGE_v1.6.11_mc1.20.1.jar             |ItemPhysic                    |itemphysic                    |1.6.11              |COMMON_SET|Manifest: NOSIGNATURE
		nfm-2023.08.15-1.20.1.jar                         |Nosiphus Furniture Mod        |nfm                           |2023.08.15          |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.1.44-universal.jar                |Forge                         |forge                         |47.1.44             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Disenchanting-forge-1.20.1-2.2.4.jar              |Disenchanting                 |disenchanting                 |2.2.3               |COMMON_SET|Manifest: NOSIGNATURE
		twilightforest-1.20.1-4.3.1809-universal.jar      |The Twilight Forest           |twilightforest                |4.3.1809            |COMMON_SET|Manifest: NOSIGNATURE
		supplementaries-1.20-2.6.3.jar                    |Supplementaries               |supplementaries               |1.20-2.6.3          |ERROR     |Manifest: NOSIGNATURE
		DivineRPG-1.10.6.jar                              |DivineRPG                     |divinerpg                     |1.10.6              |COMMON_SET|Manifest: NOSIGNATURE
		ironchest-1.20.1-14.4.4 (1).jar                   |Iron Chests                   |ironchest                     |1.20.1-14.4.4       |COMMON_SET|Manifest: NOSIGNATURE
		mcw-lights-1.0.6-mc1.20.1forge.jar                |Macaw's Lights and Lamps      |mcwlights                     |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		DungeonsArise-1.20.1-2.1.56.1-beta.jar            |When Dungeons Arise           |dungeons_arise                |2.1.56.1-1.20.1     |COMMON_SET|Manifest: NOSIGNATURE
		ad_astra-forge-1.20.1-1.15.3 (1).jar              |Ad Astra                      |ad_astra                      |1.15.3              |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 4ccf0b40-1cc0-4afc-8765-6d883fd7cdce
	FML: 47.1
	Forge: net.minecraftforge:47.1.44

**Comment by cherryomfg** [comment]
im tryna update moonlight and supplementaries but its didnt work

**Comment by MehVahdJukaar** [comment]
your config files got corrupted. delete them

**Comment by cherryomfg** [comment]
> your config files got corrupted. delete them

where i can find him

**Comment by MehVahdJukaar** [comment]
Configs folder

**Comment by cherryomfg** [comment]
thank you its worked
