### ISSUE TITLE
[1.20.1 - Fabric] Game crashes when using REI

### ISSUE THREAD

**Issue by memoharos** [MehVahdJukaar/Supplementaries#791]
First of all, this mod is awesome. I used it with forge with no incidents. But now I am playing in fabric version using REI for recipes and the game crashes when I navigate in recipes. The log is:

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at net.mehvahdjukaar.moonlight.api.client.model.fabric.BakedQuadBuilderImpl.<init>(BakedQuadBuilderImpl.java:38)
	at net.mehvahdjukaar.moonlight.api.client.model.fabric.BakedQuadBuilderImpl.create(BakedQuadBuilderImpl.java:26)
	at net.mehvahdjukaar.moonlight.api.client.model.BakedQuadBuilder.create(BakedQuadBuilder.java)
	at net.mehvahdjukaar.moonlight.api.client.model.BakedQuadBuilder.create(BakedQuadBuilder.java:22)
	at net.mehvahdjukaar.supplementaries.client.renderers.items.AltimeterItemRenderer$AltimeterModel.<init>(AltimeterItemRenderer.java:111)
	at net.mehvahdjukaar.supplementaries.client.renderers.items.AltimeterItemRenderer.lambda$renderByItem$0(AltimeterItemRenderer.java:67)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:448)
	at net.mehvahdjukaar.supplementaries.client.renderers.items.AltimeterItemRenderer.method_3166(AltimeterItemRenderer.java:66)
	at net.mehvahdjukaar.moonlight.api.client.ItemStackRenderer.render(ItemStackRenderer.java:524)
	at net.minecraft.class_756.handler$bdn000$fabric-rendering-v1$fabric_onRender(class_756.java:541)
	at net.minecraft.class_756.method_3166(class_756.java)
	at net.minecraft.class_918.method_23179(class_918.java:126)
	at net.minecraft.class_332.method_51425(class_332.java:531)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51428(class_332.java:495)
	at net.minecraft.class_465.method_2385(class_465.java:249)
	at net.minecraft.class_465.method_25394(class_465.java:115)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_481.method_25394(class_481.java:722)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.mehvahdjukaar.moonlight.api.client.model.fabric.BakedQuadBuilderImpl.<init>(BakedQuadBuilderImpl.java:38)
	at net.mehvahdjukaar.moonlight.api.client.model.fabric.BakedQuadBuilderImpl.create(BakedQuadBuilderImpl.java:26)
	at net.mehvahdjukaar.moonlight.api.client.model.BakedQuadBuilder.create(BakedQuadBuilder.java)
	at net.mehvahdjukaar.moonlight.api.client.model.BakedQuadBuilder.create(BakedQuadBuilder.java:22)
	at net.mehvahdjukaar.supplementaries.client.renderers.items.AltimeterItemRenderer$AltimeterModel.<init>(AltimeterItemRenderer.java:111)
	at net.mehvahdjukaar.supplementaries.client.renderers.items.AltimeterItemRenderer.lambda$renderByItem$0(AltimeterItemRenderer.java:67)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:448)
	at net.mehvahdjukaar.supplementaries.client.renderers.items.AltimeterItemRenderer.method_3166(AltimeterItemRenderer.java:66)
	at net.mehvahdjukaar.moonlight.api.client.ItemStackRenderer.render(ItemStackRenderer.java:524)
	at net.minecraft.class_756.handler$bdn000$fabric-rendering-v1$fabric_onRender(class_756.java:541)
	at net.minecraft.class_756.method_3166(class_756.java)
	at net.minecraft.class_918.method_23179(class_918.java:126)
	at net.minecraft.class_332.method_51425(class_332.java:531)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51428(class_332.java:495)
	at net.minecraft.class_465.method_2385(class_465.java:249)
	at net.minecraft.class_465.method_25394(class_465.java:115)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_481.method_25394(class_481.java:722)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Item being rendered --
Details:
	Item Type: altimeter
	Item Damage: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.class_332.method_51425(class_332.java:531)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51428(class_332.java:495)
	at net.minecraft.class_465.method_2385(class_465.java:249)
	at net.minecraft.class_465.method_25394(class_465.java:115)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_481.method_25394(class_481.java:722)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (241, 69). Absolute: (966.000000, 278.000000)
	Screen size: Scaled: (461, 253). Absolute: (1842, 1009). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['gharos21'/134, l='ClientLevel', x=-3.11, y=69.00, z=69.49]]
	Chunk stats: 1024, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,78,80), Section: (at 0,14,0 in 1,4,5; chunk contains blocks 16,-64,80 to 31,319,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 128122 game time, 36593 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Moonlight Mods Dynamic Assets

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-84-generic
	Java Version: 17.0.8.1, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 1857048576 bytes (1771 MiB) / 3460300800 bytes (3300 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x0412
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 9978.86
	Virtual memory used (MB): 9535.66
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms1024m -Xmx4096m
	Fabric Mods: 
		advancedcompass: Advanced Compass 1.2.15
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.20.1
		architectury: Architectury 9.1.12
		axesareweapons: Axes Are Weapons 1.7.1
		bagofholding: Bag Of Holding 8.0.0
			extensibleenums: Extensible Enums 7.0.1
			puzzlesapi: Puzzles Api 8.0.2
				puzzlesaccessapi: Puzzles Access Api 8.0.5
		balm-fabric: Balm 7.1.4
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.66
		compostbag: Compost Bag 2.0.0
		controllable: Controllable 0.20.2
			io_github_libsdl4j_libsdl4j: libsdl4j 2.26.4-1.2
		craftingcraft: Crafting Slots 16.0.0
		disenchantingfabric: Disenchanting 1.20.1-2.2.4a
		easymagic: Easy Magic 8.0.1
		enchantinginfuser: Enchanting Infuser 8.0.2
		enderzoology: Ender Zoology 8.0.1
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
		etcetera: Etcetera 1.1.2-fabric
		expandedstorage: Expanded Storage 10.0.0-beta.3
		fabric-api: Fabric API 0.89.3+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.11+0737cd8077
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.1+0889cb7877
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.22
		fallingleaves: Falling Leaves 1.15.3
		forgeconfigapiport: Forge Config API Port 8.0.0
		forgeconfigscreens: Forge Config Screens 8.0.2
		framework: Framework 0.6.16
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		hcreative: Battleaxes 1.0.0
		healthindicatortxf: Health Indicator TXF 1.20.1-1.1.2-fabric
			midnightlib: MidnightLib 1.4.1
		immersive_aircraft: Immersive Aircraft 0.6.2+1.20.1
		infinitetrading: Infinite Trading 4.0
		inventorio: Inventorio 1.9.2
		inventoryprofilesnext: Inventory Profiles Next 1.10.7
		java: OpenJDK 64-Bit Server VM 17
		libipn: libIPN 4.0.0
		map_atlases: Map Atlases 2.6.0
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.8.42
		notenoughcrashes: Not Enough Crashes 4.4.6+1.20.1
		overflowingbars: Overflowing Bars 8.0.0
		puzzleslib: Puzzles Lib 8.0.24
		replantingcrops: Replanting Crops 5.1
		roughlyenoughitems: Roughly Enough Items 12.0.665
			error_notifier: Error Notifier 1.0.9
		simplemagnets: Simple Magnets 1.1.9
		sodium: Sodium 0.5.3
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.14
		supplementaries: Supplementaries 1.20-2.6.7
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-rc.3
		tradingpost: Trading Post 8.0.1
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.5
		waystones: Waystones 14.0.2
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2) GL version 4.5 (Core Profile) Mesa 21.2.6, Intel Open Source Technology Center
	Window size: 1842x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: es_mx
	CPU: 4x Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['gharos21'/134, l='ServerLevel[Testera]', x=-3.11, y=69.00, z=69.49]]
	Data Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, Supplementaries Generated Pack, file/Battle Skills.zip, file/Better Loot.zip, file/Book Of Experience 3.1.0.zip, file/Fast Leaf Decay v2.0.7 (MC 1.20.x).zip, file/Homing Xp.zip, file/Multitool-v4.1.2.zip, file/Potion of Spelunking v2.1 1.19.zip (incompatible), file/dynamiclights-v1.7-mc1.17x-1.20x-datapack.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Rendering (v1) (fabric-rendering-v1), Fabric Loader (fabricloader), Moonlight (moonlight), Supplementaries (supplementaries)

**Comment by MehVahdJukaar** [comment]
Sodium issue. Sodium is incompatible with fabric api unles you use indium

**Comment by memoharos** [comment]
That's right. Installing Indium fixes the problem
Thanks
