### ISSUE TITLE
[🐞]: Newest version for 1.19.2 fails to load

### ISSUE THREAD

**Issue by SiverDX** [MehVahdJukaar/Supplementaries#817]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below

### Version-Loader

1.19.2-forge

### Supplementaries Version

1.19.2-2.4.0

### Moonlight Lib Version

1.19.2-2.3.3

### Issue Detail

```log
[03:11:58] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: supplementaries, class net.mehvahdjukaar.supplementaries.forge.SupplementariesForge
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.3.0.jar%23879!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.3.0.jar%23878!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?] {re:mixin}
Caused by: java.lang.NoSuchFieldError: KEY
	at net.mehvahdjukaar.supplementaries.common.misc.map_markers.ModMapMarkers.<clinit>(ModMapMarkers.java:44) ~[supplementaries-1.19.2-2.4.0.jar%23824!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:88) ~[supplementaries-1.19.2-2.4.0.jar%23824!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.forge.SupplementariesForge.<init>(SupplementariesForge.java:40) ~[supplementaries-1.19.2-2.4.0.jar%23824!/:?] {re:classloading,re:mixin}
	... 14 more
```

I checked the moonlight .jar and that field is indeed not present

**Comment by Xelbayria** [comment]
Please drag/attach a full log of the `latest.log` or `crash-report` here. FYI, a cropped part from the log doesn't help very much.

**Comment by SiverDX** [comment]
I read it and know enough / added a comment to explain what the errors is

**Comment by SiverDX** [comment]
No longer occurs in Supplementaries 1.19.2-2.4.1
