### ISSUE TITLE
[🐞]: Unclear cause of console freeze, Lootr-1.20-0.7.29.75 + Supplementaries (Lastest version)

### ISSUE THREAD

**Issue by PikouGame** [MehVahdJukaar/Supplementaries#829]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries-1.20-2.6.20-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.59-fabric

### Issue Detail

Hi, sorry for the bothering.I've been encountering a problem where supplementaries cause radomly my server console to freeze for an undetermined amount of time (I highly suspect chunk loading). 
After a month of troubleshooting with my players, we finally obtained the first crash logs related to the issue. From my analysis, it seems that supplementaries is encountering difficulties when generating something with a specific content. However, I'm struggling to comprehend the details of this error message. Lootr, a mod that generate chest for every single player is also being named in the logs.

The first file is the crash-log.
The second is the log file.

Thank you for your understanding, and I would greatly appreciate any assistance you can provide.

### Optional Attachment

[crash-2023-11-09_22.05.36-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13315163/crash-2023-11-09_22.05.36-server.txt)
[2023-11-09-4.log](https://github.com/MehVahdJukaar/Supplementaries/files/13315166/2023-11-09-4.log)

**Comment by MehVahdJukaar** [comment]
Try increasing server max tick time. I don't really know what's the real issue behind this because first of all that code should be executed off thread so should not affect tick time. Second  the issue description is the most vague I've see , it just says "watchdog"

**Comment by chopsoy** [comment]
Hello, just want to give some additional info for this issue. Our server also encountered this issue with the same stack trace in the stack log. After some investigation and backtracking our steps we realized that this issue happened when one of our players interacted (right-clicked) on a very specific chest (to open it). No chest dialog would open and the server would crash (after being killed by watchdog after 60 seconds of tick time).

The chest was located in a village with a two-storied building in it, on the second story. We had the admin fly around to generate several other chunks with the same building, and the chests in those buildings did not exhibit the same issue. I believe that whether or not the server crashes depends on the inventory of the chest (as it's being generated), but we have no way of verifying because we're unable to see the contents of the chest once the server crashes.

After poking around in this repository (with my limited knowledge of Minecraft modding), my *very naiive* guess is that [this file](https://github.com/MehVahdJukaar/Supplementaries/blob/72d879f56d3dc5e5c683f3473060be7703be33fd/common/src/main/resources/data/supplementaries/loot_tables/inject/test.json) was committed to the branch in mistake, and the loot table specified by this file may occasionally be involved as a part of chest loot generation, which may be somehow related to the frames in stack trace where Minecraft's vanilla source code invokes Supplementaries' AdventureMapHandler?

```
	at net.mehvahdjukaar.supplementaries.common.entities.trades.AdventurerMapsHandler.createMapOrQuill(AdventurerMapsHandler.java:161)
	at MC//net.minecraft.loot.function.ExplorationMapLootFunction.handler$hne000$supplementaries$turnToQuill(ExplorationMapLootFunction.java:563)
```

I don't have a copy of the decompiled vanilla Minecraft jar handy to debug further, so apologies if my speculation created is a false lead. Just wanted to provide additional info that may aid in debugging. Here's the server crash log on our side (very similar to OP's stack trace).

[crash-2023-12-28_02.54.42-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13783638/crash-2023-12-28_02.54.42-server.txt)
[crash-2023-12-28_03.09.28-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13783639/crash-2023-12-28_03.09.28-server.txt)
[crash-2023-12-28_04.00.22-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13783640/crash-2023-12-28_04.00.22-server.txt)

**Comment by MehVahdJukaar** [comment]
You are not using the latest version. This issue was resolved
