### ISSUE TITLE
[🐞]: [1.20.1] [Fabric] 2.6.29 crashes server due to newly introduced unchecked cast

### ISSUE THREAD

**Issue by cuteBoiButt** [MehVahdJukaar/Supplementaries#840]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

1.20-2.6.29

### Moonlight Lib Version

1.20-2.8.64

### Issue Detail

Latest changes to [BowMixin](https://github.com/MehVahdJukaar/Supplementaries/blob/1.20-back/fabric/src/main/java/net/mehvahdjukaar/supplementaries/mixins/fabric/BowMixin.java) and [CrossbowMixin](https://github.com/MehVahdJukaar/Supplementaries/blob/1.20-back/fabric/src/main/java/net/mehvahdjukaar/supplementaries/mixins/fabric/CrossbowMixin.java) in 2.6.29 introduced unchecked [cast]( https://github.com/MehVahdJukaar/Supplementaries/blob/66aa1fd19ae5092d2433951144097d222fb6483a/fabric/src/main/java/net/mehvahdjukaar/supplementaries/mixins/fabric/BowMixin.java#L25-L25) which crashes servers
note that method QuiverItem.getQuiver does proper type [checks](https://github.com/MehVahdJukaar/Supplementaries/blob/66aa1fd19ae5092d2433951144097d222fb6483a/fabric/src/main/java/net/mehvahdjukaar/supplementaries/common/items/fabric/QuiverItemImpl.java#L22) 

stacktraces look like this:
```
java.lang.ClassCastException: class fr.hugman.promenade.entity.SunkenSkeletonEntity cannot be cast to class net.minecraft.class_1657 (fr.hugman.promenade.entity.SunkenSkeletonEntity and net.minecraft.class_1657 are in unnamed module of l>
        at net.minecraft.class_1764.handler$fca000$supplementaries$shrinkQuiverArrow(class_1764.java:2024)
        at net.minecraft.class_1764.method_7765(class_1764.java:147)
        at net.minecraft.class_1764.method_7767(class_1764.java:131)
        at net.minecraft.class_1764.method_7840(class_1764.java:106)
        at net.minecraft.class_1799.method_7930(class_1799.java:508)
        at net.minecraft.class_1309.method_6075(class_1309.java:3169)
        at net.minecraft.class_1383.method_6268(class_1383.java:130)
        at net.minecraft.class_4135.method_6268(class_4135.java:65)
        at net.minecraft.class_1355.method_38849(class_1355.java:120)
        at net.minecraft.class_1308.method_6023(class_1308.java:779)
        at net.minecraft.class_1309.method_6007(class_1309.java:2673)
        at net.minecraft.class_1308.method_6007(class_1308.java:550)
        at net.minecraft.class_1588.method_6007(class_1588.java:44)
        at net.minecraft.class_1547.method_6007(class_1547.java:127)
        at net.minecraft.class_1309.method_5773(class_1309.java:2419)
        at net.minecraft.class_1308.method_5773(class_1308.java:351)
        at net.minecraft.class_3218.method_18762(class_3218.java:739)
        at net.minecraft.class_1937.method_18472(class_1937.java:480)
        at net.minecraft.class_3218.method_31420(class_3218.java:385)
        at net.minecraft.class_5574.method_31791(class_5574.java:54)
        at net.minecraft.class_3218.method_18765(class_3218.java:353)
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
        at net.minecraft.class_3176.method_3813(class_3176.java:283)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
        at java.base/java.lang.Thread.run(Thread.java:842)
```

**Comment by MehVahdJukaar** [comment]
erm thing is for crossbow one vanilla does the same unsafe cast implying that living entity has to be a player

**Comment by MehVahdJukaar** [comment]
fixd
