### ISSUE TITLE
Opening the Quiver UI boots clients from the server[🐞]: 

### ISSUE THREAD

**Issue by fruitmeister101** [MehVahdJukaar/Supplementaries#908]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-forge

### Supplementaries Version

supplementaries-1.20-2.6.20-fabric.jar

### Moonlight Lib Version

moonlight-1.20-2.8.57-fabric.jar

### Issue Detail

I didn't see any post regarding this issue.

Pressing the Quiver Interface key opens the quiver interface, and then 2 seconds later, the client is booted from the server.
This is running on a heavily modded server, and there could be conflict with other mods.
I also acknowledge that this server is not using the most up-to-date versions of stuff (waiting for all mods to update before transition).
If this has been solved already, I will notify my playerbase to be careful until I can update properly.

### Optional Attachment

Report from Server Console:

[20:09:01] [Server thread/INFO]: VrontimelThyella joined the game
[20:09:03] [Server thread/INFO]: [voicechat] Received secret request of VrontimelThyella (17)
[20:09:03] [Server thread/INFO]: [voicechat] Sent secret to VrontimelThyella
[20:09:03] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2102ms or 42 ticks behind
[20:09:05] [VoiceChatPacketProcessingThread/INFO]: [voicechat] Successfully authenticated player a2892c93-8519-4715-8e74-e760b1e84b79
[20:09:06] [VoiceChatPacketProcessingThread/INFO]: [voicechat] Successfully validated connection of player a2892c93-8519-4715-8e74-e760b1e84b79
[20:09:06] [VoiceChatPacketProcessingThread/INFO]: [voicechat] Player VrontimelThyella (a2892c93-8519-4715-8e74-e760b1e84b79) successfully connected to voice chat
[20:10:22] [Netty Epoll Server IO #2/ERROR]: Encountered exception while handling in channel with name "supplementaries:22"
java.lang.IndexOutOfBoundsException: readerIndex(2) + length(8) exceeds writerIndex(9): UnpooledSlicedByteBuf(ridx: 2, widx: 9, cap: 9/9, unwrapped: PooledUnsafeDirectByteBuf(ridx: 0, widx: 9, cap: 9))
at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.82.Final.jar:?]
at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[netty-buffer-4.1.82.Final.jar:?]
at net.minecraft.class_2540.readLong(class_2540.java:1373) ~[server-intermediary.jar:?]
at net.minecraft.class_2540.method_10790(class_2540.java:575) ~[server-intermediary.jar:?]
at net.mehvahdjukaar.supplementaries.common.network.PicklePacket.<init>(PicklePacket.java:32) ~[supplementaries-1.20-2.6.20-fabric.jar:?]
at net.mehvahdjukaar.moonlight.api.platform.network.fabric.ChannelHandlerImpl.lambda$register$1(ChannelHandlerImpl.java:62) ~[moonlight-1.20-2.8.57-fabric.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:85) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-cd9e8672463c95a.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:39) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-cd9e8672463c95a.jar:?]
at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-cd9e8672463c95a.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:80) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-cd9e8672463c95a.jar:?]
at net.minecraft.class_3244.handler$zpi000$fabric-networking-api-v1$handleCustomPayloadReceivedAsync(class_3244.java:2000) ~[server-intermediary.jar:?]
at net.minecraft.class_3244.method_12075(class_3244.java) ~[server-intermediary.jar:?]
at net.minecraft.class_2817.method_12199(class_2817.java:38) ~[server-intermediary.jar:?]
at net.minecraft.class_2817.method_11054(class_2817.java:7) ~[server-intermediary.jar:?]
at net.minecraft.class_2535.method_10759(class_2535.java:175) ~[server-intermediary.jar:?]
at net.minecraft.class_2535.method_10770(class_2535.java:160) ~[server-intermediary.jar:?]
at net.minecraft.class_2535.channelRead0(class_2535.java:52) ~[server-intermediary.jar:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
[20:10:22] [Netty Epoll Server IO #2/ERROR]: Exception occurred in netty pipeline
java.lang.IndexOutOfBoundsException: readerIndex(2) + length(8) exceeds writerIndex(9): UnpooledSlicedByteBuf(ridx: 2, widx: 9, cap: 9/9, unwrapped: PooledUnsafeDirectByteBuf(ridx: 0, widx: 9, cap: 9))
at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.82.Final.jar:?]
at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[netty-buffer-4.1.82.Final.jar:?]
at net.minecraft.class_2540.readLong(class_2540.java:1373) ~[server-intermediary.jar:?]
at net.minecraft.class_2540.method_10790(class_2540.java:575) ~[server-intermediary.jar:?]
at net.mehvahdjukaar.supplementaries.common.network.PicklePacket.<init>(PicklePacket.java:32) ~[supplementaries-1.20-2.6.20-fabric.jar:?]
at net.mehvahdjukaar.moonlight.api.platform.network.fabric.ChannelHandlerImpl.lambda$register$1(ChannelHandlerImpl.java:62) ~[moonlight-1.20-2.8.57-fabric.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:85) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-cd9e8672463c95a.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:39) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-cd9e8672463c95a.jar:?]
at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-cd9e8672463c95a.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:80) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-cd9e8672463c95a.jar:?]
at net.minecraft.class_3244.handler$zpi000$fabric-networking-api-v1$handleCustomPayloadReceivedAsync(class_3244.java:2000) ~[server-intermediary.jar:?]
at net.minecraft.class_3244.method_12075(class_3244.java) ~[server-intermediary.jar:?]
at net.minecraft.class_2817.method_12199(class_2817.java:38) ~[server-intermediary.jar:?]
at net.minecraft.class_2817.method_11054(class_2817.java:7) ~[server-intermediary.jar:?]
at net.minecraft.class_2535.method_10759(class_2535.java:175) ~[server-intermediary.jar:?]
at net.minecraft.class_2535.method_10770(class_2535.java:160) ~[server-intermediary.jar:?]
at net.minecraft.class_2535.channelRead0(class_2535.java:52) ~[server-intermediary.jar:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
[20:10:22] [Server thread/INFO]: VrontimelThyella lost connection: Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(8) exceeds writerIndex(9): UnpooledSlicedByteBuf(ridx: 2, widx: 9, cap: 9/9, unwrapped: PooledUnsafeDirectByteBuf(ridx: 0, widx: 9, cap: 9))
[20:10:22] [Server thread/INFO]: VrontimelThyella left the game
[20:10:22] [Server thread/INFO]: [voicechat] Disconnecting client VrontimelThyella
[20:11:25] [User Authenticator #2/INFO]: UUID of player VrontimelThyella is a2892c93-8519-4715-8e74-e760b1e84b79
[20:11:26] [Server thread/INFO]: VrontimelThyella[/104.153.125.238:51517] logged in with entity id 912 at (-635.263129507222, 107.0, -484.22979832228845)

Image of Client Screen:
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/79765028/2d55c410-dfbb-486b-bb80-00635bdc8a76)

**Comment by MehVahdJukaar** [comment]
that would point to server and client having mismatched mod version
