### ISSUE TITLE
[🐞]: Crashing with modpack

### ISSUE THREAD

**Issue by guangroove** [MehVahdJukaar/Supplementaries#926]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

1.20-2.7.32

### Moonlight Lib Version

1.20-2.9.9

### Issue Detail

voidz, waystones, wilderwild, woof, yaclx, yet_another_config_lib_v3, yigd), minecraft:supporteatinganimation, seasons:seasonal_lush_caves, Moonlight Mods Dynamic Assets, file/Stay_True_1.20.zip, file/FreshAnimations_v1.8.1.zip, file/Fresh-Dungeons-1.20.1.zip
[21:21:23] [Render thread/INFO]: [STDERR]: Java 10 memcpy enabled
[21:21:23] [Render thread/INFO]: Generated runtime CLIENT_RESOURCES for pack Moonlight Mods Dynamic Assets (immersive_weathering) in: 93 ms
[21:21:23] [Render thread/ERROR]: Failed to generate hanging sign extension texture for regions_unexplored:alpha. Could be that the target mod isnt registering their wood type properly
[21:21:23] [Render thread/INFO]: Generated runtime CLIENT_RESOURCES for pack Moonlight Mods Dynamic Assets (supplementaries) in: 111 ms
[21:21:23] [Worker-Main-3/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/block/old iron/iron_door_bottom.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/block/old iron/iron_door_top.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/block/old iron/iron_trapdoor.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/cool netherrite/netherite_axe.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/cool netherrite/netherite_boots.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/cool netherrite/netherite_chestplate.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/cool netherrite/netherite_helmet.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/cool netherrite/netherite_hoe.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/cool netherrite/netherite_leggings.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/cool netherrite/netherite_pickaxe.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/cool netherrite/netherite_shovel.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/cool netherrite/netherite_sword.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/cool netherrite/pack.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/cool netherrite/readme.txt, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/netherite no gold/netherite_boots.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/netherite no gold/netherite_chestplate.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/netherite no gold/netherite_helmet.png, ignoring
[21:21:24] [Worker-Main-9/WARN]: Invalid path in datapack: minecraft:textures/item/netherite no gold/netherite_leggings.png, ignoring
[21:21:24] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[21:21:24] [Worker-Main-10/WARN]: Texture geckolib:entity/creeper with size 64x40 limits mip level from 4 to 3
[21:21:24] [Worker-Main-10/WARN]: Texture wilderwild:entity/firefly/nectar with size 487x487 limits mip level from 3 to 0
[21:21:24] [Worker-Main-10/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 0, because of minimum power of two: 1
[21:21:24] [Render thread/INFO]: Starting custom uniform resolving
[21:21:25] [Worker-Main-8/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/cut_sandstone.json' in resourcepack: 'file/Stay_True_1.20.zip' for variant: 'axis=z': Unknown blockstate property: 'axis'
[21:21:25] [Worker-Main-8/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/cut_sandstone.json' in resourcepack: 'file/Stay_True_1.20.zip' for variant: 'axis=x': Unknown blockstate property: 'axis'
[21:21:25] [Worker-Main-8/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/cut_sandstone.json' in resourcepack: 'file/Stay_True_1.20.zip' for variant: 'axis=y': Unknown blockstate property: 'axis'
[21:21:28] [Render thread/WARN]: Error while parsing the block ID map entry for "block.10092":
[21:21:28] [Render thread/WARN]: - The block minecraft:stone has no property with the name variant, ignoring!
[21:21:28] [Render thread/WARN]: Error while parsing the block ID map entry for "block.10152":
[21:21:28] [Render thread/WARN]: - The block minecraft:stone_slab has no property with the name variant, ignoring!
[21:21:28] [Render thread/WARN]: Error while parsing the block ID map entry for "block.60016":
[21:21:28] [Render thread/WARN]: - The block minecraft:dragon_head has no property with the name powered, ignoring!
[21:21:28] [Render thread/WARN]: Error while parsing the block ID map entry for "block.10240":
[21:21:28] [Render thread/WARN]: - The block minecraft:stone_slab has no property with the name variant, ignoring!
[21:21:28] [Render thread/WARN]: Error while parsing the block ID map entry for "block.60036":
[21:21:28] [Render thread/WARN]: - The block minecraft:dragon_head has no property with the name powered, ignoring!
[21:21:28] [Render thread/WARN]: Error while parsing the block ID map entry for "block.10364":
[21:21:28] [Render thread/WARN]: - The block minecraft:stone_slab has no property with the name variant, ignoring!
[21:21:28] [Render thread/WARN]: Error while parsing the block ID map entry for "block.10100":
[21:21:28] [Render thread/WARN]: - The block minecraft:stone has no property with the name variant, ignoring!
[21:21:28] [Render thread/WARN]: Error while parsing the block ID map entry for "block.10084":
[21:21:28] [Render thread/WARN]: - The block minecraft:stone has no property with the name variant, ignoring!
[21:21:28] [Render thread/WARN]: Error while parsing the block ID map entry for "block.10032":
[21:21:28] [Render thread/WARN]: - The block minecraft:stone_slab has no property with the name variant, ignoring!
[21:21:28] [Render thread/WARN]: Error while parsing the block ID map entry for "block.10088":
[21:21:28] [Render thread/WARN]: - The block minecraft:stone has no property with the name variant, ignoring!
[21:21:28] [Render thread/WARN]: Error while parsing the block ID map entry for "block.10104":
[21:21:28] [Render thread/WARN]: - The block minecraft:stone has no property with the name variant, ignoring!
[21:21:28] [Render thread/WARN]: Error while parsing the block ID map entry for "block.10096":
[21:21:28] [Render thread/WARN]: - The block minecraft:stone has no property with the name variant, ignoring!
[21:21:28] [Render thread/WARN]: Error while parsing the block ID map entry for "block.10416":
[21:21:28] [Render thread/WARN]: - The block minecraft:stone_slab has no property with the name variant, ignoring!
[21:21:28] [Render thread/INFO]: constructed ocean shader successfully
[21:21:28] [Render thread/INFO]: [STDOUT]: binding wonky attributes
[21:21:28] [Render thread/INFO]: constructed liquids shader successfully
[21:21:28] [Render thread/ERROR]: Unhandled game exception
net.mehvahdjukaar.supplementaries.common.utils.VibeChecker$BadModError: Some OTHER mod failed to load baked models. Refusing to proceed further to prevent in game issues. See logs for details
	at net.mehvahdjukaar.supplementaries.common.utils.fabric.VibeCheckerImpl.vibeCheckModels(VibeCheckerImpl.java:156) ~[supplementaries-1.20-2.7.32-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.utils.fabric.VibeCheckerImpl.checkVibe(VibeCheckerImpl.java:40) ~[supplementaries-1.20-2.7.32-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.checkVibe(VibeChecker.java) ~[supplementaries-1.20-2.7.32-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.fabric.SupplementariesFabric.lambda$onInitialize$0(SupplementariesFabric.java:21) ~[supplementaries-1.20-2.7.32-fabric.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-3792d0d4b63e847b.jar:?]
	at net.minecraft.class_310.handler$cpf001$fabric-lifecycle-events-v1$onStart(class_310.java:12033) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at net.mehvahdjukaar.moonlight.api.client.model.fabric.BakedQuadBuilderImpl.<init>(BakedQuadBuilderImpl.java:36) ~[moonlight-1.20-2.9.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.client.model.fabric.BakedQuadBuilderImpl.create(BakedQuadBuilderImpl.java:24) ~[moonlight-1.20-2.9.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.client.model.BakedQuadBuilder.create(BakedQuadBuilder.java) ~[moonlight-1.20-2.9.9-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.client.model.BakedQuadBuilder.create(BakedQuadBuilder.java:22) ~[moonlight-1.20-2.9.9-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.utils.fabric.VibeCheckerImpl.vibeCheckModels(VibeCheckerImpl.java:128) ~[supplementaries-1.20-2.7.32-fabric.jar:?]
	... 10 more
[21:21:28] [Render thread/INFO]: Stopping!
[21:21:28] [Render thread/INFO]: emissive suffixes loaded: {_e}.
[21:21:28] [Render thread/INFO]: emissive suffixes loaded: {_e}.
[21:21:28] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_1060.close(class_1060.java:174) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.close(class_310.java:1138) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java:1113) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:266) ~[1.20.1-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]

**Comment by guangroove** [comment]
I needed version 1.0.27 of Indium, compatible with Sodium 0.5.3
