### ISSUE TITLE
[🐞]: My game crashes everytime i try to open it 

### ISSUE THREAD

**Issue by Kosovoy12** [MehVahdJukaar/Supplementaries#959]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

Supplementaries (supplementaries), Version: 1.19.2-2.4.16

### Moonlight Lib Version

moonlight-1.19.2-2.3.6

### Issue Detail

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	Supplementaries (supplementaries), Version: 1.19.2-2.4.16
		Issue tracker URL: https://github.com/MehVahdJukaar/Supplementaries/issues
		at TRANSFORMER/supplementaries@1.19.2-2.4.16/net.mehvahdjukaar.supplementaries.common.block.blocks.UrnBlock.m_7381_(UrnBlock.java:211)
Stacktrace:
	at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.m_59640_(RandomizableContainerBlockEntity.java:68) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.m_8020_(RandomizableContainerBlockEntity.java:99) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.mehvahdjukaar.supplementaries.common.block.blocks.UrnBlock.m_7381_(UrnBlock.java:211) ~[supplementaries-1.19.2-2.4.16.jar%23703!/:?] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60724_(BlockBehaviour.java:710) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.BlockStateBaseMixin,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:modernfix-common.mixins.json:perf.reduce_blockstate_cache_rebuilds.BlockStateBaseMixin,pl:mixin:APP:supplementaries-common.mixins.json:BlockBehaviourPlanterMixin,pl:mixin:APP:starlight.mixins.json:common.blockstate.BlockStateBaseMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:lootr.mixins.json:MixinBlockStateBase,pl:mixin:APP:twigs.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:APP:valhelsia_core.mixins.json:BlockStateBaseMixin,pl:mixin:A}
	at net.minecraft.world.level.block.Block.m_49874_(Block.java:262) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_block_dropresources,re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_block_dropresources,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_block_dropresources,pl:mixin:APP:snowrealmagic.mixins.json:BlockMixin,pl:mixin:APP:embeddium.mixins.json:features.fast_biome_colors.MixinBlock,pl:mixin:APP:mixins.salt.json:BlockMixin,pl:mixin:APP:ad_astra-common.mixins.json:BlockMixin,pl:mixin:APP:blue_skies.mixins.json:BlockMixin,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:APP:cull-less-leaves.mixins.json:BlockMixin,pl:mixin:A}
	at net.minecraft.world.level.block.Block.m_49881_(Block.java:296) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_block_dropresources,re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_block_dropresources,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_block_dropresources,pl:mixin:APP:snowrealmagic.mixins.json:BlockMixin,pl:mixin:APP:embeddium.mixins.json:features.fast_biome_colors.MixinBlock,pl:mixin:APP:mixins.salt.json:BlockMixin,pl:mixin:APP:ad_astra-common.mixins.json:BlockMixin,pl:mixin:APP:blue_skies.mixins.json:BlockMixin,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:APP:cull-less-leaves.mixins.json:BlockMixin,pl:mixin:A}
	at net.mehvahdjukaar.supplementaries.common.entities.FallingUrnEntity.shatter(FallingUrnEntity.java:74) ~[supplementaries-1.19.2-2.4.16.jar%23703!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.entities.FallingUrnEntity.m_142535_(FallingUrnEntity.java:54) ~[supplementaries-1.19.2-2.4.16.jar%23703!/:?] {re:classloading}
	at net.minecraft.world.level.block.Block.m_142072_(Block.java:388) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_block_dropresources,re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_block_dropresources,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_block_dropresources,pl:mixin:APP:snowrealmagic.mixins.json:BlockMixin,pl:mixin:APP:embeddium.mixins.json:features.fast_biome_colors.MixinBlock,pl:mixin:APP:mixins.salt.json:BlockMixin,pl:mixin:APP:ad_astra-common.mixins.json:BlockMixin,pl:mixin:APP:blue_skies.mixins.json:BlockMixin,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:APP:cull-less-leaves.mixins.json:BlockMixin,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_7840_(Entity.java:1015) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,pl:mixin:APP:create.mixins.json:EntityMixin,pl:mixin:APP:entitycollisionfpsfix.mixins.json:MixinEntity,pl:mixin:APP:mixins.hammerlib.json:EntityMixin,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:APP:sliceanddice.mixins.json:EntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:EntityMixin,pl:mixin:APP:memoryleakfix.mixins.json:entityMemoriesLeak.Entity_clearMemoriesMixin,pl:mixin:APP:entityculling.mixins.json:CullableMixin,pl:mixin:APP:lambdynlights.mixins.json:lightsource.EntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:EntityInvoker,pl:mixin:APP:ad_astra-common.mixins.json:EntityMixin,pl:mixin:APP:aether.mixins.json:common.accessor.EntityAccessor,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEntity,pl:mixin:APP:piglinsafety.mixins.json:MixinEntity,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinEntity,pl:mixin:APP:railways-common.mixins.json:client.AccessorEntity,pl:mixin:APP:carryon.mixins.json:EntityMixin,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.misc.MixinEntity,pl:mixin:APP:blueprint.mixins.json:EntityMixin,pl:mixin:APP:travelerstitles.mixins.json:EntityChangeDimensionMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:mixins.irons_spellbooks.json:EntityMixin,pl:mixin:APP:mixins.irons_spellbooks.json:ClientEntityMixin,pl:mixin:APP:presencefootsteps.mixin.json:IEntity,pl:mixin:APP:sound_physics_remastered.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:create.mixins.json:client.EntityContraptionInteractionMixin,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_6478_(Entity.java:613) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,pl:mixin:APP:create.mixins.json:EntityMixin,pl:mixin:APP:entitycollisionfpsfix.mixins.json:MixinEntity,pl:mixin:APP:mixins.hammerlib.json:EntityMixin,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:APP:sliceanddice.mixins.json:EntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:EntityMixin,pl:mixin:APP:memoryleakfix.mixins.json:entityMemoriesLeak.Entity_clearMemoriesMixin,pl:mixin:APP:entityculling.mixins.json:CullableMixin,pl:mixin:APP:lambdynlights.mixins.json:lightsource.EntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:EntityInvoker,pl:mixin:APP:ad_astra-common.mixins.json:EntityMixin,pl:mixin:APP:aether.mixins.json:common.accessor.EntityAccessor,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEntity,pl:mixin:APP:piglinsafety.mixins.json:MixinEntity,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinEntity,pl:mixin:APP:railways-common.mixins.json:client.AccessorEntity,pl:mixin:APP:carryon.mixins.json:EntityMixin,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.misc.MixinEntity,pl:mixin:APP:blueprint.mixins.json:EntityMixin,pl:mixin:APP:travelerstitles.mixins.json:EntityChangeDimensionMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:mixins.irons_spellbooks.json:EntityMixin,pl:mixin:APP:mixins.irons_spellbooks.json:ClientEntityMixin,pl:mixin:APP:presencefootsteps.mixin.json:IEntity,pl:mixin:APP:sound_physics_remastered.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:create.mixins.json:client.EntityContraptionInteractionMixin,pl:mixin:A}
	at net.minecraft.world.entity.item.FallingBlockEntity.m_8119_(FallingBlockEntity.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:twigs.mixins.json:FallingBlockEntityInvoker,pl:mixin:APP:architectury.mixins.json:MixinFallingBlockEntity,pl:mixin:APP:blueprint.mixins.json:FallingBlockEntityMixin,pl:mixin:APP:quark.mixins.json:FallingBlockEntityMixin,pl:mixin:APP:create.mixins.json:accessor.FallingBlockEntityAccessor,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:alternate-current.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:thinair.common.mixins.json:ServerLevelMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,pl:mixin:APP:redirector-forge.mixins.json:net.minecraft.world.level.LevelMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:lambdynlights.mixins.json:WorldMixin,pl:mixin:APP:aether.mixins.json:common.accessor.LevelAccessor,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:alternate-current.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:thinair.common.mixins.json:ServerLevelMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:alternate-current.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:thinair.common.mixins.json:ServerLevelMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
-- Entity being ticked --
Details:
	Entity Type: supplementaries:falling_urn (net.mehvahdjukaar.supplementaries.common.entities.FallingUrnEntity)
	Entity ID: 114
	Entity Name: Falling Urn
	Entity's Exact location: -6959.50, -52.00, 3118.50
	Entity's Block location: World: (-6960,-52,3118), Section: (at 0,12,14 in -435,-4,194; chunk contains blocks -6960,-64,3104 to -6945,319,3119), Region: (-14,6; contains chunks -448,192 to -417,223, blocks -7168,-64,3072 to -6657,319,3583)
	Entity's Momentum: 0.00, -0.66, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Immitating BlockState: Block{supplementaries:urn}[treasure=false,waterlogged=false]
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_level_destroyblock,pl:mixin:APP:redirector-forge.mixins.json:net.minecraft.world.level.LevelMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:lambdynlights.mixins.json:WorldMixin,pl:mixin:APP:aether.mixins.json:common.accessor.LevelAccessor,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:alternate-current.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:thinair.common.mixins.json:ServerLevelMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:alternate-current.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:thinair.common.mixins.json:ServerLevelMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,xf:fml:openpartiesandclaims:xaero_pac_integratedserver_tickpaused,pl:runtimedistcleaner:A,re:classloading,xf:fml:openpartiesandclaims:xaero_pac_integratedserver_tickpaused,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23747!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

**Comment by MehVahdJukaar** [comment]
i need the whole latest.log

**Comment by meeprdib** [comment]
Mod versions on 1.19.2 and below are not supported
