### ISSUE TITLE
[🐞]: Can't find id for 'net.minecraft.sounds.SoundEvent@4adfb3d9' in map Registry (Server kicks client)

### ISSUE THREAD

**Issue by ItsYuriil** [MehVahdJukaar/Supplementaries#993]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2-FORGE

### Supplementaries Version

supplementaries-1.19.2-2.4.20

### Moonlight Lib Version

moonlight-1.19.2-2.3.6-forge

### Issue Detail

Well, I don't know what call for that event sound but it kicks everyone in the server that calls to that. I've been trying some mods in and out from the server and the result doesnt change much.

Mods that I know change sounds that are on my modpack: 
-Eerie Music: https://www.curseforge.com/minecraft/mc-mods/eerie-music-forge-fabric
-Sound Physics Remastered: https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered

The sound ID changes everytime I see the error pop up on the server log so I'm guessing its a dynamic event, but its always packet 96.

Anyways, I'm pretty sad to disable this mod from the modpack as I like it a lot, but until this is fixed I literally cant run the modpack without people randomly  disconecting from the server.

Here is the server log from the error + the client error message:

```
[07:13:03] [Netty Epoll Server IO #1/ERROR] [minecraft/PacketEncoder]: Error receiving packet 96
java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.sounds.SoundEvent@4adfb3d9' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
	at net.minecraft.network.FriendlyByteBuf.m_236818_(FriendlyByteBuf.java:125) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries.mixins.json:FriendlyByteBufMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ClientboundSoundPacket.m_5779_(ClientboundSoundPacket.java:47) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:45) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:classloading}
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:classloading}
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar%2380!/:4.1.77.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) ~[netty-codec-4.1.77.Final.jar%2380!/:4.1.77.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}	
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
	at net.minecraft.network.Connection.m_243087_(Connection.java:209) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:198) ~[server-1.19.2-20220805.130853-srg.jar%23325!/:?] {re:mixin,re:classloading}
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar%2385!/:4.1.77.Final] {}
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}
```

`[07:13:03] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: ItssYuri lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.sounds.SoundEvent@4adfb3d9' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]`

**Comment by MehVahdJukaar** [comment]
Check server has same mods as clients. Also are you sure this is a supplementaries issue?

**Comment by ItsYuriil** [comment]
> Check server has same mods as clients. Also are you sure this is a supplementaries issue?

100%, Its the only mod giving me any kind of conflict that makes the client getting kicked, and well, Eerie Music is clientside and I tried both with both Eerie Music and Sound Physics Remastered disabled and the problem still persisted.

I ran the server without that mod and its not giving any errors like that anymore, so I'm pretty sure its something that has to be within this mod

**Comment by MehVahdJukaar** [comment]
And do you know which of you other mods, when disabled, makes this error go away?

**Comment by ItsYuriil** [comment]
Since I added Supplementaries fairly late, I have no idea, I'll try to locate what mods does it conflict with, but there are a lot of them who calls to soundevents (the modpack has over 120 mods).

But what mod could it be conflicting with? Is that call common? Do you know what call is supplementaries trying to get based on the error message? Maybe with that info I can filter out some mods there.

**Comment by ItsYuriil** [comment]
>Do you know what call is supplementaries trying to get based on the error message? Maybe with that info I can filter out some mods there.

By this I mean if you know what the game is trying to do there, or what supplementaries is trying to achieve with that call (I have no idea)

**Comment by MehVahdJukaar** [comment]
Very hard to tell but definitely some mod that has sounds. Do you have no fog? I heard some people having an issue with that

**Comment by ItsYuriil** [comment]
Nope, found the bug, it was another mod what ran made an invalid sound call, very weird cos the error redirected to the lines of supplementary functions working, my bad.

I'm closing this bug as is not related to this mod. 
Thanks for the support

**Comment by valrimmer** [comment]
So what even was the mod lol

**Comment by Ymmit34** [comment]
What was the issue? I'm having the same error and would like to know how to proceed

**Comment by EastRane** [comment]
same problem

**Comment by PineappleTwilight** [comment]
For anybody having this problem, "The Flesh That Hates" caused this for me. However it appears to be caused by any mod that attempts to call an invalid sound. Check the logs before the exception and see if there's a sound failiure.
